"""Facility pages - all six built from the shared CMS template.

Every page here uses "template": "facility", which renders the fixed
section order defined in components.facility_sections(). The field names
below deliberately match the Webflow "Facilities" collection fields
(kicker, secH2, wisCopy, chk, fboxes, pricing, steps, faqs, boxH2 ...) so
moving this into the CMS is a field mapping exercise, not a rebuild.

Two corrections applied against the supplied CMS design, both recorded in
FACTS.md: the postcode is DE5 9RJ, not 9RL, and the basket prices are the
ones the client confirmed on 30 Jul (£4.00 / £7.50 / £10.00 / £12.50),
not the stale £4 / £7 / £9 / £11 set.
"""

BOOK = "https://evolutiongolfacademy.setmore.com/book"
MAPS = "https://www.google.com/maps/place/Evolution+Golf+Academy"
DIRECTIONS = {"label": "Get directions", "href": MAPS}
BOOK_LESSON = {"label": "Book a lesson", "href": BOOK}
ASK = {"label": "Ask a question", "href": "contact.html"}

PAGES = [

    # ============================================== TRACKMAN DRIVING RANGE
    {
        "template": "facility",
        "file": "trackman-range.html",
        "cur": "trackman-range.html",
        "name": "Trackman Driving Range",
        "title": "Trackman Driving Range Derby &amp; Nottingham | Covered Floodlit Bays | Evolution Golf Academy",
        "desc": "Trackman driving range near Derby and Nottingham. Covered, floodlit bays with tour level ball data on every shot. Walk in, no booking, baskets from £4. Open 7am to 8pm daily in Ripley.",
        "reviews": ["ciaran", "steve", "lisa"],
        "hero": {
            "kick": "Trackman Driving Range in Derby &amp; Nottingham",
            "l1": "Trackman", "l2": "Range.",
            "p": "Come experience a Trackman range with tour proven technology in a relaxed environment, with spacious bays for you to play, practise and play games. With our floodlights you can practise all year round.",
            "img": "range_night",
            "alt": "Trackman driving range near Derby and Nottingham at Evolution Golf Academy",
            "chips": [("Carry", "148", "yds"), ("Ball speed", "112", "mph"), ("Smash factor", "1.37", "")],
            "chips_head": ("Session", "7 iron · 18 shots"),
        },
        "eyebrow1": "● Trackman Driving Range in Derby &amp; Nottingham | Evolution Golf Academy",
        "secH2": "Trackman driving range near <em>Derby &amp; Nottingham</em>",
        "wisImg": "bay_night",
        "wisCopy": [
            ("p", "Our Trackman driving range sits at Ormonde Fields Golf Club on Nottingham Road in Codnor, right between Derby and Nottingham. Around 20 minutes from Derby, 25 from Nottingham and a few minutes from Ripley, Heanor and Ilkeston."),
            ("p", "Spacious covered bays with floodlights mean you can practise in any weather, morning or evening, all year round. Free parking directly outside the bays, so you are hitting balls two minutes after you park."),
            ("p", "No booking and no membership. Pay contactless at the ball dispenser, pick a free bay and start hitting. Golfers travel to us from across <a href=\"location.html\">Derby, Nottingham and Derbyshire</a> because there is nowhere closer with this technology."),
            ("h3", "What Makes a Trackman Range Different to a Normal Driving Range?"),
            ("p", "On a standard range you hit a ball, watch it disappear into the dark and guess. Trackman removes the guessing. Dual radar tracks the club through impact and the ball through its flight, then reports what actually happened: ball speed, launch angle, spin rate, carry distance, club path and face angle, on the screen in your bay about a second after you strike it."),
            ("p", "That changes what practice is worth. Most golfers overestimate how far they hit each club by ten to fifteen yards, which is the difference between the middle of the green and the bunker short of it. An hour in a bay gives you real carry numbers for every club in the bag, and those numbers are the foundation of every scoring decision you make on the course."),
            ("h3", "Do I Need to Understand the Numbers to Get Something Out of It?"),
            ("p", "No. Ignore everything except carry distance on your first visit and you will still leave knowing your yardages better than most players at your club. The rest of the data is there when you want it, and if it raises a question you cannot answer, that is exactly what a session in the <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a> is for."),
            ("p", "Plenty of golfers use the range purely for the games. Closest to the pin, virtual courses and long drive competitions turn a bucket of balls into something you actually want to finish, which is why the bays fill up with families and groups of friends as well as single figure players grinding out dispersion work."),
        ],
        "chkTitle": "● The Trackman range is for you if you want to",
        "chk": [
            "See real numbers instead of guessing where the ball went",
            "Practise in the dry, in any weather, all year round",
            "Play games and challenges rather than beat balls",
            "Warm up properly before a round",
            "Work on a change your coach gave you in a lesson",
            "Turn up whenever suits, with no booking needed",
        ],
        "cta2": DIRECTIONS,
        "cta3": {"label": "View ball prices", "href": "#pricing"},
        "eyebrow2": "● Driving range in Codnor, Ripley",
        "boxH2c": "What the Trackman range <em>actually gives you</em>",
        "boxSub": "Four things every bay does, on every shot, for every golfer who walks in.",
        "fboxes": [
            {"t": "Live data", "b": "Ball speed, launch, spin, carry and club path on screen the moment you strike. No waiting, no guessing, and nothing to set up before you start.", "img": "launch_data"},
            {"t": "Covered &amp; floodlit", "b": "Spacious bays under cover with floodlights, so rain and dark winter nights are not a problem. The range runs seven days a week, all year round.", "img": "range_sil"},
            {"t": "Games &amp; challenges", "b": "Closest to the pin, virtual courses and long drive, on your own or against friends. Practice you actually want to finish.", "img": "bay_screen"},
            {"t": "Walk in, no booking", "b": "Turn up, pay contactless at the dispenser and take any free bay. No membership, no minimum spend and no waiting for a slot.", "img": "ball_tee"},
        ],
        "closer": "Practice without feedback is just exercise. Every bay here tells you what actually happened, so the hour you spend counts towards a lower score rather than simply tiring your hands out.",
        "cta4": DIRECTIONS,
        "pricing": {
            "kick": "● Trackman driving range in Codnor, Ripley",
            "h2": "Pricing", "h2b": "Pay by the basket, nothing else.",
            "p": "No booking fee, no membership and no minimum spend. Choose your basket size at the dispenser, pay contactless and hit. Bigger baskets work out cheaper per ball.",
            "panels": [
                {"title": "Standard Baskets", "badge": "Open 7 days · 7am to 8pm", "cells": [
                    {"lb": "Small Basket", "pv": "£4.00", "per": "30 balls"},
                    {"lb": "Medium Basket", "pv": "£7.50", "per": "60 balls", "pp": "Most popular"},
                    {"lb": "Large Basket", "pv": "£10.00", "per": "90 balls", "pp": "Better value per ball"},
                    {"lb": "Jumbo Basket", "pv": "£12.50", "per": "120 balls", "pp": "Best value per ball"},
                ], "footnote": "Perfect for a full practice session with Trackman on every shot."},
                {"title": "Private Bay Hire", "badge": "Booked by the hour", "cells": [
                    {"lb": "Private Trackman bay", "pv": "£15.00", "per": "per hour",
                     "body": "Have the bay to yourself with full club and ball data plus video. Booked separately by the hour, and the sensible choice if you want to work through the whole bag without interruption."},
                ], "footnote": "Members get priority booking and better rates. See memberships for details."},
            ]},
        "procKick": "● How it works",
        "procH2": "Your first visit to <em>the range</em>",
        "procSub": "Four steps from car park to first ball. It really is this simple.",
        "procImg": "student_swing",
        "steps": [
            {"t": "Arrive at the academy", "b": "We are on Nottingham Road, Codnor. Park directly outside the driving range bays, free of charge."},
            {"t": "Pay at the dispenser", "b": "Contactless payment on the ball dispenser in the bays. Choose your basket size and collect your balls."},
            {"t": "Pick any free bay", "b": "Every bay is Trackman equipped, so there is no better or worse one to aim for. Your screen is already on and ready."},
            {"t": "Hit, track, play", "b": "Practise with your numbers on screen, or load a game and play against a mate. Club hire is available if you arrive without a set."},
        ],
        "cta5": DIRECTIONS,
        "faqKick": "● Top questions from golfers",
        "faqH2": "Trackman driving range Derby &amp; Nottingham <em>FAQs</em>",
        "faqs": [
            ("Do I need to book the driving range?", "No. The Trackman range is walk in, seven days a week from 7am to 8pm. Pay contactless at the ball dispenser and take any free bay. Bays are first come, first served, and it is rare to wait long even on a busy winter evening."),
            ("How much are range balls?", "Baskets are £4.00 for 30 balls, £7.50 for 60, £10.00 for 90 and £12.50 for 120. Pay at the dispenser in the bays. The larger baskets work out cheaper per ball, so a 90 or 120 is the better buy for a full session."),
            ("Do I need my own clubs?", "Bring your own if you have them, since practising with the clubs you play with is always more useful. If you do not have a set, club hire is included at no extra cost, so nobody needs to buy equipment before finding out whether they enjoy the game."),
            ("Is the range open in winter?", "Yes. The bays are covered and floodlit, so the range runs all year round, seven days a week. Winter is when the Trackman bays earn their keep, because the numbers on screen do not care that it is dark and raining."),
            ("Where is the range?", "Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RJ, between Derby and Nottingham. Roughly 20 minutes from Derby city centre, 25 from Nottingham and a few minutes from Ripley, Heanor and Ilkeston."),
            ("Can I have a lesson on the range?", "Yes. Book a lesson with our PGA Professional and we can use the range bays or the <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a>, depending on what you are working on. Both use the same launch monitor data."),
        ],
        "visit_kick": "Trackman range near Derby &amp; Nottingham",
        "visitH2": "Trackman driving range near <em>Derby &amp; Nottingham</em>",
        "boxH2": "Ready to hit <em>some balls?</em>",
        "boxP": "No booking, no membership, no waiting. Turn up today, pay at the dispenser and take any free bay. Open seven days a week, 7am to 8pm, in Codnor near Ripley.",
        "boxBtn1": DIRECTIONS,
        "boxBtn2": {"label": "View ball prices", "href": "#pricing"},
        "boxNote": "No booking needed · Open 7 days, 7am to 8pm · Codnor, Ripley DE5 9RJ",
    },

    # =================================================== TRACKMAN SIMULATOR
    {
        "template": "facility",
        "file": "trackman-simulator.html",
        "cur": "trackman-simulator.html",
        "name": "Trackman Simulator",
        "title": "Golf Simulator Derby &amp; Nottingham | Trackman Indoor Bays | Evolution Golf Academy",
        "desc": "Trackman golf simulator near Derby and Nottingham. Play world famous courses indoors, practise all winter and see real ball data. From £13 per hour off peak, open 7am to 8pm daily in Ripley.",
        "reviews": ["lisa", "ciaran", "irene"],
        "hero": {
            "kick": "Trackman Golf Simulator in Derby &amp; Nottingham",
            "l1": "Trackman", "l2": "Simulator.",
            "p": "Play the world's greatest golf courses indoors on a Trackman simulator. Full shot data, virtual rounds with friends and practice that counts, whatever the weather outside.",
            "img": "sim",
            "alt": "Trackman golf simulator near Derby and Nottingham at Evolution Golf Academy",
        },
        "quickbar": [
            ("clock", "Open daily", "7:00am to 8:00pm"),
            ("tag", "Off-peak from", "£13.00 per hour"),
            ("check", "Group friendly", "Up to 4 players per bay"),
            ("pin", "DE5 9RJ", "Free on-site parking"),
        ],
        "eyebrow1": "● Trackman Golf Simulator in Derby &amp; Nottingham | Evolution Golf Academy",
        "secH2": "Indoor golf simulator near <em>Derby &amp; Nottingham</em>",
        "wisImg": "bay_indoor",
        "wisCopy": [
            ("p", "Our Trackman simulator is at Ormonde Fields Golf Club, Codnor, on the Derby to Nottingham road. Around 20 minutes from Derby, 25 from Nottingham, and the closest simulator of its kind for golfers in Ripley, Heanor and Ilkeston."),
            ("p", "Play full rounds on famous courses, work on your game with complete shot data, or compete with friends. Up to four players can share a bay, and the more of you there are, the cheaper it gets per person."),
            ("p", "Because it is indoors, weather never cancels your golf. Golfers from across <a href=\"location.html\">Derby, Nottingham and Derbyshire</a> book the simulator through winter to keep playing while the courses are wet."),
            ("h3", "How Does a Golf Simulator Actually Work?"),
            ("p", "You hit a real golf ball with your own clubs into a screen a few yards away. Trackman's radar tracks the club through impact and the ball through the first part of its flight, then models the rest from the measured launch conditions: ball speed, launch angle, spin rate, spin axis and attack angle. Because it measures rather than guesses, a thin three iron looks like a thin three iron on screen, and a well struck one runs out the way it should."),
            ("p", "That accuracy is what separates a Trackman bay from the camera based systems in most bars and entertainment venues. It is the same dual radar technology used on the PGA Tour and on the range at major championships, which is why the carry numbers you see indoors match the ones you get outside on a still day."),
            ("h3", "Is It the Same Technology as the Driving Range Bays?"),
            ("p", "It is the same launch monitor and the same measurements you see in the <a href=\"trackman-range.html\">Trackman driving range bays</a>, doing a different job. The range is about volume and immediate feedback. The simulator wraps that data in a golf course, a target and a score, which changes how you behave. Golfers concentrate differently when there is water short of the green, even an imaginary one."),
            ("p", "That makes the simulator the better choice for pressure practice and for playing with friends, and the range the better choice for working through the bag. Most regulars use both. If you want the numbers explained rather than simply displayed, that is a coaching conversation, and it happens next door in the <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a> with an Advanced PGA Professional."),
        ],
        "chkTitle": "● The simulator is for you if you want to",
        "chk": [
            "Play golf when the weather has ruined the course",
            "Play famous courses without leaving Derbyshire",
            "Have a round with friends in the warm",
            "Practise with full shot data on real clubs",
            "Keep your game sharp through winter",
            "Book a fixed hour rather than turn up",
        ],
        "cta2": {"label": "Book a simulator", "href": BOOK},
        "cta3": {"label": "See the range", "href": "trackman-range.html"},
        "eyebrow2": "● Indoor golf in Codnor, Ripley",
        "boxH2c": "What the simulator <em>actually gives you</em>",
        "boxSub": "Golf that carries on regardless of what the forecast is doing.",
        "fboxes": [
            {"t": "Famous courses", "b": "Full virtual rounds on world famous courses, links classics and major venues, played with your own clubs and a real ball.", "img": "sim"},
            {"t": "Full shot data", "b": "Every shot measured exactly as on tour: ball speed, launch, spin and carry, saved so you can compare against your last visit.", "img": "trackman_screen"},
            {"t": "Up to 4 players", "b": "Group play, games and competitions, from £6 each per hour off peak. One of the cheapest nights out in Derbyshire that also improves your golf.", "img": "on_course"},
            {"t": "All weather golf", "b": "Indoors and warm. Rain, wind and dark nights make no difference, which is why the bays are busiest between November and March.", "img": "bay_indoor"},
        ],
        "closer": "A simulator is not a compromise on real golf. It is a way to keep playing and keep improving in the months when the course will not let you, and the data means those months count for something.",
        "cta4": {"label": "Book a simulator", "href": BOOK},
        "pricing": {
            "kick": "● Trackman simulator in Codnor, Ripley",
            "h2": "Pricing", "h2b": "Flexible pricing that makes sense.",
            "p": "Whether you are practising or playing with friends, our pricing is designed around the way you use the simulator. Solo golfers benefit from lower off peak prices and maximum Trackman time, while groups can share the cost for an affordable indoor golf experience.",
            "panels": [
                {"title": "Off-Peak", "badge": "Mon to Fri, 8am to 2pm", "cells": [
                    {"lb": "1 Player", "pv": "£13", "per": "per hour"},
                    {"lb": "2 Players", "pv": "£17", "pp": "Just £8.50 per person"},
                    {"lb": "3 Players", "pv": "£21", "pp": "Just £7.00 per person"},
                    {"lb": "4 Players", "pv": "£24", "pp": "Just £6.00 per person"},
                ], "footnote": "Perfect for practice with maximum Trackman time."},
                {"title": "Peak", "badge": "Mon to Fri, 2pm to 10pm · Weekends", "cells": [
                    {"lb": "Up to 4 Players", "pv": "£25", "per": "per hour",
                     "body": "One fixed price for exclusive simulator hire, whether you are practising on your own or playing with friends."},
                ], "footnote": "Great for an evening round with friends, whatever the weather."},
            ]},
        "procKick": "● How it works",
        "procH2": "Your simulator <em>session</em>",
        "procSub": "Book a bay, turn up, play. Four steps from booking to first tee.",
        "procImg": "bay_screen",
        "steps": [
            {"t": "Book your bay online", "b": "Choose your hour and pay online. Off peak and peak rates apply per bay, not per player."},
            {"t": "Arrive 5 minutes early", "b": "Your bay will be set up and ready when you walk in, so you use the full hour you paid for."},
            {"t": "Choose your format", "b": "A famous course, a practice range session or a Trackman game. Switch between them whenever you like."},
            {"t": "Play", "b": "Every shot tracked. Scores and numbers saved so you can compare against your next visit."},
        ],
        "cta5": {"label": "Book a simulator", "href": BOOK},
        "faqKick": "● Top questions from golfers",
        "faqH2": "Trackman simulator Derby &amp; Nottingham <em>FAQs</em>",
        "faqs": [
            ("Do I need to book the simulator?", "Yes. The simulator is booked by the hour online so your bay is guaranteed when you arrive. Evenings and weekends fill up first through winter, so book ahead if you want a peak slot."),
            ("How much does it cost?", "Off peak, from £13 per hour for one player up to £24 for four, which works out at £6 each. Peak is a fixed £25 per hour for up to four players. The price is per bay, so splitting it between friends is always the cheapest way to play."),
            ("How many people can play?", "Up to four golfers per bay, which is ideal for a group round or a competition with friends. Rounds take longer with four, so most groups book two hours if they want to finish eighteen holes."),
            ("Do I use my own clubs?", "Yes, real clubs and real balls into the impact screen. Bring your own if you have them, and if you do not, ask us about clubs when you book and we will sort it."),
            ("What courses can I play?", "A large library of famous courses, including links classics and major championship venues, plus practice ranges and a set of Trackman games and challenges for when you do not fancy a full round."),
            ("Is it good for beginners?", "Very. The data and the relaxed indoor setting make it a great place to start, with nobody watching and no pressure to keep up with a group behind. Lessons can be taken in the bay too, so a beginner can learn and play in the same place."),
        ],
        "visit_kick": "Golf simulator near Derby &amp; Nottingham",
        "visitH2": "Indoor golf simulator near <em>Derby &amp; Nottingham</em>",
        "boxH2": "Ready to play <em>your next round?</em>",
        "boxP": "Grab an hour on the simulator, bring up to three friends and play a famous course tonight. Booked online in under a minute, from £6 each off peak.",
        "boxBtn1": {"label": "Book a simulator", "href": BOOK},
        "boxBtn2": ASK,
        "boxNote": "Booked by the hour · From £13 off peak, £25 peak · Codnor, Ripley DE5 9RJ",
    },

    # ================================================ TRACKMAN TEACHING BAY
    {
        "template": "facility",
        "file": "trackman-teaching-bay.html",
        "cur": "trackman-teaching-bay.html",
        "name": "Trackman Teaching Bay",
        "title": "Trackman Teaching Bay Golf Lessons Derby | Private Coaching Bay | Evolution Golf Academy",
        "desc": "Private Trackman teaching bay for golf lessons near Derby and Nottingham. Tour level data, video analysis you keep, training aids and mirrors, with an Advanced PGA Professional.",
        "reviews": ["ian", "reece", "irene"],
        "hero": {
            "kick": "Trackman Teaching Bay Golf Lessons Derby &amp; Nottingham",
            "l1": "Teaching", "l2": "Bay.",
            "p": "A private indoor teaching bay built for golf lessons. Full Trackman data, video swing analysis and a PGA Professional alongside you, so every lesson is backed by what your swing is actually doing.",
            "img": "over_shoulder",
            "alt": "PGA coach and golfer in the Trackman teaching bay near Derby and Nottingham",
        },
        "quickbar": [
            ("check", "1:1 coaching", "Advanced PGA Professional"),
            ("tag", "Single lesson", "£55 for 60 minutes"),
            ("clock", "Open daily", "7:00am to 8:00pm"),
            ("pin", "DE5 9RJ", "Free on-site parking"),
        ],
        "eyebrow1": "● Trackman Teaching Bay in Derby &amp; Nottingham | Evolution Golf Academy",
        "secH2": "Golf lessons near <em>Derby &amp; Nottingham</em>",
        "wisImg": "coach_feedback",
        "wisCopy": [
            ("p", "Our Trackman teaching bay is at Ormonde Fields Golf Club, Codnor, between Derby and Nottingham. Around 20 minutes from Derby city centre, 25 from Nottingham, and minutes from Ripley, Heanor and Ilkeston."),
            ("p", "Equipped with industry leading Trackman technology, training aids, mirrors and professional coaching equipment, every lesson is designed to give you the feedback, understanding and support needed to make lasting improvements."),
            ("p", "It is where all of our <a href=\"1-1-lessons.html\">golf lessons in Derby and Nottingham</a> take place, taught one to one by <a href=\"meet-team.html\">Advanced PGA Professional Will Painter</a>."),
            ("h3", "Why Does a Private Bay Make a Difference to a Lesson?"),
            ("p", "Learning a movement requires attention, and attention is the first thing an open range takes away. Golfers self-consciously hitting shots in front of an audience swing faster, rush between balls and stop asking questions. Put the same golfer in a quiet bay with a screen, a mirror and a coach and the questions start coming, which is when a lesson begins to earn its money."),
            ("p", "In plain terms, it is a room rather than a bay on a busy range. Nobody is hitting a driver two feet to your left, nobody is waiting for the ball dispenser behind you, and nothing you are told gets lost in the noise. For golfers travelling in from Derby, Nottingham and across Derbyshire, that hour is the part of the week where the work actually gets done."),
            ("h3", "What Technology Is in the Bay?"),
            ("p", "Trackman dual radar for ball and club data, high speed video from two angles, full length mirrors for real time feedback on posture and plane, and the training aids an Advanced PGA Professional reaches for when a picture is worth more than an explanation. The same Trackman numbers you see on the <a href=\"trackman-range.html\">Trackman driving range</a> are here, with someone qualified sitting next to them."),
            ("p", "The bay is used for every kind of coaching we run, from <a href=\"beginner-coaching.html\">beginner golf lessons</a> through to low handicap players chasing tighter dispersion, and for the indoor sessions on the <a href=\"monthly-programme.html\">monthly coaching programme</a>. Your swing videos are sent to you afterwards, so the lesson does not evaporate on the drive home."),
        ],
        "chkTitle": "● A lesson in the Teaching Bay suits you if",
        "chk": [
            "You want to know why, not just what to change",
            "You have had tips before but nothing stuck",
            "You would rather not be watched by the whole range",
            "You want your swing on video to review at home",
            "You want changes backed by numbers, not opinions",
            "You are starting from scratch and want it done properly",
        ],
        "cta2": BOOK_LESSON,
        "cta3": {"label": "See golf lessons", "href": "1-1-lessons.html"},
        "eyebrow2": "● Golf lessons in Codnor, Ripley",
        "boxH2c": "What the Teaching Bay <em>actually gives you</em>",
        "boxSub": "Four things behind every lesson taught in the bay.",
        "fboxes": [
            {"t": "Trackman data", "b": "Tour proven radar measures club and ball on every shot, so we work from facts rather than from what the strike felt like to either of us.", "img": "launch_data"},
            {"t": "Video analysis", "b": "Every swing recorded alongside its data, from two angles. Your videos are sent home afterwards so you can review them whenever you like.", "img": "over_shoulder"},
            {"t": "Performance testing", "b": "Skills measured under pressure, so coaching targets what is genuinely costing you shots rather than what is easiest to teach.", "img": "trackman_screen"},
            {"t": "Training aids &amp; mirrors", "b": "Full length mirrors and the right aid at the right moment, for when seeing the position beats another explanation of it.", "img": "lesson_grip"},
        ],
        "closer": "Most golfers are not short of tips. They are short of a clear reason why. The bay exists so you leave every lesson knowing exactly what to work on next, and why it will make a difference.",
        "cta4": BOOK_LESSON,
        "procKick": "● How it works",
        "procH2": "Your first <em>golf lesson</em>",
        "procSub": "From booking to a clear plan in your hand, in four steps.",
        "procImg": "lesson_grip",
        "steps": [
            {"t": "Book your lesson", "b": "One to one with an Advanced PGA Professional. Book online or call us on 07710 582036."},
            {"t": "A relaxed start", "b": "The bay is private and quiet. We talk through your game and what you want from it before you swing a club."},
            {"t": "Measured and filmed", "b": "Your swing on Trackman and on video, so we can both see what is really happening rather than what it felt like."},
            {"t": "Leave with a plan", "b": "A clear plan and your swing videos, so practice between lessons has a point and a target."},
        ],
        "cta5": BOOK_LESSON,
        "faqKick": "● Top questions from golfers",
        "faqH2": "Golf lessons Derby &amp; Nottingham <em>FAQs</em>",
        "faqs": [
            ("How much is a golf lesson?", "A single one to one lesson is £55 for 60 minutes with our Advanced PGA Professional, with Trackman data and video analysis included. Blocks of lessons and the monthly programme work out cheaper per session and tend to produce better results."),
            ("Do I need my own clubs?", "Bring them if you have them, because coaching around the clubs you actually play with is more useful. If you do not have a set, tell us when booking and we will provide clubs at no extra cost."),
            ("Am I too old or too much of a beginner for lessons?", "No. We coach complete beginners through to low handicap golfers, and every lesson is built around you rather than a fixed syllabus. Plenty of people take their first lesson having never held a club."),
            ("Do I get my swing videos?", "Yes. Your recordings are sent to you after the lesson so you can review them at home, and so you have a genuine before and after to look back on a few months later."),
            ("How often should I have lessons?", "Most golfers see the fastest progress on a regular block or the <a href=\"monthly-programme.html\">monthly programme</a> rather than one off lessons. A single lesson can fix one clear fault, but lasting change needs a few sessions and some practice in between."),
            ("Where do lessons take place?", "In the Trackman teaching bay at Ormonde Fields Golf Club, Codnor, Ripley DE5 9RJ. Some lessons move out to the range or the short game area if that suits what we are working on."),
        ],
        "visit_kick": "Trackman golf lessons near Derby &amp; Nottingham",
        "visitH2": "Golf lessons near <em>Derby &amp; Nottingham</em>",
        "boxH2": "Ready to stop <em>guessing?</em>",
        "boxP": "Book your first lesson with our Advanced PGA Professional and leave knowing exactly what to work on, backed by your own Trackman numbers and swing videos.",
        "boxBtn1": BOOK_LESSON,
        "boxBtn2": ASK,
        "boxNote": "Lessons £55 per hour · Book online or call 07710 582036 · Codnor, Ripley DE5 9RJ",
    },

    # =================================================== GOLF FITNESS SUITE
    {
        "template": "facility",
        "file": "golf-fitness.html",
        "cur": "golf-fitness.html",
        "name": "Golf Fitness Suite",
        "title": "Golf Fitness &amp; TPI Screening Derby &amp; Nottingham | Evolution Golf Academy",
        "desc": "Golf fitness suite and TPI movement screening near Derby and Nottingham. Find the physical limits holding your swing back, then train around them. TPI certified, in Ripley, Derbyshire.",
        "reviews": ["ian", "irene", "reece"],
        "hero": {
            "kick": "Golf Fitness &amp; TPI Screening in Derby &amp; Nottingham",
            "l1": "Golf Fitness", "l2": "Suite.",
            "p": "A fitness suite built for golfers. TPI movement screening, golf specific strength and mobility work, so your body can support the swing you are building.",
            "img": "team",
            "alt": "Golf fitness suite and TPI screening near Derby and Nottingham",
        },
        "eyebrow1": "● Golf Fitness &amp; TPI Screening in Derby &amp; Nottingham | Evolution Golf Academy",
        "secH2": "Golf fitness &amp; TPI screening in <em>Derbyshire</em>",
        "wisImg": "tpi",
        "wisCopy": [
            ("p", "Your golf swing can only do what your body allows. If you cannot rotate, you cannot make the move a coach asks for, no matter how many lessons you take."),
            ("p", "The golf fitness suite pairs a TPI movement screen with golf specific strength and mobility work. We find the physical limitation first, then build a swing and a training plan that fit the body you actually have."),
            ("p", "It works alongside your <a href=\"1-1-lessons.html\">golf lessons</a>, and is the reason changes made in the <a href=\"trackman-teaching-bay.html\">teaching bay</a> tend to stick rather than fade after a fortnight."),
            ("h3", "What Is TPI Screening and Why Does It Matter?"),
            ("p", "TPI stands for Titleist Performance Institute, the body that developed the standard movement screen used by tour coaches and physiotherapists worldwide. The screen is a series of physical tests covering rotation, stability, mobility and balance, and it takes around 45 minutes to work through the full set."),
            ("p", "The point is not to grade your fitness. It is to find the specific restrictions that make certain swing faults almost inevitable. A golfer who cannot separate their hips from their shoulders will slide rather than turn, and no amount of being told to turn will change that until the restriction is addressed. Screening first means the coaching that follows is aimed at something real."),
            ("h3", "Do I Need to Be Fit Before I Come?"),
            ("p", "No, and most golfers who book a screening are not. The screen simply establishes where you are now. Some people leave with three mobility drills to do at home, others with a strength plan, and a few with a referral because what we have found needs a physiotherapist rather than a golf coach."),
            ("p", "It is equally useful at the other end. Golfers chasing distance often assume they need to swing harder, when the speed they are missing is locked up in a restricted turn or a lack of ground force. Screening finds that, and the <a href=\"swingfit.html\">SwingFit programme</a> and <a href=\"tpi-screening.html\">TPI screening page</a> cover how we build the training around it."),
        ],
        "chkTitle": "● A TPI screening is for you if",
        "chk": [
            "You cannot make the move your coach keeps asking for",
            "Your back or hips ache after a round",
            "You lose distance and cannot work out why",
            "You feel stiff on the first tee no matter how you warm up",
            "You want more speed without swinging harder",
            "You want to keep playing pain free for years",
        ],
        "cta2": {"label": "Book a screening", "href": BOOK},
        "cta3": {"label": "See TPI Screening", "href": "tpi-screening.html"},
        "eyebrow2": "● TPI screening in Codnor, Ripley",
        "boxH2c": "What the Fitness Suite <em>actually gives you</em>",
        "boxSub": "Four areas that decide what your swing is physically capable of.",
        "fboxes": [
            {"t": "TPI movement screen", "b": "A full body screen showing how you move and what your swing can realistically do, matched against your Trackman numbers.", "img": "tpi"},
            {"t": "Golf strength", "b": "Speed, power and resilience built with training designed around the golf swing rather than borrowed from general gym work.", "img": "team"},
            {"t": "Mobility &amp; stability", "b": "Targeted work on whatever is limiting your turn, posture and balance, prescribed from what the screen actually found.", "img": "student_swing"},
            {"t": "Injury prevention", "b": "Move better, swing within your means and stay playing pain free for longer, which matters more the further into your golfing life you get.", "img": "on_course"},
        ],
        "closer": "Coaching the swing without checking the body is guesswork. Screen first, and the plan you get is one your body can actually carry out.",
        "cta4": {"label": "Book a screening", "href": BOOK},
        "procKick": "● How it works",
        "procH2": "Your TPI <em>screening</em>",
        "procSub": "A full movement assessment and a plan built on what it finds.",
        "procImg": "student_swing",
        "steps": [
            {"t": "Book your screening", "b": "A TPI movement screen takes around 45 minutes. Book online or call us on 07710 582036."},
            {"t": "Full body assessment", "b": "We test rotation, stability, mobility and balance through the whole body, working through the standard TPI screen."},
            {"t": "Linked to your swing", "b": "Your results are matched to your swing characteristics, so the causes of your faults become obvious rather than theoretical."},
            {"t": "Leave with a plan", "b": "Exercises, coaching or both, built around what your body needs first and what will make the fastest difference."},
        ],
        "cta5": {"label": "Book a screening", "href": BOOK},
        "faqKick": "● Top questions from golfers",
        "faqH2": "Golf fitness &amp; TPI screening <em>FAQs</em>",
        "faqs": [
            ("What is a TPI screening?", "A Titleist Performance Institute movement screen. It is a standard set of physical tests that assesses how your body moves and links that directly to your golf swing, so we can see which faults are technique and which are physical."),
            ("How long does it take?", "Around 45 minutes for the full screen, plus time afterwards to talk through your results and agree a plan. Most people are with us for a little over an hour in total."),
            ("Do I need to be fit already?", "No. The screen tells us where you are now, and the plan starts from there. Golfers of every age and fitness level book screenings, and a good number have never done structured training in their lives."),
            ("Will it help my distance?", "Often yes. Speed usually comes from moving better rather than swinging harder, and the screen finds the restrictions that are capping what you can produce. Distance gains from mobility work tend to arrive without any extra effort on your part."),
            ("Is it only for injured golfers?", "No. Many golfers screen to prevent injury and to unlock the movement their swing needs. If you are currently in pain we will tell you honestly whether you need a physiotherapist before you need a golf coach."),
            ("Do I need lessons as well?", "They work best together. The screen shapes what your coach can reasonably ask your body to do, which is why we recommend screening before starting a block of <a href=\"1-1-lessons.html\">golf lessons</a> if you have a physical issue you already know about."),
        ],
        "visit_kick": "Golf fitness near Derby &amp; Nottingham",
        "visitH2": "Golf fitness near <em>Derby &amp; Nottingham</em>",
        "boxH2": "Ready to find out <em>what is holding you back?</em>",
        "boxP": "Book a TPI movement screening and find out in 45 minutes why your body will not make the move your swing needs, and what to do about it.",
        "boxBtn1": {"label": "Book a screening", "href": BOOK},
        "boxBtn2": ASK,
        "boxNote": "TPI certified · Around 45 minutes · Codnor, Ripley DE5 9RJ",
    },

    # ================================================== GRASS DRIVING RANGE
    {
        "template": "facility",
        "file": "grass-range.html",
        "cur": "grass-range.html",
        "name": "Grass Driving Range",
        "title": "Grass Driving Range Derby &amp; Nottingham | Practise Off Real Turf | Evolution Golf Academy",
        "desc": "Grass driving range near Derby and Nottingham. Practise off real turf with true lies and real divots, alongside the covered Trackman bays. Walk in, no booking, in Ripley, Derbyshire.",
        "reviews": ["ciaran", "steve", "lisa"],
        "hero": {
            "kick": "Grass Driving Range in Derby &amp; Nottingham",
            "l1": "Grass", "l2": "Range.",
            "p": "Practise off real turf, exactly as you play. Our grass driving range gives you true strikes, real divots and honest feedback on your ball striking.",
            "img": "student_swing",
            "alt": "Grass driving range near Derby and Nottingham at Evolution Golf Academy",
        },
        "eyebrow1": "● Grass Driving Range in Derby &amp; Nottingham | Evolution Golf Academy",
        "secH2": "Grass driving range near <em>Derby &amp; Nottingham</em>",
        "wisImg": "student_swing",
        "wisCopy": [
            ("p", "Mats forgive a heavy strike. Grass does not. Off turf, a fat shot feels and looks like a fat shot, which is exactly the feedback you need if you want your practice to show up in your scores."),
            ("p", "Our grass range gives you real lies, real divots and the same conditions you face on the course. It is the closest practice gets to playing."),
            ("p", "It sits alongside the covered <a href=\"trackman-range.html\">Trackman range</a> and the <a href=\"short-game.html\">short game area</a>, so you can move between turf work, data work and scoring practice in one visit."),
            ("h3", "Why Does Practising Off Grass Matter?"),
            ("p", "A mat has a hard surface under a thin layer of synthetic fibre. Hit two inches behind the ball and the club skids off that surface into the back of the ball, producing a shot that looks respectable. Do the same on turf and the club digs, the ball goes nowhere, and you get an honest report on your low point control."),
            ("p", "That honesty is the whole point. Golfers who practise exclusively on mats often arrive at the first tee with a swing that has been quietly rewarded for a fault, then wonder why the same swing produces heavy shots on the course. Turf practice removes the disguise, which is uncomfortable for a session or two and extremely valuable after that."),
            ("h3", "How Does It Work Alongside the Trackman Bays?"),
            ("p", "Most golfers who use both treat them as different tools. The covered Trackman bays give you volume, numbers and shelter, which makes them the right place to work through the bag or to practise in February. The grass line gives you the real strike and the real lie, which makes it the right place to check that what you built in the bays actually survives contact with turf."),
            ("p", "A common routine is to warm up and gather numbers in a bay, then move out to the grass for the last twenty balls to confirm the strike is genuine. Finish on the <a href=\"short-game.html\">short game area</a> and you have covered every part of the game in a single visit, without moving your car."),
            ("h3", "When Is the Grass Range Open?"),
            ("p", "The turf line runs through the playing season, broadly spring to autumn, and closes when the ground is too wet or too worn to give a fair lie. Managing it that way is what keeps the surface worth hitting from. When it is closed, the covered bays carry on seven days a week, so a wasted journey is never a risk if you check before you set off."),
            ("p", "Warming up before a round is the other job the grass line does particularly well. Ten minutes off turf before you tee off tells you what your strike is doing that morning far more honestly than the same ten minutes off a mat, and it is the reason a lot of Ormonde Fields members walk past the bays on their way to the first tee."),
        ],
        "chkTitle": "● The grass range is for you if you want to",
        "chk": [
            "Feel a real strike rather than a mat bounce",
            "Practise the lies you actually get on the course",
            "Warm up properly before you play",
            "Work on turf interaction and low point control",
            "Combine range work with short game practice",
            "Practise outdoors in the playing season",
        ],
        "cta2": DIRECTIONS,
        "cta3": {"label": "See the Trackman range", "href": "trackman-range.html"},
        "eyebrow2": "● Grass range in Codnor, Ripley",
        "boxH2c": "What the grass range <em>actually gives you</em>",
        "boxSub": "Honest feedback that a mat can never give you.",
        "fboxes": [
            {"t": "True strike feedback", "b": "Real turf shows exactly where the club met the ground. No mat forgiveness, and no shot flattering a strike that did not deserve it.", "img": "student_swing"},
            {"t": "Course conditions", "b": "Practise the shots you actually face, off the lies you actually get, rather than off a perfect flat surface every single time.", "img": "on_course"},
            {"t": "Short game nearby", "b": "The short game area and putting green are a few steps away, so a full practice session takes one visit and one car park.", "img": "putting"},
            {"t": "Seasonal opening", "b": "Open through the playing season. The covered Trackman range runs all year, so winter practice carries on regardless.", "img": "range_sil"},
        ],
        "closer": "If your range game never turns up on the course, the surface you practise on is usually part of the reason.",
        "cta4": DIRECTIONS,
        "procKick": "● How it works",
        "procH2": "Using the <em>grass range</em>",
        "procSub": "Walk in, pay at the dispenser and practise off turf.",
        "procImg": "ball_tee",
        "steps": [
            {"t": "Arrive at the academy", "b": "The grass range sits beside the covered Trackman bays on Nottingham Road, Codnor, with free parking outside."},
            {"t": "Pay at the dispenser", "b": "Contactless payment, same basket prices as the covered range, from £4.00 for 30 balls."},
            {"t": "Set up on the turf line", "b": "Real lies and real divots. Take a divot, that is the point of being out here rather than in a bay."},
            {"t": "Add short game work", "b": "Finish on the short game area and putting green a few steps away to round out the session."},
        ],
        "cta5": DIRECTIONS,
        "faqKick": "● Top questions from golfers",
        "faqH2": "Grass driving range Derby &amp; Nottingham <em>FAQs</em>",
        "faqs": [
            ("Is the grass range open all year?", "It opens through the playing season, since turf needs time to recover and winter conditions make it unusable. The covered <a href=\"trackman-range.html\">Trackman range</a> is open all year, seven days a week, 7am to 8pm."),
            ("Do I need to book?", "No. Walk in, pay contactless at the ball dispenser and practise. There is no membership and no minimum spend, exactly the same as the covered bays."),
            ("How much are balls?", "Same basket prices as the covered range: £4.00 for 30 balls, £7.50 for 60, £10.00 for 90 and £12.50 for 120. The bigger baskets are better value per ball."),
            ("Can I take divots?", "Yes. That is exactly why turf practice works better than mats, and the turf line is managed and rotated so there is always good ground to hit from."),
            ("Can I have a lesson on the grass?", "Yes. Tell us when booking and your coach can run the lesson off turf, which is often the right call if you are working on strike quality or low point control."),
            ("Where is it?", "Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RJ, roughly 20 minutes from Derby and 25 from Nottingham."),
        ],
        "visit_kick": "Grass driving range near Derby &amp; Nottingham",
        "visitH2": "Grass driving range near <em>Derby &amp; Nottingham</em>",
        "boxH2": "Ready to practise <em>off real turf?</em>",
        "boxP": "Walk in today, pay contactless at the dispenser and take a divot. No booking needed, open seven days a week in Codnor near Ripley.",
        "boxBtn1": DIRECTIONS,
        "boxBtn2": ASK,
        "boxNote": "No booking needed · Open through the playing season · Codnor, Ripley DE5 9RJ",
    },

    # ===================================================== SHORT GAME AREA
    {
        "template": "facility",
        "file": "short-game.html",
        "cur": "short-game.html",
        "name": "Short Game Area",
        "title": "Short Game Practice Area Derby &amp; Nottingham | Chipping, Bunker &amp; Putting | Evolution Golf Academy",
        "desc": "Short game practice area near Derby and Nottingham. Chipping, pitching, a real sand bunker and a true rolling putting green. Walk in, seven days a week, in Ripley, Derbyshire.",
        "reviews": ["steve", "ciaran", "reece"],
        "hero": {
            "kick": "Short Game Practice Area in Derby &amp; Nottingham",
            "l1": "Short Game", "l2": "Area.",
            "p": "Half your shots happen inside 100 yards. Our short game area and putting green let you practise chipping, pitching, bunker play and putting on real surfaces.",
            "img": "putting",
            "alt": "Short game practice area near Derby and Nottingham at Evolution Golf Academy",
        },
        "eyebrow1": "● Short Game Practice Area in Derby &amp; Nottingham | Evolution Golf Academy",
        "secH2": "Short game practice near <em>Derby &amp; Nottingham</em>",
        "wisImg": "putting",
        "wisCopy": [
            ("p", "Around half of the shots in a round happen inside 100 yards, yet most golfers spend almost all of their practice time hitting driver. That is the single easiest thing to fix."),
            ("p", "Our short game area gives you real turf lies around a proper green, a practice bunker with real sand and a true rolling putting green, so you can practise every scoring shot you actually face."),
            ("p", "Add a short game lesson with our <a href=\"meet-team.html\">Advanced PGA Professional</a> and you will know exactly which shots to practise and how."),
            ("h3", "Why Does Short Game Practice Drop Handicaps Fastest?"),
            ("p", "Because the shots are shorter, the margin for improvement is enormous and the physical demands are low. A mid handicapper who gets up and down four times a round instead of once has saved three shots without changing their swing, gaining a yard of distance or spending a winter rebuilding anything."),
            ("p", "It is also the part of the game where practice transfers most directly. A forty yard pitch on our practice green is the same shot you will face on the course, off a similar lie, to a similar target. There is very little translation loss, which is not true of hitting fifty drivers off a flat mat."),
            ("h3", "What Can I Practise Here?"),
            ("p", "Chipping and pitching from real turf lies around the green, bunker play from a practice bunker with real sand, and putting on a true rolling surface where pace and read behave the way they will on the course. Between them, that covers every shot you hit inside 100 yards apart from the full wedge, and the <a href=\"trackman-range.html\">Trackman range</a> next door covers that one."),
            ("p", "Bunker practice deserves a particular mention, because it is the shot most club golfers avoid practising and consequently the one that costs them most. A practice bunker with real sand means you can hit fifty splash shots in an afternoon and turn your worst shot into an ordinary one. A <a href=\"1-1-lessons.html\">short game lesson</a> is usually the quickest way to make that happen."),
            ("h3", "How Should I Structure a Short Game Session?"),
            ("p", "Aimlessly dropping a dozen balls in one spot and chipping them at the same flag is the most common mistake, because it rehearses a shot you will never face twice in a round. Play each ball from a different lie and to a different target instead, exactly as the course will present them, and score yourself out of ten on getting up and down."),
            ("p", "Finish with putting, and spend most of that time on pace from long range rather than on three footers. Three putts cost far more shots across a season than missed short putts do, and pace is the skill that transfers between greens. Half an hour structured that way is worth more than two hours of unfocused chipping, and it is the routine our <a href=\"monthly-programme.html\">monthly programme</a> members are given to work through between lessons."),
        ],
        "chkTitle": "● The short game area is for you if",
        "chk": [
            "You lose shots around the green, not off the tee",
            "Bunkers make you nervous",
            "Your putting pace changes green to green",
            "You want to cut your handicap the fastest way",
            "You need a shot you can trust from 40 yards",
            "You want to practise scoring, not just striking",
        ],
        "cta2": DIRECTIONS,
        "cta3": BOOK_LESSON,
        "eyebrow2": "● Short game area in Codnor, Ripley",
        "boxH2c": "What the short game area <em>actually gives you</em>",
        "boxSub": "Every scoring shot, on the surfaces you actually play from.",
        "fboxes": [
            {"t": "Chipping &amp; pitching", "b": "Real turf lies around a proper green. Practise every trajectory and landing spot rather than one stock shot from a flat mat.", "img": "putting"},
            {"t": "Bunker play", "b": "A practice bunker with real sand. Turn your worst shot into a strength, which is worth more strokes than anything you can do with a driver.", "img": "bunker"},
            {"t": "Putting green", "b": "A true rolling green for pace, lines and pressure putt practice, so the speed you learn here is the speed you get out on the course.", "img": "putting"},
            {"t": "Short game lessons", "b": "Add a lesson and learn exactly which shots to practise, and how, instead of chipping aimlessly for an hour and hoping.", "img": "lesson_grip"},
        ],
        "closer": "Nothing drops a handicap faster than getting up and down more often. This is where that happens.",
        "cta4": BOOK_LESSON,
        "procKick": "● How it works",
        "procH2": "Using the <em>short game area</em>",
        "procSub": "Bring your wedges and putter. We will do the rest.",
        "procImg": "bunker",
        "steps": [
            {"t": "Arrive at the academy", "b": "The short game area sits beside the range on Nottingham Road, Codnor, with free parking directly outside."},
            {"t": "Bring wedges and putter", "b": "Balls are provided on the green. Just bring your scoring clubs and something to aim at."},
            {"t": "Practise every shot", "b": "Chipping, pitching, bunker play and putting on real surfaces, in whatever order suits what you are working on."},
            {"t": "Add a lesson", "b": "A short game lesson turns aimless chipping into targeted practice with a clear order of priorities."},
        ],
        "cta5": BOOK_LESSON,
        "faqKick": "● Top questions from golfers",
        "faqH2": "Short game practice Derby &amp; Nottingham <em>FAQs</em>",
        "faqs": [
            ("Do I need to book the short game area?", "No. It is walk in, seven days a week alongside the rest of the academy, from 7am to 8pm. There is no booking, no membership and no minimum spend."),
            ("Are balls provided?", "Yes, balls are provided on the green. Bring your own wedges and putter, since practising with your own scoring clubs is the entire point of the exercise."),
            ("Is there a bunker?", "Yes, a practice bunker with real sand so you can work on greenside shots properly. It is the facility most golfers say they need and least often have access to."),
            ("Can I have a short game lesson?", "Yes. Book with our Advanced PGA Professional and we will build the session around your scoring shots, then give you a practice plan that targets the ones costing you most."),
            ("Is it suitable for beginners?", "Very. Short game is often the quickest confidence win for a new golfer, because a decent chip is achievable in a single session in a way that a decent drive usually is not."),
            ("Where is it?", "Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RJ, between Derby and Nottingham and minutes from Ripley, Heanor and Ilkeston."),
        ],
        "visit_kick": "Short game practice near Derby &amp; Nottingham",
        "visitH2": "Short game practice near <em>Derby &amp; Nottingham</em>",
        "boxH2": "Ready to get <em>up and down more often?</em>",
        "boxP": "Bring your wedges and putter down today, or book a short game lesson and find out exactly which shots are costing you strokes.",
        "boxBtn1": DIRECTIONS,
        "boxBtn2": BOOK_LESSON,
        "boxNote": "No booking needed · Balls provided on the green · Codnor, Ripley DE5 9RJ",
    },
]
