"""Facility pages - simulator, teaching bay, golf fitness, grass range, short game."""

PAGES = [

    # ================================================== TRACKMAN SIMULATOR
    {
        "file": "trackman-simulator.html",
        "cur": "trackman-simulator.html",
        "title": "Golf Simulator Derby &amp; Nottingham | Trackman Indoor Bays | Evolution Golf Academy",
        "desc": "Trackman golf simulator near Derby and Nottingham. Play world famous courses indoors, practise all winter and see real ball data. £25 per hour, open 7am to 8pm daily in Ripley.",
        "visit_kick": "Golf simulator near Derby &amp; Nottingham",
        "cta": ("Play golf <em>indoors, all year.</em>",
                "Trackman simulator bays at Ormonde Fields, Ripley. £25 per hour, seven days a week, fifteen minutes from Derby and twenty from Nottingham."),
        "hero": {
            "kick": "Golf Simulator Derby &amp; Nottingham",
            "l1": "Trackman", "l2": "Simulator.",
            "p": "Our <strong>golf simulator near Derby and Nottingham</strong> runs on Trackman, so the shot on the screen is the shot you actually hit. Play world famous courses indoors, practise through the winter and see real ball data on every swing. Booking required, £25 per hour.",
            "img": "sim",
            "alt": "Trackman golf simulator near Derby and Nottingham at Evolution Golf Academy",
        },
        "marq": ["Golf Simulator Derby", "Indoor Golf Nottingham", "Trackman Ball Data",
                 "Play Famous Courses", "Winter Golf Practice", "Ripley, Derbyshire"],
        "sections": [

            {"type": "prose", "kick": "Indoor golf near Derby &amp; Nottingham",
             "h2": "What Is a Trackman <em>Golf Simulator?</em>",
             "blocks": [
                 ("p", "A <strong>golf simulator</strong> is an indoor bay where a launch monitor measures what the club and ball actually do, then puts the resulting shot onto a screen in front of you. Ours run on Trackman, the same dual-radar system used on the PGA Tour, which means the ball you hit into the screen behaves on the software the way it would have behaved outdoors on a still day in Derbyshire."),
                 ("p", "For golfers in Derby and Nottingham that solves a very British problem. There are roughly four months of the year when eighteen holes is a test of character rather than a test of golf. An indoor bay gives you somewhere warm, dry and floodlit to keep hitting shots, and unlike a mat in a garage it tells you exactly what those shots did."),
                 ("h3", "How Does a Golf Simulator Actually Work?"),
                 ("p", "You hit a real golf ball with your own clubs into a screen a few yards away. Trackman's radar tracks the club through impact and the ball through the first part of its flight, then models the rest from the measured launch conditions: ball speed, launch angle, spin rate, spin axis and attack angle. Because it measures rather than guesses, a thin three iron looks like a thin three iron on screen, and a well struck one runs out the way it should."),
                 ("h3", "Is It the Same Technology as the Driving Range Bays?"),
                 ("p", "It is the same launch monitor and the same measurements you see in the <a href=\"trackman-range.html\">Trackman driving range bays</a>, doing a different job. The range is about volume and immediate feedback. The simulator wraps that data in a golf course, a target and a score, which changes how you behave. Golfers concentrate differently when there is water short of the green, even an imaginary one."),
                 ("p", "If you want the numbers explained rather than simply displayed, that is a coaching conversation, and it happens next door in the <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a> with a PGA Professional."),
             ]},

            {"type": "cards", "kick": "Inside the simulator bay",
             "h2": "What Can You Do on the <em>Golf Simulator?</em>",
             "p": "One bay, several jobs. Most golfers arrive wanting to play a famous course and leave having spent half the session on practice modes.",
             "cards": [
                 {"img": "sim", "alt": "Playing a famous golf course indoors on the Trackman simulator in Derbyshire",
                  "h": "Play Famous Courses Indoors",
                  "p": "Work your way round some of the best known courses in world golf without leaving Codnor. Full eighteen holes, or nine if the evening is getting on. Handicaps can be applied so a mixed group still gets a fair game."},
                 {"img": "bay_screen", "alt": "Trackman simulator practice modes and skills tests on screen",
                  "h": "Structured Practice Modes",
                  "p": "Target practice, closest to the pin, long drive contests and skills tests that give you a score at the end. A number to beat next time is far more useful than a vague sense the session went well."},
                 {"img": "launch_data", "alt": "Winter golf practice with Trackman launch data indoors near Derby",
                  "h": "Winter Golf and Bad Weather",
                  "p": "Rain, frost, wind and dark evenings stop outdoor golf for months at a time. Indoors, a January session looks exactly like a June one, which is how golfers arrive in spring already swinging well."},
                 {"img": "bay_indoor", "alt": "Group golf simulator session at Evolution Golf Academy Ripley",
                  "h": "Groups, Friends and Occasions",
                  "p": "Bays take a small group comfortably. Societies, birthdays, work nights out and fourballs who have been rained off all use them. Bring your own clubs or borrow a set from us."},
             ]},

            {"type": "split", "img": "bay_screen",
             "img_alt": "Trackman golf simulator screen and ball data at Evolution Golf Academy",
             "kick": "Accuracy and honesty",
             "h2": "How Accurate Is a <em>Golf Simulator?</em>",
             "paras": [
                 "Accuracy depends almost entirely on what is doing the measuring. Camera-only systems infer a great deal from very little. Trackman's dual radar measures club delivery and ball launch directly, then applies a flight model that has been checked against real shots for years. In practice, carry distances on our <strong>golf simulator in Derby and Nottingham</strong> sit within a couple of yards of what the same swing produces outdoors.",
                 "The honest caveat is that a simulator cannot give you wind, a downhill lie, or the particular horror of a four footer to win the match. It measures the shot accurately. It does not replace the golf course. As practice and as winter mileage it is excellent, and most golfers get more out of an hour indoors than out of a summer of unstructured range sessions.",
             ],
             "ticks": [
                 "<b>Dual radar, not cameras</b> - the system measures club and ball rather than estimating them",
                 "<b>Carry distances you can trust</b> - build a yardage chart and take it to <a href=\"1-1-lessons.html\">your next golf lesson</a>",
                 "<b>Every shot recorded</b> - strike, dispersion, spin and ball flight, shot after shot",
                 "<b>Your own clubs</b> - nothing is simulated about the equipment in your hands",
                 "<b>Fifteen minutes from Derby</b>, twenty from Nottingham on the A610, free parking on site",
             ],
             "btn2": ("See the teaching bay", "trackman-teaching-bay.html"), "alt": True},

            {"type": "steps", "kick": "Booking a bay",
             "h2": "How Do I Book a <em>Golf Simulator Session?</em>",
             "p": "Unlike the outdoor range, the simulator is booked in advance. Bays get busy from October onwards, so a few days of notice through the winter is sensible.",
             "steps": [
                 ("Choose your slot",
                  "The academy is open 7am to 8pm, seven days a week, and the simulator runs the whole time. Early mornings and mid-afternoons are quietest. Evenings from six are the busiest, particularly between November and February."),
                 ("Book online or by phone",
                  "Book through the online system or call 07710 582036. If there are more than four of you, ring rather than book online so we can put you in the right bay and give you enough time."),
                 ("Decide what you want from the hour",
                  "Playing a course and practising a skill are two different sessions. Deciding beforehand stops the hour quietly disappearing into nine holes that nobody scored."),
                 ("Arrive ten minutes early",
                  "Parking is free on site at Ormonde Fields Golf Club, Nottingham Road, Codnor. Ten minutes gives you time to change shoes, warm up and get the bay set up without eating into your booking."),
                 ("Add coaching if the data raises questions",
                  "Golfers regularly book a simulator hour, see something in the numbers they cannot explain, and follow it with <a href=\"1-1-lessons.html\">a one to one golf lesson</a>. That is the sequence we would recommend, in that order."),
             ]},

            {"type": "prose", "kick": "Who uses the bays",
             "h2": "Who Is the <em>Golf Simulator For?</em>",
             "blocks": [
                 ("h3", "Club Golfers Who Refuse to Stop in Winter"),
                 ("p", "By some distance the largest group. Golfers carrying a handicap who know from experience that three months off costs them the first half of the following season. An hour a week indoors keeps sequencing, strike and clubhead speed roughly where they were in September, and the difference shows in April."),
                 ("h3", "Beginners Who Would Rather Not Be Watched"),
                 ("p", "A simulator bay is enclosed and quiet, which suits anyone still nervous about topping one in front of strangers. It works well alongside <a href=\"beginner-coaching.html\">beginner golf coaching</a>, and if you have genuinely never held a club, <a href=\"get-into-golf.html\">Get Into Golf</a> is a gentler first step than booking a bay on your own."),
                 ("h3", "Groups, Societies and Anyone Organising Something"),
                 ("p", "Nine holes on a famous course, four players, a scorecard and no possibility of rain makes a straightforward evening out. Groups from Derby, Nottingham, Ripley and across Derbyshire use the bays for society nights, birthdays and the annual attempt to settle an argument about who is actually the longest hitter."),
                 ("h3", "Juniors and Families"),
                 ("p", "Short attention spans and long waits do not mix. On the simulator a junior gets a shot every thirty seconds and a score to chase, which holds interest far longer than a basket of balls hit into a field. Coaches on our <a href=\"junior-academy.html\">Junior Academy</a> use the bays for exactly that reason, and the <a href=\"ladies-academy.html\">Ladies Academy</a> runs indoor sessions once the light goes in October."),
             ], "alt": True},

            {"type": "stats", "items": [("£25", "Per Simulator Hour"), ("2+", "Simulator Bays"), ("7am-8pm", "Open Every Day")]},

            {"type": "prose", "kick": "Simulator prices",
             "h2": "How Much Does a Golf Simulator Session <em>Cost?</em>",
             "blocks": [
                 ("p", "The simulator is £25 per hour for the bay rather than per person, so four players splitting an hour pay a little over six pounds each. A private practice bay without the course software is £15 per hour, and if all you want is to hit balls, range baskets start from £4."),
                 ("h3", "How Long Should I Book For?"),
                 ("p", "An hour covers nine holes for two players, or a focused solo practice session. Four players wanting eighteen holes should budget two hours and probably a little more, because golf on a screen still involves people telling stories between shots. If in doubt, book the longer slot."),
                 ("h3", "Is Coaching Included in the Price?"),
                 ("p", "No, coaching is booked separately. A <a href=\"1-1-lessons.html\">one to one lesson</a> with a PGA Professional is £55 an hour, and the <a href=\"monthly-programme.html\">monthly coaching programme</a> is £60 a month if you would rather have continuous support than occasional lessons. Prices can change, so confirm on 07710 582036 before you travel."),
             ]},

            {"type": "rel", "kick": "Explore the academy",
             "h2": "What Else Is at Our <em>Golf Academy?</em>",
             "p": "The simulator is one part of the site. Everything below is on the same premises at Ormonde Fields in Codnor, Ripley.",
             "links": [
                 ("trackman-range.html", "Trackman Driving Range",
                  "Seven covered, floodlit bays with ball speed, carry, spin and shot shape on every shot. Walk in, no booking.", "Trackman range"),
                 ("trackman-teaching-bay.html", "Trackman Teaching Bay",
                  "A private, distraction free bay with Trackman, video analysis and training aids, used for one to one coaching.", "Teaching bay"),
                 ("grass-range.html", "Grass Driving Range",
                  "Real turf, real divots and honest feedback on your strike, through the drier months of the year.", "Grass range"),
                 ("short-game.html", "Short Game Area",
                  "Chipping, pitching, bunker play and putting, where most amateur golfers save the quickest strokes.", "Short game"),
                 ("golf-fitness.html", "Golf Fitness Suite",
                  "TPI-informed mobility, strength and speed work built around what the golf swing actually demands.", "Golf fitness"),
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes with a PGA Professional using the same Trackman data you see in the simulator bay.", "Golf lessons"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Golf Simulator Derby &amp; Nottingham - <em>FAQs.</em>",
             "qs": [
                 ("Do I need to book the golf simulator?",
                  "Yes. The simulator bays are booked in advance, unlike the walk-in <a href=\"trackman-range.html\">Trackman driving range</a>. Book online or call 07710 582036. From October through to March, evening slots go early in the week, so give yourself a few days of notice rather than turning up and hoping."),
                 ("How much does the golf simulator cost per hour?",
                  "It is £25 per hour for the bay, not per golfer, so the cost per head falls sharply with a group. A private practice bay without the course software is £15 per hour. Range baskets start from £4. Prices are reviewed from time to time, so confirm on 07710 582036 before travelling."),
                 ("How many people can use one simulator bay?",
                  "A bay is comfortable for up to four golfers playing together, and an hour suits two players over nine holes. Larger groups and societies are welcome, but ring rather than booking online so we can allocate enough bays and enough time for everyone to get a proper go."),
                 ("Do I need my own golf clubs?",
                  "No. Clubs are available if you do not have your own, which makes an indoor bay a reasonable way to try golf for the first time without buying anything. Trainers are fine indoors. If you are starting from scratch, <a href=\"get-into-golf.html\">Get Into Golf</a> is a better introduction than a solo hour."),
                 ("How accurate is the Trackman simulator compared with real golf?",
                  "Trackman measures club and ball with dual radar rather than inferring flight from cameras, so carry distances typically land within a couple of yards of the same swing hit outdoors. What it cannot reproduce is wind, sloping lies and nerves, so treat it as excellent practice rather than a replacement for the course."),
                 ("Can I have a golf lesson on the simulator?",
                  "Coaching normally runs in the private <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a>, which is set up with video, mirrors and training aids. Simulator bays are used for coaching where course management, club selection or on-course strategy is the point of the session, which suits more experienced golfers."),
                 ("Is the simulator good for beginners?",
                  "It is, largely because nobody is watching. The bay is enclosed, the feedback is immediate and there is no queue behind you. Most beginners get more from it once they have had a few <a href=\"beginner-coaching.html\">beginner golf lessons</a>, so the swing they are repeating is one worth repeating."),
                 ("Where is the golf simulator and is there parking?",
                  "We are at Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL, roughly 15 minutes from Derby and 20 from Nottingham on the A610. Parking is free on site. See <a href=\"golf-lessons-derby.html\">golf lessons in Derby</a> or <a href=\"golf-lessons-nottingham.html\">golf lessons in Nottingham</a> for directions."),
                 ("Can juniors use the golf simulator?",
                  "Yes, and it suits them well. The pace is quick, the scoring is visible and the weather is irrelevant. Juniors should be supervised by an adult in the bay. Structured coaching for younger golfers runs through the <a href=\"junior-academy.html\">Junior Academy</a> rather than as open bay time."),
             ], "alt": True},
        ],
    },

    # ================================================ TRACKMAN TEACHING BAY
    {
        "file": "trackman-teaching-bay.html",
        "cur": "trackman-teaching-bay.html",
        "title": "Trackman Teaching Bay Golf Lessons Derby | Private Coaching Bay | Evolution Golf Academy",
        "desc": "Private Trackman teaching bay for golf lessons near Derby and Nottingham. Tour-level data, video analysis you keep, training aids and mirrors, with a PGA Professional. £55 per hour.",
        "visit_kick": "Trackman golf lessons near Derby &amp; Nottingham",
        "cta": ("Book a lesson in the <em>teaching bay.</em>",
                "One hour, one PGA Professional, full Trackman data and video you take home. £55 per hour at Ormonde Fields, Ripley."),
        "hero": {
            "kick": "Trackman Teaching Bay Golf Lessons Derby &amp; Nottingham",
            "l1": "Teaching", "l2": "Bay.",
            "p": "The <strong>Trackman teaching bay</strong> is where golf lessons near Derby and Nottingham actually happen: a private, quiet room with tour-level ball data, video analysis, mirrors and a PGA Professional watching every shot you hit. Booked by the hour, seven days a week.",
            "img": "over_shoulder",
            "alt": "PGA coach and golfer in the Trackman teaching bay near Derby and Nottingham",
        },
        "marq": ["Trackman Teaching Bay", "Golf Lessons Derby", "PGA Professional Coaching",
                 "Video Swing Analysis", "Private Indoor Bay", "Nottingham &amp; Derbyshire"],
        "sections": [

            {"type": "prose", "kick": "Private coaching bay in Derbyshire",
             "h2": "What Is a <em>Trackman Teaching Bay?</em>",
             "blocks": [
                 ("p", "A great lesson starts with feeling comfortable. That is why our private <strong>Trackman Teaching Bay</strong> provides a quiet, distraction free environment where you can relax, focus on your game and enjoy a premium coaching experience. Equipped with industry leading Trackman technology, training aids, mirrors and professional coaching equipment, every lesson is designed to give you the feedback, understanding and support needed to make lasting improvements."),
                 ("p", "In plain terms, it is a room rather than a bay on a busy range. Nobody is hitting a driver two feet to your left, nobody is waiting for the ball dispenser behind you, and nothing you are told gets lost in the noise. For golfers travelling in from Derby, Nottingham and across Derbyshire, that hour is the part of the week where the work actually gets done."),
                 ("h3", "Why Does a Private Bay Make a Difference to a Lesson?"),
                 ("p", "Learning a movement requires attention, and attention is the first thing an open range takes away. Golfers self-consciously hitting shots in front of an audience swing faster, rush between balls and stop asking questions. Put the same golfer in a quiet bay with a screen, a mirror and a coach and the questions start coming, which is when a <a href=\"1-1-lessons.html\">one to one golf lesson</a> begins to earn its money."),
                 ("h3", "What Technology Is in the Bay?"),
                 ("p", "Trackman dual radar for ball and club data, high speed video from two angles, full length mirrors for real-time feedback on posture and plane, and the training aids a PGA Professional reaches for when a picture is worth more than an explanation. The same Trackman numbers you see on the <a href=\"trackman-range.html\">Trackman driving range</a> are here, with someone qualified sitting next to them."),
                 ("p", "The bay is used for every kind of coaching we run, from <a href=\"beginner-coaching.html\">beginner golf lessons</a> through to low handicap players chasing dispersion, and for the indoor sessions on the <a href=\"monthly-programme.html\">monthly coaching programme</a>."),
             ]},

            {"type": "cards", "kick": "What is in the bay",
             "h2": "What Do You Get in a <em>Trackman Teaching Bay Lesson?</em>",
             "p": "Four things, in every session, whether you are two months into golf or two shots off scratch.",
             "cards": [
                 {"img": "launch_data", "alt": "Trackman data numbers displayed during a golf lesson near Derby",
                  "h": "Trackman Data",
                  "p": "Club path, face angle, attack angle, strike location, launch, spin and carry, measured on every shot. Your coach uses it to explain exactly why the ball did what it did, rather than guessing from the naked eye."},
                 {"img": "coach_feedback", "alt": "Trackman video swing analysis with a PGA coach in Derbyshire",
                  "h": "Trackman Video Analysis",
                  "p": "Your swing filmed, drawn on and played back in the lesson, then sent to you afterwards so you have it on your phone. Feel and real are rarely the same thing, and video settles the argument in about four seconds."},
                 {"img": "trackman_screen", "alt": "Trackman performance and test centre assessment in the teaching bay",
                  "h": "Performance and Test Centre",
                  "p": "Structured tests that challenge specific areas of your game and expose where you are actually losing shots. Most golfers are surprised. The wedges are usually worse than the driver, whatever the scorecard suggested."},
                 {"img": "bay_screen", "alt": "Trackman interactive games used during a golf lesson in Ripley",
                  "h": "Gamify Your Lesson",
                  "p": "Trackman's interactive games turn a drill into a competition with a score attached. Pressure is a skill, and adding a little of it in the bay is the simplest way to make practice look more like golf."},
             ]},

            {"type": "split", "img": "lesson_grip",
             "img_alt": "PGA Professional adjusting a golfer's grip in the teaching bay near Derby",
             "kick": "Why golfers book the bay",
             "h2": "Why Take a Golf Lesson in a <em>Private Bay?</em>",
             "paras": [
                 "The measurable reason is feedback. A <strong>Trackman teaching bay golf lesson in Derby</strong> gives your coach numbers for every shot and video for the ones that matter, so a change is either working or it is not, and you both find out inside three swings rather than three weeks.",
                 "The less measurable reason is that people learn better when they are not being watched. Golf is an unusually public sport to be bad at. A quiet room removes the audience, and the hour turns into a conversation about your game rather than a performance for the bay next door.",
             ],
             "ticks": [
                 "<b>Quiet and private</b> - no queue, no audience, no shouting over a driver",
                 "<b>Numbers and video together</b> - what happened, and what it looked like",
                 "<b>Video sent to you</b> - the lesson does not evaporate on the drive home",
                 "<b>Every level welcome</b> - from <a href=\"get-into-golf.html\">Get Into Golf</a> beginners to single figure handicaps",
                 "<b>Physical screening available</b> - add a <a href=\"tpi-screening.html\">TPI screening</a> if your body is the limiting factor",
             ],
             "btn2": ("See 1:1 lessons", "1-1-lessons.html"), "alt": True},

            {"type": "steps", "kick": "How a lesson runs",
             "h2": "How Does a <em>Trackman Golf Lesson Work?</em>",
             "p": "An hour, structured. Nothing about it requires you to know anything about launch monitors beforehand.",
             "steps": [
                 ("We talk before you swing",
                  "Five minutes on what you play off, what you want, what has been going wrong and what you have already tried. Coaching somebody without that context is guesswork with good equipment."),
                 ("You hit shots and we gather data",
                  "Warm up, then hit a set of shots while Trackman records everything and the cameras run. No instruction yet. We need to see your golf swing, not your golf swing plus a suggestion."),
                 ("We look at it together",
                  "Data and video on the screen, side by side, with the one or two things actually costing you shots identified in plain English. Long lists of faults are how golfers leave lessons worse than they arrived."),
                 ("We change one thing and test it",
                  "A drill, a feel or a training aid, then shots to prove it. Trackman tells us immediately whether the change did what it was supposed to do, so nothing leaves the bay untested."),
                 ("You leave with a plan and the video",
                  "What to practise, how to practise it and how you will know it is working. The swing videos are sent to you afterwards. Follow-up work happens on the <a href=\"trackman-range.html\">Trackman range</a> or in the <a href=\"short-game.html\">short game area</a>."),
             ]},

            {"type": "prose", "kick": "Who books the teaching bay",
             "h2": "Who Are Teaching Bay Lessons <em>For?</em>",
             "blocks": [
                 ("h3", "Golfers Who Have Plateaued"),
                 ("p", "The most common visitor. Someone who got to fifteen or eighteen, stuck there, and has spent two summers hitting balls without moving. Almost always there is a measurable cause hiding in the data, usually strike location or a club path they had no way of seeing on their own."),
                 ("h3", "Complete Beginners"),
                 ("p", "Starting in a quiet bay rather than on a busy range is easier on the nerves and quicker on the learning. New golfers pair the bay with <a href=\"beginner-coaching.html\">beginner coaching</a>, and the <a href=\"ladies-academy.html\">Ladies Academy</a> and <a href=\"junior-academy.html\">Junior Academy</a> both use it for indoor work through the winter."),
                 ("h3", "Better Players Chasing Small Margins"),
                 ("p", "For single figure golfers the gains are in dispersion, spin control and gapping rather than anything dramatic. That work needs measurement, because the differences are too small to see. Half a degree of face angle is invisible to the eye and worth several yards left of the flag."),
                 ("h3", "Anyone Whose Body Is the Problem"),
                 ("p", "A fair number of swing faults are physical rather than technical. If you cannot rotate, you will find another way to move the club, and no amount of instruction fixes that. In those cases the honest answer is a <a href=\"tpi-screening.html\">TPI screening</a> and some <a href=\"golf-fitness.html\">golf fitness work</a> alongside the lessons."),
             ], "alt": True},

            {"type": "stats", "items": [("£55", "Per Hour Lesson"), ("3", "PGA Professionals"), ("7", "Days a Week")]},

            {"type": "rel", "kick": "Explore the academy",
             "h2": "What Else Is at Our <em>Golf Academy?</em>",
             "p": "Everything below sits on the same site at Ormonde Fields Golf Club in Codnor, Ripley, fifteen minutes from Derby.",
             "links": [
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes with a PGA Professional in the teaching bay, £55, with video sent to you afterwards.", "Golf lessons"),
                 ("monthly-programme.html", "Monthly Programme",
                  "Continuous coaching at £60 a month for golfers who want a plan rather than the occasional lesson.", "Monthly coaching"),
                 ("trackman-range.html", "Trackman Driving Range",
                  "Seven covered, floodlit bays with full ball data, for practising the work between lessons.", "Trackman range"),
                 ("trackman-simulator.html", "Trackman Simulator",
                  "Play famous courses indoors or use the bay for winter practice when the weather closes in.", "Golf simulator"),
                 ("tpi-screening.html", "TPI Screening",
                  "A physical assessment that shows whether your body is capable of the swing you are trying to make.", "TPI screening"),
                 ("meet-team.html", "Meet the Team",
                  "Will Painter, Hayden Berridge and Scott Hassall, the PGA Professionals who take the lessons.", "Meet the coaches"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Trackman Teaching Bay Lessons - <em>FAQs.</em>",
             "qs": [
                 ("How much does a lesson in the Trackman teaching bay cost?",
                  "A one hour <a href=\"1-1-lessons.html\">1:1 golf lesson</a> with a PGA Professional is £55, including full Trackman data and the video sent to you afterwards. If you want ongoing coaching rather than one-off lessons, the <a href=\"monthly-programme.html\">monthly programme</a> is £60 a month. Call 07710 582036 to confirm current prices."),
                 ("Do I get the swing videos to keep?",
                  "Yes. The swing videos recorded in your lesson are sent to you afterwards, so you can watch them at home and check your practice against what the coach was actually asking for. Golfers forget roughly half of a lesson by the following morning, and video is the cheapest possible insurance against that."),
                 ("Do I need to be any good to book the teaching bay?",
                  "No. Beginners are the second largest group who use it, precisely because it is private. There is no audience and no queue. If you have never held a golf club, <a href=\"get-into-golf.html\">Get Into Golf</a> or <a href=\"beginner-coaching.html\">beginner coaching</a> is the right starting point, and both use this bay."),
                 ("What is the Performance and Test Centre?",
                  "A set of Trackman tests that challenge specific areas of your game under measurement, from wedge distance control to driving accuracy. It scores you and shows where the shots are genuinely going missing. Most golfers discover the problem is not the part of the game they had been practising."),
                 ("Do I need my own golf clubs for a lesson?",
                  "Clubs are available if you do not have your own, so nobody needs to buy equipment before finding out whether they enjoy the game. If your clubs turn out to be the problem rather than your swing, your coach will say so, and a custom fitting is the next conversation."),
                 ("How often should I have a golf lesson?",
                  "For most club golfers, one lesson every three to four weeks with structured practice in between works better than a burst of weekly lessons followed by nothing. Practice is where the change happens, and the <a href=\"trackman-range.html\">Trackman range</a> gives you the same data to check yourself against."),
                 ("Can two of us share a lesson in the bay?",
                  "Yes, shared lessons work well for couples, friends and parent and child pairs, and they cost less per person. The trade-off is half the hitting time each, so they suit golfers working on similar things. Call 07710 582036 to arrange one rather than booking two separate slots."),
                 ("Is the teaching bay indoors and open all year?",
                  "It is fully indoors and heated, and it runs 7am to 8pm every day of the year, weather permitting nothing at all. Winter is the busiest period for exactly that reason. Outdoor work moves to the <a href=\"grass-range.html\">grass driving range</a> in the drier months when a coach wants real turf."),
                 ("Which coach will I have?",
                  "Will Painter, Hayden Berridge or Scott Hassall, all PGA Professionals. Scott heads up junior coaching and Hayden is also our custom fitter. You can request a coach when booking. Read about all three on <a href=\"meet-team.html\">Meet the Team</a>."),
             ], "alt": True},
        ],
    },

    # ======================================================== GOLF FITNESS
    {
        "file": "golf-fitness.html",
        "cur": "golf-fitness.html",
        "title": "Golf Fitness Derby &amp; Nottingham | TPI Mobility, Strength &amp; Speed | Evolution Golf Academy",
        "desc": "Golf fitness near Derby and Nottingham. TPI-informed mobility, strength, speed and injury prevention for golfers, built on a physical screening. Ripley, Derbyshire, open 7 days.",
        "visit_kick": "Golf fitness near Derby &amp; Nottingham",
        "cta": ("Train the body that <em>swings the club.</em>",
                "Start with a TPI screening at £75, then a plan built around what your body can actually do. Ormonde Fields, Ripley, seven days a week."),
        "hero": {
            "kick": "Golf Fitness Derby &amp; Nottingham",
            "l1": "Golf", "l2": "Fitness.",
            "p": "<strong>Golf fitness in Derby and Nottingham</strong>, built on a TPI physical screening rather than a generic gym plan. Mobility, stability, strength and clubhead speed, aimed squarely at the swing faults that no amount of coaching will fix on its own.",
            "img": "team",
            "alt": "Golf fitness coaching at Evolution Golf Academy near Derby and Nottingham",
        },
        "marq": ["Golf Fitness Derby", "TPI Certified", "Mobility &amp; Stability",
                 "Clubhead Speed Training", "Injury Prevention", "Nottingham &amp; Derbyshire"],
        "sections": [

            {"type": "prose", "kick": "Golf specific training in Derbyshire",
             "h2": "What Is <em>Golf Fitness?</em>",
             "blocks": [
                 ("p", "<strong>Golf fitness</strong> is physical training built around the demands of the golf swing rather than around general health. The swing asks the body to separate the upper and lower halves, rotate quickly, stabilise through impact and repeat that seventy or eighty times in four hours while walking six miles. Training for it looks very little like training for anything else, which is why generic gym programmes rarely move a handicap."),
                 ("p", "Our approach starts with assessment, not exercise. Before anyone is given a single drill, we look at how your body actually moves, because the exercises that help a golfer who cannot rotate are the opposite of the ones that help a golfer who is too mobile and cannot control it. Golfers from Derby, Nottingham and across Derbyshire come here for that first part more than for the second."),
                 ("h3", "Why Are So Many Swing Faults Physical Rather Than Technical?"),
                 ("p", "Because the body will always find a way to get the club to the ball. If your hips cannot rotate far enough in the backswing, you will slide, or lift, or bend your lead arm, and one of those will show up on video as a fault. A coach can ask you to stop doing it. Your body will simply pick a different compensation, because the original restriction is still there."),
                 ("p", "The classic examples are familiar to anyone who has had <a href=\"1-1-lessons.html\">golf lessons</a> and not managed to make them stick. Early extension, where the hips move towards the ball through impact, is very often limited hip internal rotation or weak glutes. Loss of posture is frequently thoracic spine mobility. A reverse spine angle can be a hip flexor problem. Instruction alone does not touch any of those."),
                 ("h3", "What Does TPI Mean?"),
                 ("p", "The Titleist Performance Institute is the industry standard for assessing how a golfer's body relates to their golf swing. Our coaches are TPI certified, which means they run a structured physical screen and read the results against known swing characteristics. It is the same framework used on tour, and it is where every fitness plan here begins. Full detail is on the <a href=\"tpi-screening.html\">TPI screening</a> page."),
             ]},

            {"type": "cards", "kick": "The four pillars",
             "h2": "What Does <em>Golf Fitness Cover?</em>",
             "p": "Four areas, weighted differently for every golfer depending on what the screening finds.",
             "cards": [
                 {"img": "tpi", "alt": "TPI mobility assessment for golfers near Derby and Nottingham",
                  "h": "Mobility",
                  "p": "Hips, thoracic spine, shoulders and ankles. Most amateur golfers are restricted in at least two of them, and the swing they end up with is the one their range of motion allows rather than the one they want."},
                 {"img": "team", "alt": "Golf specific strength and stability training in Derbyshire",
                  "h": "Stability and Strength",
                  "p": "Mobility without control is just wobble. Glutes, core and grip strength give you something to rotate against, which is what turns range of motion into a swing that repeats under pressure on the eighteenth."},
                 {"img": "driver_balls", "alt": "Clubhead speed training for golfers at Evolution Golf Academy",
                  "h": "Speed and Power",
                  "p": "Speed is trainable at any age, and it is the single most reliable way to shorten the course. Overspeed work, sequencing drills and measured progress on the <a href=\"trackman-range.html\">Trackman range</a>, so the gains are numbers rather than feelings."},
                 {"img": "student_swing", "alt": "Injury prevention screening for golfers in Ripley Derbyshire",
                  "h": "Injury Prevention",
                  "p": "Golfers hurt lower backs, lead wrists and elbows, usually through repetition rather than accident. Screening finds the imbalances that cause it before they turn into six weeks off in the middle of the season."},
             ]},

            {"type": "split", "img": "tpi",
             "img_alt": "TPI certified golf fitness assessment near Derby and Nottingham",
             "kick": "Distance and durability",
             "h2": "Can Golf Fitness Add <em>Distance?</em>",
             "paras": [
                 "Usually, yes, and often more quickly than technical work does. Clubhead speed comes from how fast you can move and how efficiently you sequence it, both of which respond to training. Golfers who commit to <strong>golf fitness</strong> for eight to twelve weeks frequently add three to six miles an hour of clubhead speed, and every mile an hour is worth roughly two to three yards of carry with a driver.",
                 "The less exciting benefit is durability. A golfer who can still rotate on the sixteenth hits a better tee shot than one who has been quietly falling apart since the turn, and that is worth more over a season than any single swing change. Distance is what people ask for. Playing pain free in ten years is what they thank us for.",
             ],
             "ticks": [
                 "<b>Starts with a screening</b> - a <a href=\"tpi-screening.html\">TPI physical screen</a> before anything is prescribed",
                 "<b>Measured on Trackman</b> - speed gains verified in the <a href=\"trackman-range.html\">range bays</a>, not guessed at",
                 "<b>Works alongside coaching</b> - fitness and <a href=\"1-1-lessons.html\">golf lessons</a> pulling the same direction",
                 "<b>Any age, any handicap</b> - juniors, ladies, seniors and low handicap players all screen differently",
                 "<b>Fifteen minutes from Derby</b>, twenty from Nottingham, free parking on site",
             ],
             "btn2": ("Book a TPI screening", "tpi-screening.html"), "alt": True},

            {"type": "steps", "kick": "Getting started",
             "h2": "How Do I Start <em>Golf Fitness Training?</em>",
             "p": "In order, because doing this the wrong way round is how golfers end up doing exercises they did not need.",
             "steps": [
                 ("Book a TPI screening",
                  "£75 for a structured physical assessment with a TPI certified coach. It takes about an hour and tests mobility, stability, balance and rotation against the movements the golf swing requires. Book it on the <a href=\"tpi-screening.html\">TPI screening</a> page."),
                 ("Match the findings to your golf swing",
                  "The screen on its own is only half the picture. Read against video and Trackman data from the <a href=\"trackman-teaching-bay.html\">teaching bay</a>, it shows which of your faults are physical and which are genuinely technical."),
                 ("Get a plan you will actually do",
                  "Usually three or four exercises, ten to fifteen minutes, three times a week. Long programmes get abandoned by week two. Short ones survive, and a short programme done consistently beats a thorough one done twice."),
                 ("Train, then retest",
                  "Six to eight weeks of work, then the same screen again alongside speed numbers on the <a href=\"trackman-range.html\">Trackman range</a>. Either the restriction has moved or it has not, and both answers are useful."),
                 ("Fold it into your coaching",
                  "Physical work and technical work should be pointed at the same target. Golfers on the <a href=\"monthly-programme.html\">monthly coaching programme</a> get both reviewed together rather than treated as two separate hobbies."),
             ]},

            {"type": "prose", "kick": "Who it suits",
             "h2": "Who Is <em>Golf Fitness For?</em>",
             "blocks": [
                 ("h3", "Golfers Over Fifty Losing Distance"),
                 ("p", "The most common enquiry we get. Distance loss with age is real, but a great deal of it is lost mobility and lost speed rather than anything inevitable. Both respond to training. Golfers in their sixties regularly regain speed they assumed was gone for good, which changes which clubs they are hitting into greens."),
                 ("h3", "Anyone With a Recurring Back or Wrist Problem"),
                 ("p", "If your lower back aches after every round, that is information rather than bad luck. Screening usually finds a limitation somewhere else, commonly the hips or thoracic spine, that the back has been compensating for. Note that we assess movement for golf and are not a medical service, so anything painful should see a clinician first."),
                 ("h3", "Juniors Who Are Growing Quickly"),
                 ("p", "Growth spurts wreck coordination and timing, and young golfers often need physical work more than swing changes during them. Coaches on the <a href=\"junior-academy.html\">Junior Academy</a> screen juniors as a matter of course and build age-appropriate movement work in, well before anyone touches a weight."),
                 ("h3", "Ladies and Beginners Building From Scratch"),
                 ("p", "Starting golf with a body that can already rotate and stabilise makes learning far quicker, because you are not learning compensations. The <a href=\"ladies-academy.html\">Ladies Academy</a> includes movement work, and new golfers coming through <a href=\"beginner-coaching.html\">beginner coaching</a> or <a href=\"get-into-golf.html\">Get Into Golf</a> can add a screening at any point."),
             ], "alt": True},

            {"type": "stats", "items": [("£75", "TPI Screening"), ("TPI", "Certified Coaches"), ("7am-8pm", "Open Every Day")]},

            {"type": "rel", "kick": "Explore the academy",
             "h2": "What Else Is at Our <em>Golf Academy?</em>",
             "p": "Fitness works best next to the rest of it. Everything below is on the same site in Codnor, Ripley.",
             "links": [
                 ("tpi-screening.html", "TPI Screening",
                  "The physical assessment every fitness plan starts from. One hour, £75, with a TPI certified PGA coach.", "TPI screening"),
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Technical coaching that works with your body rather than against it, using Trackman and video.", "Golf lessons"),
                 ("trackman-range.html", "Trackman Driving Range",
                  "Where speed gains get measured. Seven covered floodlit bays with full ball and club data.", "Trackman range"),
                 ("trackman-teaching-bay.html", "Trackman Teaching Bay",
                  "Private indoor bay where screening results are read against your actual golf swing on video.", "Teaching bay"),
                 ("monthly-programme.html", "Monthly Programme",
                  "Continuous coaching at £60 a month, with physical and technical work reviewed side by side.", "Monthly coaching"),
                 ("junior-academy.html", "Junior Academy",
                  "Coaching for younger golfers, including age-appropriate movement work through growth spurts.", "Junior golf"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Golf Fitness Derby &amp; Nottingham - <em>FAQs.</em>",
             "qs": [
                 ("Do I need to be fit to start golf fitness?",
                  "No, and most golfers who book are not. The screening measures where you are now, not where you should be, and the plan starts from that. Plenty of people begin with mobility work they can do on a living room floor. Turning up unfit is the reason to come, not a reason to wait."),
                 ("What happens in a TPI screening?",
                  "About an hour of structured movement tests looking at hip and thoracic rotation, shoulder mobility, pelvic control, balance and stability, each one chosen because it relates to a known golf swing characteristic. You leave with the results explained and a short plan. Full detail is on the <a href=\"tpi-screening.html\">TPI screening</a> page."),
                 ("How much does golf fitness cost?",
                  "A TPI screening is £75 and includes the assessment plus your initial programme. Follow-up work can be arranged around it, and golfers on the <a href=\"monthly-programme.html\">monthly coaching programme</a> at £60 a month have physical work built into their reviews. Call 07710 582036 for current pricing."),
                 ("Will golf fitness actually make me hit it further?",
                  "For most golfers, yes. Speed responds well to training at any age, and roughly every mile per hour of clubhead speed is worth two to three yards of carry. Gains of three to six miles an hour over eight to twelve weeks are common, though results vary with your starting point, age and how consistently you train."),
                 ("Can golf fitness fix my slice?",
                  "Sometimes, and more often than golfers expect. A slice caused by an out-to-in path can come from an inability to rotate the lower body, in which case no amount of instruction holds. If it is a grip or a face problem it is technical, and that is a <a href=\"1-1-lessons.html\">golf lesson</a>. The screening tells us which conversation to have."),
                 ("Is this suitable for older golfers?",
                  "It is arguably most useful for them. Seniors typically screen with limited hip and thoracic rotation, which explains both the lost distance and the sore back. Programmes are built to be gentle and gradual. Several of our regulars are the wrong side of seventy and hitting it further than they did at sixty five."),
                 ("Do I need a gym membership?",
                  "No. Most programmes use bodyweight, a resistance band and a mat, and take ten to fifteen minutes. The work that changes a golf swing is generally mobility and control rather than heavy lifting. If you already have a gym you use, the plan can be written to fit around what is available there."),
                 ("Is golf fitness the same as physiotherapy?",
                  "No. We assess movement in relation to the golf swing and train it. We do not diagnose or treat injuries. If something hurts, see a GP or physiotherapist first, then bring the screening in afterwards to build back sensibly. The two work together well, and we are happy to work alongside a clinician."),
                 ("Can juniors and ladies do golf fitness?",
                  "Yes. Juniors are screened as part of the <a href=\"junior-academy.html\">Junior Academy</a>, with movement work suited to their stage of growth and no loading. The <a href=\"ladies-academy.html\">Ladies Academy</a> includes mobility and stability work in its sessions, and any individual screening can be booked separately."),
             ], "alt": True},
        ],
    },

    # ========================================================= GRASS RANGE
    {
        "file": "grass-range.html",
        "cur": "grass-range.html",
        "title": "Grass Driving Range Ripley, Derbyshire | Real Turf Practice | Evolution Golf Academy",
        "desc": "Grass driving range in Ripley, Derbyshire. Real turf, real divots and honest strike feedback, with covered Trackman bays as the year-round option. 15 minutes from Derby, free parking.",
        "visit_kick": "Grass driving range in Ripley, Derbyshire",
        "cta": ("Hit off <em>real grass.</em>",
                "The grass range runs through the drier months at Ormonde Fields, Ripley. Covered Trackman bays open 7am to 8pm, every day of the year."),
        "hero": {
            "kick": "Grass Driving Range in Ripley, Derbyshire",
            "l1": "Grass", "l2": "Range.",
            "p": "Our <strong>grass driving range in Ripley, Derbyshire</strong> lets you hit off real turf and take real divots, which is the only way to find out what your strike is genuinely doing. Mats forgive fat shots. Grass does not, and that honesty is the point.",
            "img": "student_swing",
            "alt": "Grass driving range at Evolution Golf Academy in Ripley, Derbyshire",
        },
        "marq": ["Grass Driving Range Ripley", "Real Turf Practice", "Honest Strike Feedback",
                 "Low Point Control", "Derbyshire Golf Academy", "15 Minutes From Derby"],
        "sections": [

            {"type": "prose", "kick": "Real turf practice in Derbyshire",
             "h2": "What Is a <em>Grass Driving Range?</em>",
             "blocks": [
                 ("p", "A <strong>grass driving range</strong> is exactly what it sounds like and rarer than it should be: an outdoor practice area where you hit off natural turf rather than a synthetic mat. Ours sits on the ground at Ormonde Fields Golf Club in Codnor, Ripley, and it is open through the drier months of the year, with the covered <a href=\"trackman-range.html\">Trackman range bays</a> carrying the load in winter."),
                 ("p", "Most golfers in Derby, Nottingham and across Derbyshire do the overwhelming majority of their practice on mats, then wonder why the ball behaves differently on the course. The reason is not mysterious. A mat and a fairway respond to a slightly heavy strike in completely opposite ways, and only one of them tells you the truth."),
                 ("h3", "Why Do Mats Hide a Fat Shot?"),
                 ("p", "Because the club bounces. Hit two inches behind the ball on a mat and the sole skids off the surface into the back of the ball, and the shot comes out somewhere close to normal. Do the same on turf and the club digs, the divot starts before the ball, and you have a chunk that finishes forty yards short. The swing was identical. The feedback was not."),
                 ("p", "Over a winter of mat practice that adds up. Golfers groove a low point behind the ball without ever being told, then arrive in April convinced they have lost their game overnight. They have not. They have been practising a fault that the surface was covering up for them."),
                 ("h3", "What Is Low Point Control and Why Does It Matter?"),
                 ("p", "Low point is where the clubhead reaches the bottom of its arc. For an iron off the fairway it needs to be in front of the ball, so you strike ball first and take the divot after. It is the single most important factor in decent iron play, and it is the thing grass measures for you automatically. The divot tells you where the low point was, in the ground, permanently."),
                 ("p", "That is why coaches move outdoors when the weather allows. A <a href=\"1-1-lessons.html\">golf lesson</a> on strike is far more productive on turf, and the Trackman data from a grass shot reflects a real contact rather than a mat-assisted one."),
             ]},

            {"type": "cards", "kick": "What the grass range gives you",
             "h2": "What Does the Grass Range at Our <em>Derbyshire Academy</em> Offer?",
             "p": "It is a simple facility doing something the indoor bays cannot do. That is the whole reason it exists.",
             "cards": [
                 {"img": "ball_tee", "alt": "Real turf golf practice on the grass driving range in Ripley",
                  "h": "Real Turf, Real Divots",
                  "p": "Hit from natural ground and read your own divots. Where the divot starts, how deep it goes and which way it points tells you more about your strike than any amount of hitting off rubber."},
                 {"img": "driver_balls", "alt": "Golfer practising every club on the grass range in Derbyshire",
                  "h": "Every Club, Off the Deck",
                  "p": "Fairway woods, hybrids and long irons off grass behave nothing like they do off a mat. If you have never hit a three wood off the deck in practice, the first attempt should not be on the fifteenth."},
                 {"img": "on_course", "alt": "Practising varied lies on grass before playing the course",
                  "h": "Varied Lies",
                  "p": "Slightly sitting down, slightly sitting up, a bit thin at the edges. Real turf hands you lies that a flat mat never will, which is a reasonable rehearsal for the golf course fifty yards away."},
                 {"img": "student_swing", "alt": "PGA coaching session on the grass driving range near Derby",
                  "h": "Coaching Outdoors",
                  "p": "PGA coaches take lessons out here when the ground is right and the work calls for it, usually strike, low point and anything involving genuine ball-then-turf contact."},
             ]},

            {"type": "split", "img": "ball_tee",
             "img_alt": "Golf ball on real turf at the grass driving range in Derbyshire",
             "kick": "Grass against mats",
             "h2": "Is Grass Better Than Mats for <em>Practice?</em>",
             "paras": [
                 "For strike, yes, without much argument. A <strong>grass driving range</strong> gives honest feedback on low point and contact quality, and it does it on every single shot without anybody having to tell you. Mats give you volume, comfort and year-round availability, and they are kinder to your wrists and elbows over a long session.",
                 "The sensible answer is that you want both, used for different jobs. Do your repetition work and your data work in the covered bays, then test the strike on turf before it matters. Golfers who only ever practise on mats tend to be worse at ball-first contact than they think, and golfers who only ever practise on grass tend to stop practising in November.",
             ],
             "ticks": [
                 "<b>Honest strike feedback</b> - the divot tells you where your low point actually was",
                 "<b>Long clubs off the deck</b> - fairway woods and hybrids as the course will ask for them",
                 "<b>Kinder on the golf course</b> - what you practise is what you will face",
                 "<b>Covered bays as backup</b> - the <a href=\"trackman-range.html\">Trackman range</a> runs 7am to 8pm all year",
                 "<b>Short game next door</b> - pair it with the <a href=\"short-game.html\">short game practice area</a>",
             ],
             "btn2": ("See the Trackman range", "trackman-range.html"), "alt": True},

            {"type": "steps", "kick": "Using the grass range",
             "h2": "How Do I Use the <em>Grass Driving Range?</em>",
             "p": "Nothing complicated, but a call before you set off in changeable weather will save you a wasted journey.",
             "steps": [
                 ("Check it is open",
                  "The grass range is seasonal and weather dependent. It opens when the ground can take traffic and closes when it cannot, which in Derbyshire is a moving target. Ring 07710 582036 on the day if the weather has been unkind."),
                 ("Park and pick up a basket",
                  "Free parking on site at Ormonde Fields Golf Club, Nottingham Road, Codnor. Baskets start from £4. Larger baskets are better value if you intend to spend real time on it."),
                 ("Work along the turf, not into one hole",
                  "Take your divots in a line, working backwards or sideways so you use fresh ground each shot. It keeps the surface usable for the next golfer and gives you a clean lie every time, which is the point of being out there."),
                 ("Watch the divots, not just the ball",
                  "After each shot, look at where the divot started relative to where the ball was. That is your low point, and it is more useful information than the flight, particularly with mid and short irons."),
                 ("Move indoors when the weather turns",
                  "When the ground is too wet or the light has gone, the covered <a href=\"trackman-range.html\">Trackman bays</a> are floodlit until 8pm every day, and the <a href=\"trackman-simulator.html\">golf simulator</a> is booked by the hour."),
             ]},

            {"type": "prose", "kick": "Seasons and weather",
             "h2": "When Is the <em>Grass Range Open?</em>",
             "blocks": [
                 ("h3", "It Is Seasonal, and We Are Honest About That"),
                 ("p", "Natural turf needs recovery time and it will not take heavy traffic when it is saturated. The grass range therefore runs through the drier part of the year and closes when conditions demand it. Anyone claiming a grass range in the East Midlands is open every day of the winter is describing a field they are about to ruin."),
                 ("h3", "What Happens When It Is Closed?"),
                 ("p", "Practice carries on indoors. The <a href=\"trackman-range.html\">Trackman driving range</a> has seven covered, floodlit bays open 7am to 8pm every day of the year, with full ball and club data on every shot. That is the year-round facility, and for most golfers it is where the bulk of the work happens."),
                 ("h3", "How Do I Know Before I Travel?"),
                 ("p", "Call 07710 582036. It takes thirty seconds and it beats driving over from Derby or Nottingham to find the ropes across. If you are coming for coaching, your PGA Professional will decide on the day whether the session is better served on turf or in the <a href=\"trackman-teaching-bay.html\">teaching bay</a>."),
                 ("h3", "Is It Worth Building a Trip Around?"),
                 ("p", "If your iron striking is the weak point, yes. An hour on grass in June will tell you more about your contact than a winter of mats. Pair it with the <a href=\"short-game.html\">short game area</a> and you have half of a genuinely useful practice morning, with the covered <a href=\"trackman-simulator.html\">simulator and indoor bays</a> covering the rest."),
             ], "alt": True},

            {"type": "stats", "items": [("£4", "Baskets From"), ("7", "Covered Bays Year-Round"), ("15 min", "From Derby")]},

            {"type": "rel", "kick": "Explore the academy",
             "h2": "What Else Is at Our <em>Golf Academy?</em>",
             "p": "The grass range is one part of a site that also runs indoors, seven days a week, all year.",
             "links": [
                 ("trackman-range.html", "Trackman Driving Range",
                  "Seven covered, floodlit bays with full ball data. Walk in, no booking, 7am to 8pm every day.", "Trackman range"),
                 ("short-game.html", "Short Game Area",
                  "Chipping, pitching, bunker play and putting, a short walk from the grass range.", "Short game"),
                 ("trackman-simulator.html", "Trackman Simulator",
                  "Play famous courses indoors, or use the bay for winter practice at £25 per hour.", "Golf simulator"),
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes with a PGA Professional, indoors or on turf depending on what the session needs.", "Golf lessons"),
                 ("trackman-teaching-bay.html", "Trackman Teaching Bay",
                  "Private indoor bay with Trackman, video analysis, mirrors and training aids.", "Teaching bay"),
                 ("location.html", "Find Us in Ripley",
                  "Nottingham Road, Codnor, Ripley DE5 9RL. Fifteen minutes from Derby, twenty from Nottingham.", "Location"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Grass Driving Range Ripley - <em>FAQs.</em>",
             "qs": [
                 ("Is the grass driving range open all year?",
                  "No. It is seasonal and weather dependent, because natural turf needs recovery time and will not take traffic when saturated. It runs through the drier months. The covered <a href=\"trackman-range.html\">Trackman range bays</a> are the year-round option, open 7am to 8pm every day including through winter."),
                 ("Do I need to book the grass range?",
                  "No, it runs on the same walk-in basis as the covered bays. What we would suggest is a quick call to 07710 582036 before you travel if the weather has been wet, because there is nothing more irritating than driving over from Nottingham to find the turf closed for recovery."),
                 ("How much does it cost to use the grass range?",
                  "Baskets start from £4 for a small basket, with larger baskets better value for longer sessions. There is no separate charge for using the turf rather than a covered bay. Prices are reviewed occasionally, so confirm on 07710 582036 if you are planning a long session."),
                 ("Why practise on grass instead of a mat?",
                  "Because a mat hides a fat shot. The sole bounces off the surface and the ball still goes somewhere reasonable, so you never learn that your low point is behind the ball. On turf the club digs and the shot goes nowhere, which is unpleasant, honest and exactly the feedback you need."),
                 ("Can I have a golf lesson on the grass range?",
                  "Yes, when conditions allow and when the work suits it, which usually means strike, low point or long clubs off the deck. Most lessons run in the <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a> because it is private and fully equipped, and your coach will choose on the day."),
                 ("Can I hit driver off the grass range?",
                  "Yes, tees are used on the grass range as normal, so driver and fairway woods are both fine. Hitting fairway woods and hybrids off the deck is arguably the best reason to be out there, because they behave completely differently on turf and almost nobody practises it."),
                 ("Where exactly is the grass range?",
                  "At Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL, on the same site as everything else we run. That is roughly 15 minutes from Derby and 20 from Nottingham on the A610, with free parking. See <a href=\"location.html\">our location page</a> for directions."),
                 ("What should I wear on the grass range?",
                  "Golf shoes or trainers with reasonable grip, and something you do not mind getting muddy at the edges of the season. Spikes are fine. Bear in mind you are outdoors in Derbyshire, so waterproofs live in the bag from about September onwards regardless of the forecast."),
                 ("Is there somewhere to practise short game as well?",
                  "Yes, the <a href=\"short-game.html\">short game practice area</a> is on the same site and covers chipping, pitching, bunker play and putting. Golfers who combine an hour on the grass range with an hour on the short game area tend to see their scores move faster than those who only hit full shots."),
             ], "alt": True},
        ],
    },

    # ========================================================== SHORT GAME
    {
        "file": "short-game.html",
        "cur": "short-game.html",
        "title": "Short Game Practice Area Derbyshire | Chipping, Bunker &amp; Putting | Evolution Golf Academy",
        "desc": "Short game practice area in Derbyshire, near Derby and Nottingham. Chipping, pitching, bunker play and putting greens, plus PGA short game coaching. Ripley DE5 9RL, free parking.",
        "visit_kick": "Short game practice area in Derbyshire",
        "cta": ("Save your shots <em>around the green.</em>",
                "Chipping, pitching, bunkers and putting at Ormonde Fields, Ripley. Open seven days, fifteen minutes from Derby."),
        "hero": {
            "kick": "Short Game Practice Area in Derbyshire",
            "l1": "Short", "l2": "Game.",
            "p": "Our <strong>short game practice area in Derbyshire</strong> covers chipping, pitching, bunker play and putting, all on the same site near Derby and Nottingham. Somewhere between half and two thirds of your shots happen inside 100 yards, which is where handicaps actually fall.",
            "img": "putting",
            "alt": "Short game practice area and putting green in Derbyshire at Evolution Golf Academy",
        },
        "marq": ["Short Game Area Derbyshire", "Chipping &amp; Pitching", "Bunker Practice",
                 "Putting Green", "PGA Short Game Coaching", "Ripley, Near Derby"],
        "sections": [

            {"type": "prose", "kick": "Inside 100 yards, near Derby &amp; Nottingham",
             "h2": "What Is a <em>Short Game Practice Area?</em>",
             "blocks": [
                 ("p", "A <strong>short game practice area</strong> is ground set aside for the shots that finish holes rather than start them: chips, pitches, bunker shots and putts. Ours is at Ormonde Fields Golf Club in Codnor, Ripley, alongside the <a href=\"trackman-range.html\">Trackman driving range</a>, and it is where golfers who care about their scorecard spend the second half of a practice session."),
                 ("p", "It is also, by some margin, the most neglected facility on any golf site in the country. Walk past a range at six on a summer evening near Derby or Nottingham and every bay is full of drivers. Walk past the chipping green and there will be one person on it, and they will be the one who has taken four shots off their handicap this year."),
                 ("h3", "How Many Shots Actually Happen Inside 100 Yards?"),
                 ("p", "For most club golfers, somewhere between half and two thirds of every round. Count them honestly on your next eighteen. A bogey golfer shooting around 90 will typically take 32 to 36 putts and add fifteen or so chips, pitches and bunker shots on top. That is well over half the card, played with clubs that get a fraction of the practice time."),
                 ("p", "Meanwhile there are fourteen tee shots, and maybe ten full iron shots. The maths is unkind to the way most people practise. Nobody wants to hear it, because hitting drivers is enjoyable and hitting forty yard pitches is not, but the shots are where the shots are."),
                 ("h3", "Why Does the Short Game Decide Your Handicap?"),
                 ("p", "Because it is where the big numbers come from and where they get rescued. A missed green is a par for the golfer who can chip and a double for the golfer who cannot, and over eighteen holes you will miss between eight and twelve greens. Improving your long game moves the misses closer. Improving your short game turns those misses into fours instead of sixes, and it does it far faster."),
                 ("p", "It is also the part of golf least dependent on physical ability, which is why it rewards practice so reliably. You do not need speed, flexibility or a new driver. You need repetitions and honest feedback, both of which are free once you are here. If you want the technique checked first, that is a <a href=\"1-1-lessons.html\">lesson with a PGA Professional</a>."),
             ]},

            {"type": "cards", "kick": "Four skills, one area",
             "h2": "What Can You Practise in the <em>Short Game Area?</em>",
             "p": "Everything from a hundred yards in, on the same patch of ground, without moving your bag more than fifty paces.",
             "cards": [
                 {"img": "putting", "alt": "Putting green practice at the short game area in Derbyshire",
                  "h": "Putting",
                  "p": "The largest single line on your scorecard. Work on start line, speed control and the three to six footers that decide whether a good round survives the back nine. Bring a couple of tees and a coin."},
                 {"img": "on_course", "alt": "Chipping practice around the green near Derby and Nottingham",
                  "h": "Chipping",
                  "p": "Low running shots from just off the surface, where most amateurs lose a shot a round through indecision more than technique. Practise landing spots rather than swings and the results arrive quickly."},
                 {"img": "lesson_grip", "alt": "Pitching technique coaching at Evolution Golf Academy Ripley",
                  "h": "Pitching",
                  "p": "The awkward thirty to eighty yard range, which nobody enjoys and everybody faces. Distance control here is the difference between a tap-in and a twenty footer, and it responds enormously well to structured practice."},
                 {"img": "bunker", "alt": "Bunker practice at the short game area in Ripley, Derbyshire",
                  "h": "Bunker Play",
                  "p": "The shot most golfers fear and almost nobody practises, largely because bunkers are unavailable on a driving range. Half an hour with a coach usually removes the fear entirely, because the technique is unusual rather than difficult."},
             ]},

            {"type": "split", "img": "bunker",
             "img_alt": "Bunker shot practice at the short game area near Derby",
             "kick": "Where handicaps fall",
             "h2": "Is Short Game Practice the Fastest Way to <em>Lower Your Handicap?</em>",
             "paras": [
                 "For nearly every golfer above a five handicap, yes. A well used <strong>short game practice area</strong> pays back faster than anything else on a golf site, because the skills are simple, the repetitions are quick and the improvement transfers directly to the card. You can hit sixty chips in twenty minutes. You cannot do that with a driver, and it would not help if you could.",
                 "There is a reason coaches keep saying it and golfers keep ignoring it. Long game improvement is visible and satisfying. Short game improvement is quiet and turns up as a lower number on the scorecard three weeks later. One of those feels better in the moment and the other one actually works.",
             ],
             "ticks": [
                 "<b>Chipping, pitching, bunkers and putting</b> in one place on the same site",
                 "<b>Quick repetitions</b> - sixty shots in twenty minutes, with instant feedback",
                 "<b>Coaching available</b> - short game work with a <a href=\"1-1-lessons.html\">PGA Professional</a>",
                 "<b>Suits every level</b> - from <a href=\"beginner-coaching.html\">beginner coaching</a> upwards, with no speed or strength required",
                 "<b>Fifteen minutes from Derby</b>, twenty from Nottingham, free parking on site",
             ],
             "btn2": ("Book short game coaching", "1-1-lessons.html"), "alt": True},

            {"type": "steps", "kick": "A practice routine that works",
             "h2": "How Should I Practise My <em>Short Game?</em>",
             "p": "An hour, split into four. This is roughly what our coaches set golfers on the monthly programme, and it beats aimless chipping by a distance.",
             "steps": [
                 ("Fifteen minutes on short putts",
                  "Three to six feet, from every angle around one hole, and do not leave until you hole ten in a row. These are the putts that quietly cost two shots a round, and holing out under a small amount of self-imposed pressure is a skill in itself."),
                 ("Fifteen minutes on speed",
                  "Long putts from thirty to fifty feet, ignoring the line entirely and judging only whether the ball finishes within a club length. Three putts come from poor speed far more often than from poor reading."),
                 ("Fifteen minutes chipping to a landing spot",
                  "Put a towel or a tee where you want the ball to land, then chip to it rather than to the hole. Chipping is a landing spot and a roll-out ratio, and separating the two makes club selection obvious rather than instinctive."),
                 ("Fifteen minutes on the shot you avoid",
                  "For most golfers that is a bunker shot or a forty yard pitch. Practise the one you dread, because it is the one costing you strokes. If you cannot get out of a bunker at all, book <a href=\"1-1-lessons.html\">an hour with a coach</a> before you spend a summer digging."),
                 ("Finish with a test, not a drill",
                  "Nine random shots, one attempt each, scored up and down or not. Random beats blocked practice because golf is random. Record the score and try to beat it next week, the same way you would on the <a href=\"trackman-range.html\">Trackman range</a>."),
             ]},

            {"type": "prose", "kick": "Putting, in more detail",
             "h2": "What Is the Best Way to <em>Practise Putting?</em>",
             "blocks": [
                 ("h3", "Separate Line From Speed"),
                 ("p", "Almost every putting problem is one or the other, and practising them together means you learn neither. Spend one session on start line with a gate of two tees, and another on speed with no target at all beyond a rough distance. Golfers who do this for a month usually find the three putts disappear before the holed putts increase."),
                 ("h3", "Practise the Length You Actually Face"),
                 ("p", "Nobody has ever three putted from four feet, and nobody holes many from forty. The scoring putts are between three and ten feet, and that is where the practice time should sit. Watch a busy putting green and count how many people are lagging fifty footers because it is more pleasant than missing short ones."),
                 ("h3", "Use Pressure, Even Artificial Pressure"),
                 ("p", "Ten in a row from four feet, starting again from zero on a miss, is a genuinely uncomfortable drill by the seventh. That discomfort is the point. Practice without consequence teaches you to putt without consequence, which is not the situation you are training for."),
                 ("h3", "Get the Basics Checked Once"),
                 ("p", "Aim, eye position and face angle at impact are worth a single lesson, because they are almost impossible to self-diagnose and they undermine everything else. A short game session in the <a href=\"trackman-teaching-bay.html\">teaching bay</a> or out on the green with a coach settles it, and golfers on the <a href=\"monthly-programme.html\">monthly coaching programme</a> get it reviewed as a matter of routine."),
             ], "alt": True},

            {"type": "stats", "items": [("100", "Yards and In"), ("7am-8pm", "Open Every Day"), ("15 min", "From Derby")]},

            {"type": "rel", "kick": "Explore the academy",
             "h2": "What Else Is at Our <em>Golf Academy?</em>",
             "p": "The short game area sits alongside everything else at Ormonde Fields in Codnor, Ripley.",
             "links": [
                 ("trackman-range.html", "Trackman Driving Range",
                  "Seven covered, floodlit bays with full ball data. Walk in, 7am to 8pm, seven days a week.", "Trackman range"),
                 ("grass-range.html", "Grass Driving Range",
                  "Real turf and honest strike feedback through the drier months, a short walk away.", "Grass range"),
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Short game coaching with a PGA Professional, £55 an hour, on the green or in the bay.", "Golf lessons"),
                 ("trackman-teaching-bay.html", "Trackman Teaching Bay",
                  "Private indoor bay with Trackman, video analysis, mirrors and training aids.", "Teaching bay"),
                 ("monthly-programme.html", "Monthly Programme",
                  "Continuous coaching at £60 a month, including structured short game practice plans.", "Monthly coaching"),
                 ("beginner-coaching.html", "Beginner Coaching",
                  "New golfers often start around the green, where the swing is short and the wins are quick.", "Beginner golf"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Short Game Practice Area Derbyshire - <em>FAQs.</em>",
             "qs": [
                 ("Do I need to book the short game area?",
                  "No, it works on the same walk-in basis as the <a href=\"trackman-range.html\">Trackman driving range</a>, seven days a week from 7am to 8pm. Only coaching, <a href=\"trackman-simulator.html\">simulator bays</a> and custom fitting need booking. Bring your own balls for chipping and putting practice."),
                 ("How much does the short game area cost to use?",
                  "There is no charge for using the putting and chipping areas with your own golf balls. If you want range balls for pitching, baskets start from £4. Short game coaching with a PGA Professional is charged as a normal lesson at £55 per hour. Call 07710 582036 to check."),
                 ("Is there a bunker to practise from?",
                  "Yes, bunker practice is part of the short game area, which makes it one of the few places near Derby and Nottingham where you can actually work on the shot. Most golfers avoid bunkers entirely until they are standing in one, which is a poor moment to learn the technique."),
                 ("How much of my practice should be short game?",
                  "If you want your handicap to fall, at least half. Somewhere between half and two thirds of the shots in a typical round happen inside 100 yards, and most amateurs spend under a quarter of their practice time there. Simply reversing that ratio moves scores for almost everybody."),
                 ("Can beginners use the short game area?",
                  "Yes, and it is arguably the best place for a new golfer to start. The swings are short, the ball goes a sensible distance and the feedback is immediate, none of which is true of a driver. <a href=\"beginner-coaching.html\">Beginner coaching</a> and <a href=\"get-into-golf.html\">Get Into Golf</a> both spend time around the green."),
                 ("Can I have a short game lesson?",
                  "Yes. Chipping, pitching, bunker play and putting are all covered in a standard <a href=\"1-1-lessons.html\">1:1 lesson</a> at £55 an hour, taken out on the short game area where the shots actually live. Many golfers get more from one short game hour than from three full swing lessons."),
                 ("Is the short game area open in winter?",
                  "It is open year-round in principle, but it is outdoors, so frost, waterlogging and darkness all affect it. Between November and February most short game work moves indoors to the <a href=\"trackman-teaching-bay.html\">teaching bay</a>, where wedge distance control can be measured on Trackman regardless of the weather."),
                 ("What should I bring?",
                  "Your wedges, your putter, a sand wedge with reasonable bounce if you have one, and a handful of your own golf balls. A towel and a couple of tees are useful for marking landing spots. Golf shoes or trainers with grip are sensible on wet grass."),
                 ("Where is the short game area?",
                  "On the same site as everything else, at Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL. That is around 15 minutes from Derby and 20 from Nottingham on the A610, with free parking. See <a href=\"location.html\">our location page</a> for directions."),
             ], "alt": True},
        ],
    },
]
