"""Local SEO landing pages - the two city pages plus the FAQ hub.

These are the pages that have to rank for "golf lessons Derby" and
"golf lessons Nottingham", so they carry the deepest copy and link
hardest into the service pages.
"""

_PRICES = [
    {"amt": "£55", "per": "per session", "h": "1:1 PGA Lesson",
     "p": "Sixty minutes with an Advanced PGA Professional, Trackman data and video analysis throughout. The standard starting point for most golfers."},
    {"amt": "£60", "per": "per month", "h": "Monthly Programme", "feat": True, "tag": "Most Popular",
     "p": "Structured, ongoing coaching with a plan between sessions rather than occasional one-off lessons."},
    {"amt": "£75", "per": "per session", "h": "TPI Screening",
     "p": "Titleist Performance Institute movement screening, linking physical limitations to your swing faults."},
]

PAGES = [

    # ================================================== DERBY
    {
        "file": "golf-lessons-derby.html",
        "cur": "golf-lessons-derby.html",
        "title": "Golf Lessons in Derby | PGA Professional Coaching | Evolution Golf Academy",
        "desc": "Golf lessons in Derby with an Advanced PGA Professional. Trackman coaching, covered driving range, indoor simulators and custom fitting, 15 minutes from Derby city centre on the A610.",
        "visit_kick": "Golf lessons near Derby",
        "cta": ("Book your golf lesson in <em>Derby.</em>",
                "PGA Professional coaching with Trackman data on every shot, fifteen minutes from Derby city centre. Open seven days a week, 7am to 8pm."),
        "hero": {
            "kick": "Golf Lessons in Derby - PGA Professional Coaching",
            "l1": "Golf Lessons", "l2": "Derby.",
            "p": "<strong>Golf lessons in Derby</strong> are available at Evolution Golf Academy, fifteen minutes from the city centre on the A610. PGA Professional coaching, Trackman data on every shot, a covered floodlit driving range and indoor simulators, all on one site with free parking.",
            "img": "lesson_grip",
            "alt": "Golf lessons in Derby with an Advanced PGA Professional at Evolution Golf Academy",
        },
        "marq": ["Golf Lessons Derby", "PGA Golf Coach Derby", "Trackman Range Near Derby",
                 "Golf Tuition Derby", "Beginner Golf Lessons Derby", "Golf Academy Derbyshire"],
        "sections": [

            {"type": "prose", "kick": "Golf coaching for Derby golfers",
             "h2": "Where Can You Get <em>Golf Lessons in Derby?</em>",
             "blocks": [
                 ("p", "Derby is not short of places to hit a golf ball, but it is short of places to actually learn. Most options are either a members' club with a waiting list and a dress code, or a strip of mats with no coaching attached. <strong>Golf lessons in Derby</strong> at Evolution Golf Academy sit deliberately between the two: a full performance facility with Advanced PGA Professional coaching, open to anybody, and you do not need to be a member to book."),
                 ("p", "We are based at Ormonde Fields Golf Club in Codnor, just outside Ripley, which puts us roughly fifteen minutes from Derby city centre on the A610. For most Derby golfers that is a shorter journey than crossing the city in rush hour, and there is free parking when you arrive rather than a multi-storey and a walk."),
                 ("h3", "What Makes This Different From a Normal Driving Range?"),
                 ("p", "Every bay on our range is fitted with Trackman, the dual-radar launch monitor used on the PGA Tour. That means when you take a <a href=\"1-1-lessons.html\">golf lesson with an Advanced PGA Professional</a>, your coach is working from measured numbers rather than an opinion about what your ball flight looked like. Ball speed, launch angle, spin rate, carry distance, club path and face angle are all on screen within a second of impact."),
                 ("p", "It changes what a lesson can achieve. Instead of \"that looked better\", you get a number that either moved or did not. If a grip change adds four miles an hour of ball speed and straightens your club path by three degrees, you can see it happen, and so can your coach."),
                 ("h3", "Do You Need to Be Any Good to Book a Lesson?"),
                 ("p", "No, and this is the single most common thing Derby golfers ask before booking. We coach complete beginners every week. <a href=\"beginner-coaching.html\">Beginner golf lessons</a> assume no prior knowledge, we can lend you a set, and nobody expects you to know what a lie angle is. If you have literally never held a club, <a href=\"get-into-golf.html\">Get Into Golf</a> is an even gentler starting point."),
             ]},

            {"type": "cards", "kick": "Coaching available to Derby golfers",
             "h2": "What Golf Coaching Is Available <em>Near Derby?</em>",
             "p": "Everything below runs from the same site in Codnor, so you are never sent somewhere else for the next stage.",
             "cards": [
                 {"img": "lesson_grip", "alt": "One to one golf lesson near Derby",
                  "h": "1:1 Golf Lessons",
                  "p": "Sixty minutes with an Advanced PGA Professional, Trackman data and video analysis throughout. The fastest route to fixing whatever is actually costing you shots.",
                  "href": "1-1-lessons.html", "cta": "Golf lessons"},
                 {"img": "range_night", "alt": "Trackman driving range near Derby",
                  "h": "Trackman Driving Range",
                  "p": "Covered floodlit bays with ball speed, carry and shot shape on every swing. Walk in with no booking, from £4 a basket, seven days a week.",
                  "href": "trackman-range.html", "cta": "Driving range"},
                 {"img": "sim", "alt": "Indoor golf simulator near Derby",
                  "h": "Indoor Golf Simulator",
                  "p": "Play world-famous courses indoors on Trackman. For Derby golfers this is what keeps the game going through January and February.",
                  "href": "trackman-simulator.html", "cta": "Golf simulator"},
                 {"img": "tpi", "alt": "TPI screening and custom club fitting near Derby",
                  "h": "TPI Screening &amp; Fitting",
                  "p": "Movement screening and Trackman-based custom club fitting, so neither your body nor your equipment is quietly holding you back.",
                  "href": "tpi-screening.html", "cta": "TPI screening"},
             ]},

            {"type": "split", "img": "range_night",
             "img_alt": "Driving range fifteen minutes from Derby city centre",
             "kick": "Getting here from Derby",
             "h2": "How Far Is Evolution Golf Academy <em>From Derby?</em>",
             "paras": [
                 "<strong>About fifteen minutes from Derby city centre</strong>, straight out on the A610. No motorway, no city parking charges, and free parking on site when you get here.",
                 "We are open 7am to 8pm every day of the week, which for most Derby golfers means a lesson before work or a range session after it are both realistic rather than theoretical.",
             ],
             "ticks": [
                 "<b>15 minutes from Derby city centre</b> via the A610 through Ripley",
                 "<b>Free parking on site</b> - no permits, no charges, no walk",
                 "<b>Open 7 days</b> - 7am to 8pm, floodlit through the winter",
                 "<b>Everything on one site</b> - coaching, <a href=\"trackman-range.html\">range</a>, <a href=\"trackman-simulator.html\">simulators</a>, <a href=\"golf-fitness.html\">fitness</a> and fitting",
                 "<b>No need to be a member</b> - book a single lesson and nothing more",
             ],
             "btn2": ("Find us", "location.html"), "alt": True},

            {"type": "steps", "kick": "Directions",
             "h2": "How Do You Get to the Academy <em>From Derby?</em>",
             "p": "Whichever side of the city you are starting from, the A610 does most of the work.",
             "steps": [
                 ("From Derby city centre",
                  "Head north east out of the city and join the A610 towards Ripley and Codnor. Stay on it past Ripley and the academy is on Nottingham Road at Ormonde Fields Golf Club. Around fifteen minutes in normal traffic."),
                 ("From Allestree, Oakwood and Chaddesden",
                  "You are already on the right side of the city. Pick up the A38 or the A61 north and cut across to the A610 at Ripley. Typically twelve to eighteen minutes."),
                 ("From Spondon, Borrowash and Long Eaton",
                  "Head north through Ilkeston and Heanor and join the A610 at Codnor. Around twenty minutes, and you avoid Derby city traffic entirely."),
                 ("From Mickleover and the south west",
                  "Ring road round to the A38 north, then across to Ripley. Allow twenty five minutes at peak times."),
                 ("Parking and arrival",
                  "Free parking on site at Ormonde Fields Golf Club. Come to the academy building, and if it is your first <a href=\"1-1-lessons.html\">golf lesson</a>, arrive ten minutes early so your coach can talk through what you want from it."),
             ]},

            {"type": "prices", "kick": "Golf lesson prices",
             "h2": "How Much Do <em>Golf Lessons Cost in Derby?</em>",
             "p": "No joining fee, and no need to be a member. You pay for the coaching you book.",
             "cards": _PRICES},

            {"type": "prose", "kick": "Choosing the right coaching",
             "h2": "Which Golf Lessons Are Right <em>for You?</em>",
             "blocks": [
                 ("h3", "If You Have Never Played Golf Before"),
                 ("p", "Start with <a href=\"get-into-golf.html\">Get Into Golf</a> or <a href=\"beginner-coaching.html\">beginner golf lessons</a>. Both assume nothing, provide clubs, and are built around getting you comfortable rather than technically perfect. Most Derby beginners are playing a short course within a few months."),
                 ("h3", "If You Play but Have Stopped Improving"),
                 ("p", "This is what the <a href=\"monthly-programme.html\">monthly coaching programme</a> exists for. Occasional one-off lessons tend to produce a good week followed by a slow slide back. Structured coaching with a practice plan between sessions is what actually shifts a handicap."),
                 ("h3", "If Your Body Is Fighting Your Swing"),
                 ("p", "If you physically cannot get into a position, no amount of coaching will put you there. <a href=\"tpi-screening.html\">TPI screening</a> assesses how your body moves and links each restriction to the swing fault it produces, and the <a href=\"golf-fitness.html\">golf fitness suite</a> is where you then work on it."),
                 ("h3", "If Your Clubs Might Be the Problem"),
                 ("p", "Off-the-shelf clubs fit the average golfer, and almost nobody is average. Our fitters run custom fitting using Trackman data, covering shaft, loft, lie and gapping, and you leave with a full specification document. Fittings are brand neutral, so you can buy from us or anywhere you like."),
                 ("h3", "If You Are Bringing a Child"),
                 ("p", "The <a href=\"junior-academy.html\">junior academy</a> covers ages six to sixteen under Will Painter, Advanced PGA Professional. Plenty of Derby parents drive over for it because structured junior coaching is genuinely hard to find locally."),
             ], "alt": True},

            {"type": "areas", "kick": "Areas we serve near Derby",
             "h2": "Which Areas Near Derby <em>Do You Cover?</em>",
             "p": "Golfers travel to us from right across Derby and south Derbyshire. If you are within half an hour of Ripley on the road network, the drive is worth it.",
             "tags": [("Derby", None), ("Allestree", None), ("Oakwood", None), ("Chaddesden", None),
                      ("Spondon", None), ("Mickleover", None), ("Borrowash", None), ("Duffield", None),
                      ("Ilkeston", None), ("Belper", None), ("Long Eaton", None), ("Heanor", None),
                      ("Alfreton", None), ("Swanwick", None), ("Langley Mill", None),
                      ("Ripley", "location.html"), ("Nottingham", "golf-lessons-nottingham.html")]},

            {"type": "rel", "kick": "Explore the academy",
             "h2": "What Else Is on Site <em>Near Derby?</em>",
             "links": [
                 ("trackman-range.html", "Trackman Driving Range",
                  "Covered floodlit bays with full ball and club data on every shot. Walk in, no booking, from £4.", "Driving range"),
                 ("trackman-teaching-bay.html", "Trackman Teaching Bay",
                  "A private, quiet bay with Trackman, video analysis and training aids, used for one to one coaching.", "Teaching bay"),
                 ("trackman-simulator.html", "Trackman Simulator",
                  "Play championship courses indoors, or use it as a practice tool when the weather closes in.", "Golf simulator"),
                 ("short-game.html", "Short Game Area",
                  "Chipping, pitching, bunker play and putting - where most amateur golfers save the quickest strokes.", "Short game"),
                 ("meet-team.html", "Meet the PGA Coach",
                  "Will Painter, Advanced PGA Professional, and the expertise behind the coaching here.", "Our coach"),
                 ("golf-lessons-nottingham.html", "Golf Lessons Nottingham",
                  "Coming from the other direction? The same academy, twenty minutes out on the A610.", "Nottingham"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Golf Lessons Derby - <em>FAQs.</em>",
             "qs": [
                 ("How far is Evolution Golf Academy from Derby city centre?",
                  "Roughly fifteen minutes by car via the A610. We are at Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RJ, with free parking on site. For most parts of Derby it is a quicker trip than crossing the city at rush hour."),
                 ("How much do golf lessons cost in Derby?",
                  "A 1:1 lesson with an Advanced PGA Professional is £55 for sixty minutes. The <a href=\"monthly-programme.html\">monthly coaching programme</a> is £60 per month, and <a href=\"tpi-screening.html\">TPI movement screening</a> is £75. There is no joining fee and you do not need to be a member. Call 07710 582036 to confirm current prices."),
                 ("Is there a Trackman range near Derby?",
                  "Yes. Our <a href=\"trackman-range.html\">Trackman driving range</a> is the closest Trackman-equipped range to Derby, with covered floodlit bays open every day from 7am to 8pm. Every bay gives you ball speed, launch angle, spin rate, carry distance and shot shape on screen."),
                 ("Can I turn up without booking?",
                  "For the driving range, yes - it is walk-in on a first-come basis. Golf lessons, <a href=\"trackman-simulator.html\">simulator bays</a>, private teaching bays and custom fitting sessions all need booking in advance."),
                 ("Do you coach complete beginners from Derby?",
                  "Regularly. <a href=\"beginner-coaching.html\">Beginner golf lessons</a> assume no experience at all and we can lend you a set, so there is nothing to buy before your first session. If you would rather start in a group, <a href=\"get-into-golf.html\">Get Into Golf</a> is designed for exactly that."),
                 ("Do you offer junior golf lessons near Derby?",
                  "Yes. Will Painter, Advanced PGA Professional, runs the <a href=\"junior-academy.html\">junior academy</a> for ages six to sixteen, with both individual lessons and group sessions. A lot of Derby parents make the trip because structured junior coaching is hard to find closer in."),
                 ("Are there ladies golf lessons near Derby?",
                  "Yes. <a href=\"ladies-academy.html\">Ladies coaching</a> is available for all abilities including complete beginners. We are a coaching academy rather than a members' club, so there is no dress code to decode and no clubhouse politics to navigate."),
                 ("What is the best driving range near Derby?",
                  "We would say ours, but the honest answer is that it depends what you want. If you want to hit balls cheaply, plenty of ranges will do. If you want to know your actual carry distances and improve measurably, a Trackman range gives you information a mat and a bucket cannot."),
                 ("Do I need my own golf clubs?",
                  "Not for your first lesson. We can lend you a set, and club hire on the range and simulators is included at no extra cost. Once you are playing regularly it is worth getting your own, and a brand neutral custom fitting using Trackman data will make sure you buy the right ones rather than guessing off a shop shelf."),
             ], "alt": True},
        ],
    },

    # ================================================== NOTTINGHAM
    {
        "file": "golf-lessons-nottingham.html",
        "cur": "golf-lessons-nottingham.html",
        "title": "Golf Lessons in Nottingham | PGA Professional Coaching | Evolution Golf Academy",
        "desc": "Golf lessons near Nottingham with an Advanced PGA Professional. Trackman coaching, covered driving range, indoor simulators and custom fitting, 20 minutes out on the A610 through Eastwood.",
        "visit_kick": "Golf lessons near Nottingham",
        "cta": ("Book your golf lesson near <em>Nottingham.</em>",
                "PGA Professional coaching with Trackman on every shot, twenty minutes out on the A610. Open seven days a week, 7am to 8pm."),
        "hero": {
            "kick": "Golf Lessons in Nottingham - PGA Professional Coaching",
            "l1": "Golf Lessons", "l2": "Nottingham.",
            "p": "<strong>Golf lessons near Nottingham</strong> are available at Evolution Golf Academy, twenty minutes from the city centre on the A610 through Eastwood. A full PGA coaching facility with Trackman on every shot, indoor simulators and custom club fitting.",
            "img": "over_shoulder",
            "alt": "Golf lessons near Nottingham with an Advanced PGA Professional at Evolution Golf Academy",
        },
        "marq": ["Golf Lessons Nottingham", "PGA Golf Coach Nottingham", "Trackman Range Nottingham",
                 "Golf Tuition Nottinghamshire", "Indoor Golf Nottingham", "Golf Academy Near Me"],
        "sections": [

            {"type": "prose", "kick": "Golf coaching for Nottingham golfers",
             "h2": "Where Can You Get <em>Golf Lessons Near Nottingham?</em>",
             "blocks": [
                 ("p", "Nottingham golfers have a decent choice of courses and a much thinner choice of serious coaching facilities. <strong>Golf lessons near Nottingham</strong> at Evolution Golf Academy give you a Trackman Official Performance Centre with an Advanced PGA Professional on site, twenty minutes out of the city on the A610 through Eastwood."),
                 ("p", "The run out is straightforward. You leave Nottingham heading north west, pass through Eastwood, and the academy is on Nottingham Road at Ormonde Fields Golf Club in Codnor. No motorway, no city centre parking, and free parking when you get here. For golfers in Kimberley, Nuthall, Watnall or Eastwood it is often under fifteen minutes."),
                 ("h3", "What Is a Trackman Performance Centre?"),
                 ("p", "Trackman is the dual-radar launch monitor used on the PGA Tour and by most of the world's leading coaches. Being an Official Performance Centre means every bay here is fitted with it, so a <a href=\"1-1-lessons.html\">golf lesson</a> is built on measured data rather than a coach's impression of your ball flight."),
                 ("p", "In practice, that means you and your coach can see ball speed, spin rate, launch angle, carry distance, club path and face angle for every shot. When a change works you know immediately, because the numbers move. When it does not, you have not wasted six weeks finding out."),
                 ("h3", "Is It Worth Driving Out of Nottingham for a Lesson?"),
                 ("p", "That depends what you want from coaching. If you want somebody to watch you hit balls and offer a tip, you can find that closer to home. If you want your swing measured, your equipment checked and a plan you can follow between sessions, the twenty minutes buys you a facility that does not really exist inside the city."),
             ]},

            {"type": "cards", "kick": "Coaching available to Nottingham golfers",
             "h2": "What Golf Coaching Is Available <em>Near Nottingham?</em>",
             "p": "All of it runs from one site in Codnor, so you are never referred elsewhere for the next step.",
             "cards": [
                 {"img": "lesson_grip", "alt": "One to one golf lesson near Nottingham",
                  "h": "1:1 Golf Lessons",
                  "p": "Sixty minutes with an Advanced PGA Professional. Trackman numbers and video analysis so you can see exactly what changed and why it mattered.",
                  "href": "1-1-lessons.html", "cta": "Golf lessons"},
                 {"img": "range_night", "alt": "Trackman driving range near Nottingham",
                  "h": "Trackman Driving Range",
                  "p": "Covered, floodlit bays with full ball and club data. Walk in seven days a week, all year round, from £4 a basket.",
                  "href": "trackman-range.html", "cta": "Driving range"},
                 {"img": "sim", "alt": "Indoor golf simulator near Nottingham",
                  "h": "Indoor Golf Simulator",
                  "p": "Play championship courses indoors on Trackman. Rain over Nottingham stops being a reason not to play golf.",
                  "href": "trackman-simulator.html", "cta": "Golf simulator"},
                 {"img": "junior", "alt": "Junior and ladies golf coaching near Nottingham",
                  "h": "Junior &amp; Ladies Coaching",
                  "p": "Structured junior coaching for ages six to sixteen, and ladies lessons for all abilities from complete beginners upwards.",
                  "href": "junior-academy.html", "cta": "Junior academy"},
             ]},

            {"type": "split", "img": "bay_night",
             "img_alt": "Golf academy twenty minutes from Nottingham",
             "kick": "Getting here from Nottingham",
             "h2": "How Far Is Evolution Golf Academy <em>From Nottingham?</em>",
             "paras": [
                 "<strong>About twenty minutes from Nottingham city centre</strong>, straight out on the A610 through Eastwood. It is a single-road trip for most of the way and it avoids the motorway entirely.",
                 "If you are coming from the north west of the city - Kimberley, Nuthall, Watnall, Giltbrook - you are considerably closer than that, often twelve to fifteen minutes.",
             ],
             "ticks": [
                 "<b>20 minutes from Nottingham city centre</b> on the A610 via Eastwood",
                 "<b>Under 15 minutes</b> from Eastwood, Kimberley, Nuthall and Giltbrook",
                 "<b>Free parking</b> on site, open 7am to 8pm every day",
                 "<b>Everything in one place</b> - coaching, <a href=\"trackman-range.html\">range</a>, <a href=\"trackman-simulator.html\">simulators</a>, <a href=\"short-game.html\">short game</a> and fitting",
                 "<b>No need to be a member</b> - book one lesson and that is the whole commitment",
             ],
             "btn2": ("Find us", "location.html"), "alt": True},

            {"type": "steps", "kick": "Directions",
             "h2": "How Do You Get to the Academy <em>From Nottingham?</em>",
             "p": "The A610 runs almost door to door, whichever part of the city you set off from.",
             "steps": [
                 ("From Nottingham city centre",
                  "Head north west and pick up the A610 towards Eastwood and Ripley. Stay on it through Eastwood and Langley Mill, and the academy is on Nottingham Road at Codnor. Around twenty minutes outside peak hours."),
                 ("From Eastwood, Kimberley and Giltbrook",
                  "You are practically next door. Join the A610 north west and you are here in ten to fifteen minutes."),
                 ("From Hucknall, Bulwell and Annesley",
                  "Cut across to the A610 at Eastwood or come down through Selston. Around twenty minutes either way."),
                 ("From Beeston, Stapleford and the south",
                  "Head up the A6002 or the A52 to join the A610 west of the city. Allow twenty five to thirty minutes."),
                 ("Parking and arrival",
                  "Free parking on site at Ormonde Fields Golf Club. If it is your first <a href=\"1-1-lessons.html\">lesson</a>, get here ten minutes early so your coach can find out what you actually want from it before the clock starts."),
             ]},

            {"type": "prices", "kick": "Golf lesson prices",
             "h2": "How Much Do <em>Golf Lessons Cost Near Nottingham?</em>",
             "p": "There is no joining fee and no need to be a member. You pay for what you book.",
             "cards": _PRICES},

            {"type": "prose", "kick": "Choosing the right coaching",
             "h2": "Which Golf Lessons Should <em>Nottingham Golfers Book?</em>",
             "blocks": [
                 ("h3", "Complete Beginners"),
                 ("p", "<a href=\"beginner-coaching.html\">Beginner golf lessons</a> assume no experience whatsoever and we can lend you a set, so there is nothing to buy first. If the idea of a one to one still feels daunting, <a href=\"get-into-golf.html\">Get Into Golf</a> runs as a friendlier group format."),
                 ("h3", "Golfers Stuck on the Same Handicap"),
                 ("p", "The <a href=\"monthly-programme.html\">monthly programme</a> is built for this. One-off lessons tend to give you a good fortnight before old habits reassert themselves. Structured coaching with practice work between sessions is what moves a handicap and keeps it moved."),
                 ("h3", "Anyone Who Suspects Their Body Is the Limit"),
                 ("p", "If you cannot physically make a turn, coaching cannot give you one. <a href=\"tpi-screening.html\">TPI screening</a> tests how your body actually moves and connects each restriction to the swing characteristic it produces, then the <a href=\"golf-fitness.html\">golf fitness suite</a> is where you address it."),
                 ("h3", "Golfers Playing With the Wrong Clubs"),
                 ("p", "Custom fitting uses Trackman data to match shaft, loft, lie and gapping to your actual swing. You get a full written specification, and fittings are brand neutral, so you can buy from us or anywhere you like."),
                 ("h3", "Winter Golfers"),
                 ("p", "The <a href=\"trackman-simulator.html\">indoor simulator</a> and the covered floodlit <a href=\"trackman-range.html\">Trackman range</a> are the reason a lot of Nottingham golfers keep their game through the off season rather than starting again every April."),
             ], "alt": True},

            {"type": "areas", "kick": "Areas we serve in Nottinghamshire",
             "h2": "Which Areas of Nottinghamshire <em>Do You Cover?</em>",
             "p": "Golfers come to us from across west Nottinghamshire and the city. If you are within half an hour of Ripley, it is an easy trip.",
             "tags": [("Nottingham", None), ("Eastwood", None), ("Hucknall", None), ("Kimberley", None),
                      ("Nuthall", None), ("Watnall", None), ("Giltbrook", None), ("Bulwell", None),
                      ("Arnold", None), ("Beeston", None), ("Stapleford", None), ("Selston", None),
                      ("Annesley", None), ("Kirkby in Ashfield", None),
                      ("Ripley", "location.html"), ("Derby", "golf-lessons-derby.html")]},

            {"type": "rel", "kick": "Explore the academy",
             "h2": "What Else Is on Site <em>Near Nottingham?</em>",
             "links": [
                 ("trackman-teaching-bay.html", "Trackman Teaching Bay",
                  "A private, quiet bay with Trackman, video analysis, mirrors and training aids for one to one coaching.", "Teaching bay"),
                 ("trackman-range.html", "Trackman Driving Range",
                  "Covered floodlit bays with live ball and club data. Walk in any day from 7am to 8pm.", "Driving range"),
                 ("grass-range.html", "Grass Driving Range",
                  "Real turf, real divots and honest feedback on your strike through the drier months.", "Grass range"),
                 ("golf-fitness.html", "Golf Fitness Suite",
                  "TPI-informed mobility, strength and speed work built around the demands of the golf swing.", "Golf fitness"),
                 ("ladies-academy.html", "Ladies Academy",
                  "PGA coaching for women of all abilities, from complete beginners to established players.", "Ladies golf"),
                 ("golf-lessons-derby.html", "Golf Lessons Derby",
                  "Travelling from the other side? The same academy, fifteen minutes out of Derby.", "Derby"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Golf Lessons Nottingham - <em>FAQs.</em>",
             "qs": [
                 ("How far is Evolution Golf Academy from Nottingham?",
                  "About twenty minutes from the city centre on the A610 through Eastwood and Langley Mill. We are at Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RJ. From Kimberley, Nuthall or Eastwood it is often under fifteen minutes."),
                 ("What golf lessons are available near Nottingham?",
                  "<a href=\"1-1-lessons.html\">1:1 PGA lessons</a>, a <a href=\"monthly-programme.html\">monthly coaching programme</a>, <a href=\"beginner-coaching.html\">beginner coaching</a>, <a href=\"get-into-golf.html\">Get Into Golf</a>, the <a href=\"junior-academy.html\">junior academy</a> for ages six to sixteen, <a href=\"ladies-academy.html\">ladies coaching</a>, <a href=\"tpi-screening.html\">TPI screening</a> and custom club fitting."),
                 ("How much do golf lessons cost near Nottingham?",
                  "A 1:1 lesson with an Advanced PGA Professional is £55 for sixty minutes, the monthly programme is £60 per month and TPI screening is £75. Range baskets start from £4 and simulator bays are £25 an hour, both with club hire included. You do not need to be a member. Call 07710 582036 to confirm current prices."),
                 ("Is there a Trackman range near Nottingham?",
                  "Yes. Our <a href=\"trackman-range.html\">Trackman driving range</a> is a short run out on the A610 and is open every day from 7am to 8pm. The bays are covered and floodlit, so it runs identically in December and June, and the range is walk-in with no booking needed."),
                 ("How do I book golf lessons from Nottingham?",
                  "Book online through our booking system or call 07710 582036. Lessons run seven days a week from 7am to 8pm, so early mornings before work and evenings after it are both available. You can also use the <a href=\"contact.html\">contact form</a> if you would rather describe what you are after first."),
                 ("Can I play indoor golf near Nottingham in winter?",
                  "Yes, and it is one of the main reasons Nottingham golfers come here between November and March. The <a href=\"trackman-simulator.html\">Trackman simulator</a> lets you play full rounds on championship courses indoors, and the covered floodlit range means normal practice carries on regardless of weather."),
                 ("Do you coach beginners from Nottingham?",
                  "Every week. <a href=\"beginner-coaching.html\">Beginner golf lessons</a> assume no prior experience and we can lend you a set, so you can turn up with nothing. Nobody is going to make you feel awkward about starting from zero."),
                 ("Do you offer junior golf coaching near Nottingham?",
                  "Yes. Will Painter, Advanced PGA Professional, leads the <a href=\"junior-academy.html\">junior academy</a> for ages six to sixteen, with individual lessons and group sessions. Structured junior coaching with launch monitor data is uncommon, which is why families travel for it."),
                 ("Is there parking at the golf academy?",
                  "Yes, free parking on site at Ormonde Fields Golf Club. No permits, no charges and no walk from a car park, which is a reasonable part of why the trip out of Nottingham is less painful than it sounds."),
             ], "alt": True},
        ],
    },

    # ================================================== FAQ HUB
    {
        "file": "faqs.html",
        "cur": "faqs.html",
        "title": "Golf Lessons FAQ Derby &amp; Nottingham | Evolution Golf Academy",
        "desc": "Answers on golf lesson prices, booking, the Trackman range, indoor simulator, custom fitting and TPI screening at Evolution Golf Academy near Derby and Nottingham.",
        "visit_kick": "Golf academy near Derby &amp; Nottingham",
        "cta": ("Still not sure? <em>Just ask.</em>",
                "Call 07710 582036 or send a message. We answer within a working day, seven days a week."),
        "hero": {
            "kick": "Golf Lessons in Derby &amp; Nottingham - Frequently Asked Questions",
            "l1": "Your", "l2": "Questions.",
            "p": "Everything golfers ask before booking <strong>golf lessons near Derby and Nottingham</strong> - prices, booking, the Trackman range, the indoor simulator, custom club fitting and TPI screening. If your question is not here, call 07710 582036.",
            "img": "bay_night",
            "alt": "Golf lessons FAQ at Evolution Golf Academy near Derby and Nottingham",
        },
        "marq": ["Golf Lesson Prices", "Trackman Range Questions", "Golf Academy Derby",
                 "Booking a Golf Lesson", "Custom Club Fitting", "Golf Academy Nottingham"],
        "sections": [
            {"type": "prose", "kick": "Before you book",
             "h2": "Common Questions About <em>Golf at Our Academy.</em>",
             "blocks": [
                 ("p", "Evolution Golf Academy is an Advanced PGA Professional coaching facility at Ormonde Fields Golf Club in Codnor, Ripley, fifteen minutes from Derby and twenty from Nottingham on the A610. We are open 7am to 8pm every day of the year, with free parking on site, and you do not need to be a member to book anything."),
                 ("p", "The questions below are the ones we get asked most often. If you would rather just talk to somebody, call <strong>07710 582036</strong> or use the <a href=\"contact.html\">contact form</a> and we answer within a working day."),
             ]},

            {"type": "faq", "kick": "Location", "alt": True,
             "h2": "Location &amp; Getting to <em>the Academy.</em>",
             "qs": [
                 ("Where is Evolution Golf Academy?",
                  "Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley, Derbyshire DE5 9RJ. We sit on the A610 between Derby and Nottingham, with free parking on site. Full directions are on the <a href=\"location.html\">location page</a>."),
                 ("How far is the academy from Derby city centre?",
                  "Around fifteen minutes by car via the A610, and often quicker than crossing Derby itself at rush hour. See our <a href=\"golf-lessons-derby.html\">golf lessons in Derby</a> page for route-by-route directions."),
                 ("How far is the academy from Nottingham?",
                  "About twenty minutes from the city centre on the A610 through Eastwood. From Kimberley, Nuthall or Eastwood it is often under fifteen. See <a href=\"golf-lessons-nottingham.html\">golf lessons in Nottingham</a> for directions."),
                 ("Is there parking at the golf academy?",
                  "Yes, free parking on site. No permits, no charges and no walk from an overflow car park."),
                 ("What are your opening hours?",
                  "7am to 8pm, seven days a week, with no regular closing day. The range bays are floodlit, so the late slots work through the winter as well as the summer."),
                 ("Can I get there by public transport?",
                  "Buses run along the A610 corridor between Ripley, Codnor and both cities, but services vary and the academy is easiest to reach by car. Call 07710 582036 if you need to check the nearest stop before travelling."),
             ]},

            {"type": "faq", "kick": "Prices and booking",
             "h2": "Golf Lesson Prices &amp; <em>Booking.</em>",
             "qs": [
                 ("How much do golf lessons cost?",
                  "A 1:1 lesson with an Advanced PGA Professional is £55 for sixty minutes. The <a href=\"monthly-programme.html\">monthly coaching programme</a> is £60 per month, and <a href=\"tpi-screening.html\">TPI movement screening</a> is £75 per session. There is no joining fee, and you do not need to be a member to book."),
                 ("How much does the driving range cost?",
                  "Baskets start from £4 for a small basket, with larger baskets better value for longer sessions. Private bay hire is £15 an hour and the <a href=\"trackman-simulator.html\">simulator</a> is £25 an hour."),
                 ("Do I need to book a golf lesson in advance?",
                  "Yes. Lessons, simulator bays, private teaching bays and custom fitting sessions all need booking. The <a href=\"trackman-range.html\">Trackman driving range</a> is the exception - that is walk-in on a first-come basis."),
                 ("How do I book?",
                  "Book online through our booking system, call 07710 582036, or send a message through the <a href=\"contact.html\">contact page</a>. We answer within a working day."),
                 ("Can I buy a golf lesson as a gift?",
                  "Call 07710 582036 to arrange it. A single lesson or a block of coaching both work well as gifts, and a <a href=\"get-into-golf.html\">Get Into Golf</a> session is a gentler present for somebody who has never played."),
                 ("What happens if I need to cancel?",
                  "Let us know as far ahead as you reasonably can on 07710 582036 and we will move the session. Late cancellations are harder to reschedule because that coach's slot has usually gone."),
                 ("Do I need to be a member?",
                  "No. Anyone can book golf lessons, the range or the simulators, and everything here is open to the public. Membership does exist and it gives you priority booking and better rates, but it is never a condition of booking. Most golfers simply pay for the lessons, range time or fitting they want and nothing else."),
             ]},

            {"type": "faq", "kick": "Coaching", "alt": True,
             "h2": "Coaching &amp; <em>Getting Started.</em>",
             "qs": [
                 ("Do I need experience to have a golf lesson?",
                  "No. We coach complete beginners every week. <a href=\"beginner-coaching.html\">Beginner golf lessons</a> assume no prior knowledge at all, and if a one to one feels like too much to start with, <a href=\"get-into-golf.html\">Get Into Golf</a> runs as a friendlier group format."),
                 ("Do I need my own golf clubs?",
                  "Not for your first session. We can lend you a set for lessons, and club hire on the range and simulators is included at no extra cost. Once you are playing regularly it is worth getting your own, and a brand neutral custom fitting will make sure you buy clubs that suit your swing rather than guessing in a shop."),
                 ("Which PGA coach will I have?",
                  "Will Painter, Advanced PGA Professional. He leads the coaching here, including the junior academy and the ladies academy, so the same coach sees your swing every session. Tell us your goal and the session is built around it rather than handed to somebody else. See <a href=\"meet-team.html\">meet the team</a> for his full background."),
                 ("What is the monthly coaching programme?",
                  "Structured, ongoing coaching at £60 per month, with a plan to follow between sessions. It suits golfers who want steady improvement rather than occasional one-off lessons that fade after a fortnight. Details on the <a href=\"monthly-programme.html\">monthly programme</a> page."),
                 ("Do you offer junior golf lessons?",
                  "Yes. Will Painter, Advanced PGA Professional, leads the <a href=\"junior-academy.html\">junior academy</a> for ages six to sixteen, with both individual lessons and group sessions."),
                 ("Do you offer ladies golf lessons?",
                  "Yes. <a href=\"ladies-academy.html\">Ladies coaching</a> covers all abilities including complete beginners. We are a coaching academy, not a members' club, so there is no dress code to work out and no clubhouse politics."),
                 ("How long does it take to learn golf?",
                  "You can hit a ball reasonably within a handful of sessions. Getting round a course comfortably usually takes a few months of regular coaching and practice. The honest answer is that it depends far more on how often you practise than on natural ability."),
             ]},

            {"type": "faq", "kick": "Facilities",
             "h2": "Trackman Range, Simulator &amp; <em>Facilities.</em>",
             "qs": [
                 ("Do I need to book the Trackman range?",
                  "No. The <a href=\"trackman-range.html\">Trackman driving range</a> is walk-in on a first-come basis, every day from 7am to 8pm. Only private teaching bays need booking."),
                 ("What is Trackman and what does it measure?",
                  "Trackman is the dual-radar launch monitor used on the PGA Tour. It measures ball speed, club head speed, launch angle, spin rate, carry distance, total distance, shot shape, club path and face angle, displayed live in your bay within about a second of impact."),
                 ("How do I book the golf simulator?",
                  "<a href=\"trackman-simulator.html\">Simulator bays</a> are booked in advance at £25 an hour, either online or by calling 07710 582036. A group can get a full round done in a fraction of the time it takes on a real course."),
                 ("Is the range open in winter?",
                  "Yes. Every bay is covered and floodlit, so the range runs exactly the same in December as it does in June. This is the main reason golfers from both cities practise here through the off season."),
                 ("Is there an outdoor grass range?",
                  "Yes. The <a href=\"grass-range.html\">grass driving range</a> runs through the drier months for golfers who want real turf interaction and honest feedback on their strike. The covered bays are the all-year option."),
                 ("Is there somewhere to practise chipping and putting?",
                  "Yes. The <a href=\"short-game.html\">short game area</a> covers chipping, pitching, bunker play and putting, which is where most amateur golfers save strokes fastest."),
                 ("What is the golf fitness suite?",
                  "A training space for the mobility, strength and speed work that supports the golf swing, guided by TPI screening rather than a generic gym programme. See the <a href=\"golf-fitness.html\">golf fitness suite</a> page."),
             ]},

            {"type": "faq", "kick": "Fitting and screening", "alt": True,
             "h2": "Custom Fitting &amp; <em>TPI Screening.</em>",
             "qs": [
                 ("Who carries out custom club fitting?",
                  "Our fitters, working on Trackman data alongside the coaching, so a fitting accounts for both your current swing and how it is likely to change as you improve. Fittings are brand neutral, so you can buy from us or anywhere you like."),
                 ("Do I have to buy clubs from you after a fitting?",
                  "No. You receive a full written specification and can take it to any retailer or manufacturer you like. The point is that you end up with the right clubs, not that you buy them here."),
                 ("How long does a club fitting take?",
                  "A full bag fitting typically runs ninety minutes to two hours. A single club fitting, driver only or irons only, is usually about sixty minutes."),
                 ("What is TPI screening?",
                  "<a href=\"tpi-screening.html\">TPI screening</a> is a Titleist Performance Institute movement assessment. It tests how your body actually moves and links each limitation to the swing characteristic it tends to cause, then gives you a prioritised exercise plan."),
                 ("Do I need TPI screening or a golf lesson first?",
                  "For most golfers a lesson first is fine. Screening becomes worth doing when a coach keeps asking for a position you physically cannot reach, or if you pick up recurring back, elbow or wrist niggles from playing."),
                 ("Is custom fitting worth it for a high handicapper?",
                  "Often more than for a low handicapper. Better players adapt to poor equipment; higher handicappers tend to build compensations around it. Getting lie angle and shaft flex right removes a variable you would otherwise be fighting every round."),
             ]},

            {"type": "rel", "kick": "Where to next",
             "h2": "Popular Pages on <em>the Site.</em>",
             "links": [
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes with an Advanced PGA Professional, Trackman data and video analysis throughout.", "Golf lessons"),
                 ("trackman-range.html", "Trackman Driving Range",
                  "Covered floodlit bays, live ball data, walk in seven days a week from £4.", "Driving range"),
                 ("beginner-coaching.html", "Beginner Coaching",
                  "No experience needed and we can lend you a set. The standard starting point for new golfers.", "Beginners"),
                 ("golf-lessons-derby.html", "Golf Lessons Derby",
                  "Directions, prices and coaching options for golfers travelling from Derby.", "Derby"),
                 ("golf-lessons-nottingham.html", "Golf Lessons Nottingham",
                  "Directions, prices and coaching options for golfers travelling from Nottingham.", "Nottingham"),
                 ("contact.html", "Contact &amp; Booking",
                  "Send a message or call 07710 582036. We answer within a working day, seven days a week.", "Get in touch"),
             ]},
        ],
    },
]

# Derby and Nottingham now come from the location CMS template in
# content_locations.py, so this module only owns the FAQ hub.
PAGES = [p for p in PAGES if p["file"] == "faqs.html"]
