"""EXEMPLAR PAGE - the pattern every other page must follow.

Target: 1200+ words of unique body copy, 10+ contextual internal links
with keyword-rich anchor text, 8+ H2s phrased as real search queries.
"""

PAGES = [{
    "file": "trackman-range.html",
    "cur": "trackman-range.html",
    "title": "Trackman Driving Range Derby &amp; Nottingham | Covered Floodlit Bays | Evolution Golf Academy",
    "desc": "Trackman driving range near Derby and Nottingham. Covered floodlit bays with ball speed, carry, spin and shot shape on every shot. Walk in, no booking, open 7am to 8pm daily.",
    "visit_kick": "Trackman driving range near Derby &amp; Nottingham",
    "cta": ("Practise with <em>real numbers.</em>",
            "The Trackman driving range is walk-in, seven days a week, 7am to 8pm. Fifteen minutes from Derby, twenty five from Nottingham. Baskets from £4.00."),
    "hero": {
        "kick": "Trackman Driving Range in Derby &amp; Nottingham",
        "l1": "Trackman", "l2": "Range.",
        "p": "The <strong>Trackman driving range</strong> at Evolution Golf Academy gives golfers from Derby, Nottingham and across Derbyshire tour-level ball data on every single shot. Covered, floodlit bays mean you can practise all year round, and you never need to book.",
        "img": "range_night",
        "alt": "Trackman driving range near Derby and Nottingham at Evolution Golf Academy",
    },
    "marq": ["Trackman Driving Range Derby", "Driving Range Nottingham", "Ball Speed &amp; Carry Data",
             "Covered Floodlit Bays", "Open 7 Days a Week", "Golf Practice Derbyshire"],
    "sections": [
        {"type": "prose", "kick": "Trackman range near Derby &amp; Nottingham",
         "h2": "What Is a Trackman <em>Driving Range?</em>",
         "blocks": [
             ("p", "A <strong>Trackman driving range</strong> is a driving range where every bay is fitted with Trackman dual-radar tracking, the same launch monitor technology used on the PGA Tour and by the majority of the world's leading coaches. Instead of hitting a bucket of balls into a field and squinting to see roughly where they finished, you get a precise set of numbers for every shot you hit, displayed on a screen in front of you within about a second of impact."),
             ("p", "That difference matters more than most golfers expect. On a conventional range near Derby or Nottingham you are effectively practising blind. You might think you flushed a seven iron, but you have no idea whether it carried 145 yards or 158, whether the spin was 5,200rpm or 8,400, or whether that slight fade was two yards of shape or twelve. Without that information you cannot tell whether the change you just made to your grip actually helped."),
             ("h3", "What Does Trackman Measure on Every Shot?"),
             ("p", "Trackman tracks both the club and the ball through impact and reports the full picture. The headline numbers most golfers care about are <strong>ball speed, club head speed, smash factor, launch angle, spin rate, carry distance, total distance, shot shape and landing angle</strong>. Beyond those, it reports club path, face angle, attack angle and dynamic loft, which is the data your <a href=\"1-1-lessons.html\">PGA golf coach</a> will use in a lesson to explain precisely why the ball is doing what it is doing."),
             ("p", "For a golfer practising alone, the two most useful numbers are usually carry distance and dispersion. Knowing that your eight iron carries 142 yards rather than the 155 you have been telling your playing partners for years is the single fastest way to stop coming up short of greens."),
             ("h3", "Is a Trackman Range Better Than a Normal Driving Range?"),
             ("p", "For practice that actually transfers to your scorecard, yes. A standard range gives you repetition. A Trackman range gives you repetition plus feedback, and feedback is what turns repetition into improvement. You find out immediately whether a swing thought is working, rather than believing it worked because one shot out of ten felt good."),
             ("p", "It also removes a very common problem: golfers grooving a fault. Without data it is entirely possible to spend a winter hitting two hundred balls a week and get worse, because you are reinforcing the same compensation every time. Numbers catch that early."),
         ]},

        {"type": "prose", "kick": "Spacious bays, relaxed atmosphere",
         "h2": "What Makes the Trackman Range at Evolution Golf Academy <em>Different?</em>",
         "blocks": [
             ("p", "Come experience a Trackman range with tour proven technology in a relaxed environment with our spacious bays for you to play, practice and play games. With our floodlight you can practice all year round."),
             ("p", "At Evolution Golf Academy, we've combined world-leading TrackMan technology with a spacious, welcoming environment. Our wide bays and relaxed atmosphere create a driving range where you can enjoy your golf without the noise."),
             ("h3", "What Is a Session on the Trackman Range Actually Like?"),
             ("p", "Practice with purpose. Play with friends. Enjoy the experience. Every shot is tracked in real time, providing instant feedback on distances, accuracy and ball flight, while interactive games, virtual golf courses and practice modes make every visit engaging for golfers of all ages and abilities."),
             ("p", "That mix is deliberate. A serious golfer can spend an hour on gapping and dispersion in one bay while a family two bays along works through a closest-to-the-pin game, and neither gets in the other's way. Seven bays, all floodlit, all Trackman-equipped, fifteen minutes from Derby city centre and twenty five minutes from Nottingham on the A610."),
             ("p", "Club hire is included at no extra cost, so nobody needs to buy equipment before finding out whether they enjoy it. If you would rather have someone show you what the numbers mean, a <a href=\"1-1-lessons.html\">1:1 golf lesson</a> in the <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a> is the next step."),
         ], "alt": True},

        {"type": "cards", "kick": "What you get in every bay",
         "h2": "What Does the Trackman Range at Our <em>Derbyshire Academy</em> Include?",
         "p": "Every bay on the range is Trackman-equipped, covered and floodlit, so the experience is the same in July as it is in January.",
         "cards": [
             {"img": "launch_data", "alt": "Trackman launch data numbers displayed on screen at the range",
              "h": "Live Data on Every Shot",
              "p": "Ball speed, club speed, launch angle, spin rate, carry, total distance and shot shape, measured and displayed the moment the ball leaves the face. No guesswork, no wondering."},
             {"img": "range_night", "alt": "Covered floodlit driving range bays in Derbyshire",
              "h": "Covered and Floodlit",
              "p": "Rain, wind or a dark February evening makes no difference. The bays are covered and floodlit, so practice carries on right through the winter when most golfers stop."},
             {"img": "bay_night", "alt": "Trackman practice games and challenges at the driving range",
              "h": "Practice Games and Challenges",
              "p": "Trackman's built-in games turn an aimless bucket of balls into targeted practice. Compete against yourself, against friends, or against golfers on the same challenges worldwide."},
             {"img": "student_swing", "alt": "Golfer using the walk-in Trackman driving range near Derby",
              "h": "Walk In, No Booking",
              "p": "The range runs first come, first served. No app, no membership, no phone call needed. Turn up, pick up a basket and hit balls."},
         ]},

        {"type": "accred", "kick": "Accredited and certified",
         "h2": "Who Accredits the <em>Trackman Range?</em>",
         "p": "The technology and the coaching behind it are both certified rather than self-declared.",
         "items": [
             ("Trackman", "Official Performance Centre", "Radar-tracked range and sim suites"),
             ("PGA", "PGA Qualified Coaches", "Members of The Professional Golfers' Association"),
             ("TPI", "Titleist Performance Institute", "Movement and biomechanics specialists"),
         ], "alt": True},

        {"type": "split", "img": "over_shoulder",
         "img_alt": "PGA coach reviewing Trackman data with a golfer near Derby",
         "kick": "Why golfers travel here to practise",
         "h2": "Why Practise at a Trackman Range <em>Near Derby?</em>",
         "paras": [
             "Most range sessions are wasted because the golfer cannot tell what actually changed. A <strong>Trackman range</strong> removes that problem entirely. You get a number against every swing, so you know within one shot whether an adjustment helped or hurt.",
             "It also makes practice measurable over months rather than minutes. Golfers who practise here regularly can look back and see clubhead speed climbing or dispersion tightening, which is far more motivating than a vague sense that things might be going alright.",
         ],
         "ticks": [
             "<b>Real numbers, not guesswork</b> - know exactly how far every club carries",
             "<b>Practise all year</b> - covered and floodlit, 7am to 8pm every single day",
             "<b>Track progress over months</b> - compare today's session to last winter's",
             "<b>PGA coaches on site</b> - turn a practice session into a <a href=\"1-1-lessons.html\">golf lesson</a> whenever you want",
             "<b>Fifteen minutes from Derby</b> and twenty five from Nottingham on the A610",
         ],
         "btn2": ("See golf lessons", "1-1-lessons.html")},

        {"type": "steps", "kick": "How to use the range", "alt": True,
         "h2": "How Do I Use the <em>Trackman Driving Range?</em>",
         "p": "There is nothing complicated about it, and you do not need to know anything about launch monitors before you arrive.",
         "steps": [
             ("Turn up, no booking needed",
              "The range is walk-in every day from 7am to 8pm. Park on site for free at Ormonde Fields Golf Club and come to the range. Bays are first come, first served."),
             ("Pick up a basket",
              "Baskets run from £4.00 for 30 balls up to £12.50 for 120 balls. The bigger baskets work out cheaper per ball, so if you are planning a full session the 90 or 120 is the sensible buy."),
             ("Take any free bay",
              "Every bay is Trackman-equipped, so there is no better or worse bay to aim for. The screen switches on and starts tracking as soon as you begin hitting."),
             ("Hit shots and read the numbers",
              "Your data appears shot by shot. If you are new to it, ignore everything except carry distance to begin with and build up from there."),
             ("Add a coach when you want one",
              "If the numbers raise a question you cannot answer, book a session in the <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a> with a PGA Professional and get it explained."),
         ]},

        {"type": "ptable", "kick": "Range basket prices",
         "h2": "How Much Does the Trackman Driving Range <em>Cost?</em>",
         "p": "Pay for the balls, use the Trackman bay for nothing. No booking required, seven days a week, and club hire is included at no extra cost if you have arrived without a set.",
         "rows": [
             ("30 balls", "£4.00"),
             ("60 balls", "£7.50"),
             ("90 balls", "£10.00"),
             ("120 balls", "£12.50"),
             ("Private Trackman range bay", "£15.00 per hour"),
         ]},

        {"type": "prose", "kick": "Getting the most from a session",
         "h2": "How Should You Practise on a <em>Trackman Range?</em>",
         "blocks": [
             ("h3", "Know Your Carry Distances First"),
             ("p", "Before working on technique, spend one session simply establishing how far each club actually carries. Hit ten shots with each iron, discard the two worst, and take the average carry. Most golfers discover they are between one and two clubs shorter than they believed, which explains an awful lot of shots that finish in the front bunker."),
             ("h3", "Practise With a Target, Not Just a Direction"),
             ("p", "Pick a specific yardage for each shot rather than hitting into open space. Trackman tells you the carry, so you can score yourself honestly. Ten shots to a 140 yard target with a scoring system is worth an hour of aimless ball-beating."),
             ("h3", "Mix Random Practice Into Your Session"),
             ("p", "Hitting thirty seven irons in a row is comfortable and mostly useless, because golf never asks you to do that. Change club every shot for part of your session and you will practise the thing the course actually tests, which is producing a good strike first time with a club you have not just warmed up with."),
             ("h3", "Do Not Chase Every Number at Once"),
             ("p", "Trackman reports a lot of data and it is easy to get overwhelmed. Pick one metric to work on per session. If you are fighting a slice, watch club path and face angle and ignore everything else. If you want more distance, watch smash factor before you worry about clubhead speed, because striking the middle of the face is worth more than swinging harder."),
             ("p", "If you would rather have someone structure that for you, our coaches build practice plans as part of the <a href=\"monthly-programme.html\">monthly coaching programme</a>, so you arrive at the range knowing exactly what you are working on."),
         ], "alt": True},

        {"type": "stats", "items": [("1", "PGA Pro"), ("2+", "Trackman Simulators"), ("7", "Trackman Range Bays")]},

        {"type": "tgrid", "kick": "What golfers say", "alt": True,
         "h2": "What Do Golfers Say About the <em>Trackman Range?</em>",
         "p": "Reviews left by golfers who practise here, unedited.",
         "items": [
             ("The practice facilities here are second to none. I couldn't of been more impressed, the grass range is an amazing touch and the track man bays are top notch as well, mats are perfect not worn, balls aren't battered, great value for money, definitely my go to practice facility now.", "Ciaran W."),
             ("Great range, balls are in very good nick, Trackman too, plus a nice little chipping area.", "Steve G."),
             ("Great place to start your golfing journey. The Trackman facilities are excellent.", "Lisa H."),
         ]},

        {"type": "rel", "kick": "Explore the academy",
         "h2": "What Else Is at Our <em>Golf Academy?</em>",
         "p": "The Trackman range is one part of the site. Everything below is on the same premises in Codnor, Ripley.",
         "links": [
             ("trackman-teaching-bay.html", "Trackman Teaching Bay",
              "A private, distraction-free bay with Trackman, video analysis and training aids, used for one to one coaching.", "Teaching bay"),
             ("trackman-simulator.html", "Trackman Simulator",
              "Play world-famous courses indoors on Trackman, or use it as a practice tool when the weather closes in.", "Golf simulator"),
             ("grass-range.html", "Grass Driving Range",
              "Hit off real turf and get honest feedback on your strike and low point, the way the course tests it.", "Grass range"),
             ("short-game.html", "Short Game Area",
              "Chipping, pitching, bunker play and putting - where most amateur golfers save the quickest strokes.", "Short game"),
             ("1-1-lessons.html", "1:1 Golf Lessons",
              "Sixty minutes with a PGA Professional using the same Trackman data you see on the range.", "Golf lessons"),
             ("golf-fitness.html", "Golf Fitness Suite",
              "TPI-informed mobility, strength and speed work built around the demands of the golf swing.", "Golf fitness"),
         ]},

        {"type": "faq", "kick": "Common questions",
         "h2": "Trackman Driving Range Derby &amp; Nottingham - <em>FAQs.</em>",
         "qs": [
             ("Do I need to book the Trackman driving range?",
              "No. The Trackman range is walk-in and runs on a first-come basis, every day from 7am to 8pm. Only the private teaching bays, <a href=\"trackman-simulator.html\">simulator bays</a> and custom fitting sessions need booking in advance."),
             ("How much does the Trackman driving range cost near Derby?",
              "Baskets are £4.00 for 30 balls, £7.50 for 60, £10.00 for 90 and £12.50 for 120, and there is no charge on top for the Trackman bay itself. A private Trackman range bay with ball data, club data and video analysis is £15 per hour. Call 07710 582036 to confirm current prices before you travel."),
             ("What does Trackman actually measure?",
              "Ball speed, club head speed, smash factor, launch angle, spin rate, carry distance, total distance, shot shape and landing angle, plus club path, face angle and attack angle. Everything is displayed live in your bay."),
             ("Is the driving range open in winter?",
              "Yes. All bays are covered and floodlit, so the range runs identically in December to how it runs in June - 7am to 8pm, seven days a week. This is the main reason golfers from Derby and Nottingham practise here through the off season."),
             ("How far is the Trackman range from Derby and Nottingham?",
              "We are at Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RJ. That is roughly 15 minutes from Derby city centre and 25 minutes from Nottingham, both on the A610, with free parking on site. See our <a href=\"golf-lessons-derby.html\">golf lessons in Derby</a> and <a href=\"golf-lessons-nottingham.html\">golf lessons in Nottingham</a> pages for directions."),
             ("Do I need my own golf clubs to use the range?",
              "Clubs are available if you do not have your own, which makes the range a reasonable place to try golf for the first time. If you are completely new, <a href=\"get-into-golf.html\">Get Into Golf</a> is a gentler starting point than turning up cold."),
             ("Can beginners use the Trackman range?",
              "Absolutely. The data is there if you want it and ignorable if you do not. Plenty of beginners use the range purely to hit balls and only start reading the numbers once they have had a few <a href=\"beginner-coaching.html\">beginner golf lessons</a>."),
             ("Can I have a golf lesson on the Trackman range?",
              "Yes. Lessons normally run in the private <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a>, which is quieter and set up with video and training aids, but coaching can take place on the main range where that suits the work better."),
             ("Is there an outdoor grass range as well?",
              "Yes. The <a href=\"grass-range.html\">grass driving range</a> runs through the drier months for golfers who want real turf interaction. The covered Trackman bays are the year-round option."),
         ], "alt": True},
    ],
}]
