"""CORE PAGES - index, about, location, meet-team, contact.

Data only. All markup lives in components.py.
"""

PAGES = [

    # ================================================================ INDEX
    {
        "file": "index.html",
        "cur": None,
        "title": "Golf Academy Derby &amp; Nottingham | Trackman &amp; PGA Coaching | Evolution Golf Academy",
        "desc": "Golf academy near Derby and Nottingham at Ormonde Fields, Ripley. Trackman range, simulators, Advanced PGA Professional coaching, custom fitting and TPI screening. Open 7am to 8pm, 7 days.",
        "visit_kick": "Golf academy near Derby &amp; Nottingham",
        "cta": ("Start playing <em>better golf.</em>",
                "Advanced PGA Professional coaching, seven Trackman range bays, indoor simulators and a full short game area. Fifteen minutes from Derby, twenty from Nottingham, open 7am to 8pm every day."),
        "hero": {
            "kick": "Golf Academy Derby &amp; Nottingham",
            "l1": "Practice. Learn.", "l2": "Play.",
            "p": "Evolution Golf Academy is a <strong>golf academy near Derby and Nottingham</strong> built around Trackman data, Advanced PGA Professional coaching and a site you can use seven days a week. Seven covered range bays, indoor simulators, a short game area and a golf fitness suite, all at Ormonde Fields in Codnor, Ripley.",
            "img": "bay_night",
            "alt": "Golf academy near Derby and Nottingham - floodlit Trackman bay at Evolution Golf Academy",
        },
        "marq": ["Golf Academy Derby", "Golf Lessons Nottingham", "Trackman Performance Centre",
                 "PGA Professional Coaching", "Open 7 Days a Week", "Ripley, Derbyshire"],
        "sections": [

            {"type": "prose", "kick": "A golf academy for Derby, Nottingham and Derbyshire",
             "h2": "What Is a Golf Academy and How Is It Different From a <em>Golf Club?</em>",
             "blocks": [
                 ("p", "A golf club sells you access to a course. A <strong>golf academy sells you improvement</strong>. Evolution Golf Academy sits on the grounds of Ormonde Fields Golf Club on Nottingham Road in Codnor, Ripley, and everything on the site exists for a single purpose: to send you home a better golfer than you arrived. Everything here is open to the public, so you do not need to be a member to book anything. Membership exists if you want it, and it gives you priority booking and better rates, but nothing on the site is locked behind it."),
                 ("p", "That matters around Derby and Nottingham because serious coaching and serious practice technology have traditionally been locked behind private clubs. If you wanted <a href=\"1-1-lessons.html\">one to one golf lessons</a> with an Advanced PGA Professional and a launch monitor pointed at your swing, you generally had to know somebody, join something, or drive for the best part of an hour. We built this academy so that the drive is fifteen minutes from Derby and twenty from Nottingham, the parking is free, and the answer to \"can I come tomorrow\" is usually yes."),
                 ("h3", "Who Is the Golf Academy For?"),
                 ("p", "This <strong>golf academy in Derbyshire</strong> is for complete beginners who have never held a club. Children aged six to sixteen in the <a href=\"junior-academy.html\">junior academy</a>. Women starting out or coming back through the <a href=\"ladies-academy.html\">ladies academy</a>. Mid handicappers who have shot the same score for three seasons and cannot work out why. Single figure players chasing the last two shots before a club championship. The facilities are identical for all of them. What changes is what the coach does with them once you are in the bay."),
                 ("h3", "What Is Actually on the Site?"),
                 ("p", "Seven Trackman-equipped bays on the <a href=\"trackman-range.html\">Trackman driving range</a>, two or more indoor <a href=\"trackman-simulator.html\">golf simulators</a>, a private <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a> for lessons and video analysis, a <a href=\"grass-range.html\">grass driving range</a> for the drier months, a <a href=\"short-game.html\">short game area</a> covering chipping, pitching, bunker play and putting, and a <a href=\"golf-fitness.html\">golf fitness suite</a> for mobility, strength and speed work. Custom club fitting runs on Trackman data and our fittings are brand neutral, so you can buy from us or anywhere you like."),
                 ("h3", "Do I Need to Be Any Good Before I Come?"),
                 ("p", "No, and the most common thing we hear from first-time callers on 07710 582036 is that they want to get a bit better before they book a lesson. That is roughly equivalent to tidying the house before the cleaner arrives. <a href=\"get-into-golf.html\">Get Into Golf</a> and structured <a href=\"beginner-coaching.html\">beginner coaching</a> exist precisely for golfers who feel that way, and nobody here has ever raised an eyebrow at a bad swing. We have all made them. You do not need your own clubs either: we can lend you a set for lessons, and the range and simulators include club hire at no extra cost."),
                 ("ul", [
                     "Open to the public, with no membership needed to book anything",
                     "Membership is optional and adds priority booking and better rates",
                     "Club hire included at no extra cost on the range and simulators",
                     "Open 7am to 8pm, seven days a week, all year round",
                     "Free parking on site at Ormonde Fields Golf Club",
                     "Fifteen minutes from Derby, twenty from Nottingham on the A610",
                 ]),
             ]},

            {"type": "cards", "kick": "Where most golfers start",
             "h2": "What Are the Most Popular Things to Book at a <em>Derbyshire Golf Academy?</em>",
             "p": "Four starting points, depending on whether you want teaching, measured practice, weather-proof play or an honest look at what your body will let you do.",
             "cards": [
                 {"img": "beginner", "alt": "Beginner golf coaching near Derby and Nottingham",
                  "h": "Beginner Coaching",
                  "p": "Structured golf tuition for anyone starting from nothing or coming back after twenty years away. Grip, setup and a swing that repeats, taught in plain English with no jargon and no embarrassment.",
                  "href": "beginner-coaching.html", "cta": "Beginner coaching"},
                 {"img": "range_night", "alt": "Trackman driving range bays at night in Ripley, Derbyshire",
                  "h": "Trackman Driving Range",
                  "p": "Seven covered, floodlit bays reporting ball speed, carry, spin and shot shape on every shot. Walk in, no booking needed, baskets from £4, seven days a week.",
                  "href": "trackman-range.html", "cta": "Trackman range"},
                 {"img": "sim", "alt": "Indoor Trackman golf simulator near Derby and Nottingham",
                  "h": "Trackman Simulator",
                  "p": "Play famous courses indoors or practise with full launch monitor data when the weather turns. £25 an hour, and the busiest thing on site between November and February.",
                  "href": "trackman-simulator.html", "cta": "Golf simulator"},
                 {"img": "tpi", "alt": "TPI screening physical assessment at Evolution Golf Academy",
                  "h": "TPI Screening",
                  "p": "A £75 physical screen that separates the swing faults you can fix with technique from the ones your body is physically refusing to allow. The starting point for lasting change.",
                  "href": "tpi-screening.html", "cta": "TPI screening"},
             ]},

            {"type": "split", "img": "coach_feedback",
             "img_alt": "PGA golf coach reviewing Trackman data with a golfer near Nottingham",
             "kick": "Why golfers choose Evolution",
             "h2": "Why Choose a <em>Golf Academy</em> Over a One-Off Pro Shop Lesson?",
             "paras": [
                 "Most golfers in Derbyshire have had a lesson at some point. Far fewer have had a coaching relationship. The difference is whether anybody is measuring what happens between sessions, and whether the person teaching you has the equipment to prove a change worked rather than asking you how it felt.",
                 "We are a <strong>Trackman Official Performance Centre</strong> and coaching here is led by Will Painter, an Advanced PGA Professional. That combination means the same data follows you from a lesson in the teaching bay, to a solo practice session on the range, to a review six weeks later. Nothing gets misremembered, because nothing is being remembered. It is recorded, and you can see it.",
             ],
             "ticks": [
                 "<b>Advanced PGA Professional coaching</b> - meet Will on the <a href=\"meet-team.html\">coaching team page</a>",
                 "<b>Trackman Official Performance Centre</b> - the launch monitor used on tour",
                 "<b>TPI certified coaching</b> - <a href=\"tpi-screening.html\">physical screening</a> so the plan fits your body",
                 "<b>Open 7am to 8pm every day</b> - weekends, school holidays and right through winter",
                 "<b>Free parking, open to all</b> - <a href=\"location.html\">fifteen minutes from Derby</a> on the A610",
             ],
             "btn2": ("Meet the coaches", "meet-team.html"), "alt": True},

            {"type": "stats", "items": [("7", "Trackman Range Bays"), ("2+", "Golf Simulators"),
                                        ("7", "Days a Week")]},

            {"type": "prose", "kick": "How the coaching works",
             "h2": "What Makes Golf Coaching at This Academy <em>Different?</em>",
             "blocks": [
                 ("h3", "Data and Feel, Rather Than One or the Other"),
                 ("p", "There are coaches who will not look at a screen and coaches who will not look at you. Both are missing half the picture. Trackman tells us what the club and ball actually did, which stops a lesson turning into two people guessing. What it cannot tell us is what a change feels like in your hands, and that is the part that has to survive the drive home. Every session here uses both, and the numbers exist to settle the argument, not to run the lesson."),
                 ("h3", "Plain English, With the Jargon Left in the Bag"),
                 ("p", "Attack angle, dynamic loft and low point control are all real things, and none of them help a golfer who has come for an hour after work and wants to stop slicing. Will will happily go as deep into the technical detail as you want, and just as happily leave all of it out. If you finish a lesson unable to explain to your playing partner what you are working on, the lesson has not landed."),
                 ("h3", "A Practice Plan You Can Realistically Do"),
                 ("p", "A <strong>golf lesson</strong> without a practice plan is entertainment. Every golfer leaves knowing exactly what to hit, how many, and what a good outcome looks like when they next get to the <a href=\"trackman-range.html\">Trackman driving range</a>. If you want that structured across a season rather than an hour, the <a href=\"monthly-programme.html\">monthly coaching programme</a> at £60 a month builds it for you and adjusts it as you improve."),
                 ("h3", "The Same Coach, Session After Session"),
                 ("p", "Improvement is cumulative and coaching relationships take a few sessions to find their rhythm. You work with Will Painter, an Advanced PGA Professional, from your first enquiry onward, so nobody is re-reading your swing from scratch every time you arrive. What changes between sessions is not the person in the bay, it is what the session is aimed at, because the plan is matched to your goals rather than to whoever has a gap in the diary. You can read how Will works on the <a href=\"meet-team.html\">meet the team page</a> before you book your first <a href=\"1-1-lessons.html\">1:1 golf lesson</a> at £55."),
                 ("h3", "Equipment That Is Not Quietly Working Against You"),
                 ("p", "A surprising number of stubborn faults turn out to be a shaft that is too soft, a lie angle that is two degrees out, or a driver with more loft than the swing needs. Custom fitting here runs on Trackman numbers rather than a chart on the wall, and our fittings are brand neutral, so you can buy from us or anywhere you like. Because the fitting sits alongside the coaching, the specification accounts for where your swing is heading rather than only where it is today. <a href=\"contact.html\">Ask us about a fitting</a> if your clubs have never been checked."),
             ], "alt": True},

            {"type": "rel", "kick": "Explore the academy",
             "h2": "What Golf Coaching Is <em>Available Near Me?</em>",
             "p": "Every programme below runs at the same site in Codnor, Ripley, with the same coaches and the same Trackman technology.",
             "links": [
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes with an Advanced PGA Professional in the Trackman teaching bay. £55, and the fastest way to fix something specific.", "Golf lessons"),
                 ("monthly-programme.html", "Monthly Programme",
                  "£60 a month for continuous coaching, a rolling practice plan and progress tracked on Trackman across the season.", "Monthly coaching"),
                 ("junior-academy.html", "Junior Academy",
                  "Group coaching for ages six to sixteen, led by Will Painter, Advanced PGA Professional. Structured, patient and good fun.", "Junior golf"),
                 ("ladies-academy.html", "Ladies Academy",
                  "Women-only group coaching for beginners and improvers, with no pressure to already know what a hybrid is.", "Ladies golf"),
                 ("golf-lessons-derby.html", "Golf Lessons Derby",
                  "What the academy offers golfers travelling the fifteen minutes out of Derby, and how to get here.", "Derby lessons"),
                 ("golf-lessons-nottingham.html", "Golf Lessons Nottingham",
                  "Directions, timings and coaching options for golfers coming from Nottingham on the A610.", "Nottingham lessons"),
             ]},

            {"type": "tgrid", "kick": "Reviews",
             "h2": "What Do Golfers Say About Evolution <em>Golf Academy?</em>",
             "items": [
                 ("Great first lesson with Will. Felt very comfortable and definitely happy with the results.", "Kelsey"),
                 ("Another great lesson with Will today. Very knowledgeable talking through all the different strategies of chipping.", "Harry"),
                 ("After a comprehensive test of a variety of shafts and swing weights I now have complete confidence in my clubs.", "Lee"),
             ], "alt": True},

            {"type": "faq", "kick": "Common questions",
             "h2": "Golf Academy Derby &amp; Nottingham - <em>FAQs.</em>",
             "qs": [
                 ("Where is Evolution Golf Academy?",
                  "We are at Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL. That is roughly fifteen minutes from Derby city centre and twenty minutes from Nottingham, both straightforward runs on the A610, with free parking on site. Step by step driving directions from Derby, Nottingham, the M1 and the surrounding Derbyshire towns are on our <a href=\"location.html\">academy location page</a>."),
                 ("Do I need to be a member to use the golf academy?",
                  "No. Anyone can book golf lessons, the range or the simulators, and everything on the site is open to the public. Membership simply gives you priority booking and better rates, so it is worth asking about if you come every week, but nothing is withheld from anyone who is not a member. You can read more about how the academy is set up and why on our <a href=\"about.html\">about page</a>."),
                 ("How much do golf lessons cost near Derby and Nottingham?",
                  "A 1:1 golf lesson with an Advanced PGA Professional is £55. The <a href=\"monthly-programme.html\">monthly coaching programme</a> is £60 a month. TPI screening is £75. Range baskets start from £4, the simulator is £25 an hour and a private bay is £15 an hour. Prices are confirmed when you book, so ring 07710 582036 if you need current detail."),
                 ("What are your opening hours?",
                  "Seven in the morning until eight at night, seven days a week, including weekends and bank holidays. The range bays are covered and floodlit, so a Tuesday in January runs exactly like a Tuesday in July. That is the main reason golfers from across Derbyshire and Nottinghamshire keep practising here through the winter when everyone else stops."),
                 ("Can a complete beginner have golf lessons here?",
                  "Yes, and a large share of our week is beginners. If you have literally never swung a club, <a href=\"get-into-golf.html\">Get Into Golf</a> is the gentlest possible entry point. If you have played a bit and want to build something that holds up, <a href=\"beginner-coaching.html\">beginner coaching</a> is the better fit. We can lend you a set for lessons, and club hire is included at no extra cost on the range and simulators, so you do not need equipment to start."),
                 ("Who will coach me at the academy?",
                  "Will Painter, Advanced PGA Professional. He leads the coaching here, so the person watching your first swing is the same person watching it six months later. Around him sit TPI certified principles, Trackman expertise and fitness professionals in the golf fitness suite, which is why a session can address technique, equipment and physical limitation without handing you between strangers. His background and how he teaches are set out on the <a href=\"meet-team.html\">meet the team page</a>."),
                 ("Do you run coaching for juniors and for women?",
                  "Yes to both. The <a href=\"junior-academy.html\">junior academy</a> covers ages six to sixteen in structured group sessions led by Will Painter, Advanced PGA Professional, and the <a href=\"ladies-academy.html\">ladies academy</a> runs women-only groups for beginners and improvers. Both feed into individual coaching later if a player wants it, and both are popular with families from Ripley, Heanor and Belper."),
                 ("How do I book a lesson or ask a question?",
                  "Book online, which is the quickest route, or ring 07710 582036 during opening hours. If you would rather write it down, the enquiry form on our <a href=\"contact.html\">contact page</a> reaches the coaching team directly and we answer within a working day. There is also a longer list of answers on our <a href=\"faqs.html\">FAQs page</a>."),
             ]},
        ],
    },

    # ================================================================ ABOUT
    {
        "file": "about.html",
        "cur": "about.html",
        "title": "About Evolution Golf Academy, Ripley Derbyshire | Trackman &amp; PGA Coaching",
        "desc": "About Evolution Golf Academy in Ripley, Derbyshire. A Trackman Official Performance Centre with Advanced PGA Professional coaching, built so golfers near Derby and Nottingham get elite coaching without joining anything.",
        "visit_kick": "About our golf academy in Ripley, Derbyshire",
        "cta": ("Come and see the <em>academy.</em>",
                "Advanced PGA Professional coaching, seven Trackman bays, indoor simulators, a short game area and a fitness suite, all on one site in Codnor, Ripley. Open 7am to 8pm, seven days."),
        "hero": {
            "kick": "About Evolution Golf Academy, Ripley, Derbyshire",
            "l1": "About the", "l2": "Academy.",
            "p": "<strong>Evolution Golf Academy in Ripley, Derbyshire</strong> was built so that golfers near Derby and Nottingham could get elite coaching and Trackman technology without joining anything or driving for forty five minutes. Advanced PGA Professional coaching, one site, and no barrier to walking through the gate.",
            "img": "team",
            "alt": "The team at Evolution Golf Academy in Ripley, Derbyshire",
        },
        "marq": ["About Evolution Golf Academy", "Ripley, Derbyshire", "Trackman Official Performance Centre",
                 "Advanced PGA Professional", "TPI Certified", "Open To The Public"],
        "sections": [

            {"type": "prose", "kick": "Our story",
             "h2": "Why Was Evolution Golf Academy Set Up in <em>Ripley, Derbyshire?</em>",
             "blocks": [
                 ("p", "Evolution Golf Academy exists because of a gap that anyone who has tried to improve at golf in the East Midlands will recognise straight away. Elite coaching and serious practice technology were available, but almost always behind a private club membership, a joining fee and a committee, or else at the end of a forty five minute drive to somewhere that could fit you in three weeks on Tuesday afternoon. Golfers were being asked to choose between convenience and quality, and quality usually lost."),
                 ("p", "So we built a <strong>golf academy in Ripley, Derbyshire</strong> where the coaching is Advanced PGA Professional standard, the technology is Trackman, and neither of those depends on you joining anything. The academy sits at Ormonde Fields Golf Club on Nottingham Road in Codnor, deliberately placed on the A610 between the two cities, so that <a href=\"golf-lessons-derby.html\">golfers coming from Derby</a> and <a href=\"golf-lessons-nottingham.html\">golfers coming from Nottingham</a> arrive in roughly the same time. Fifteen minutes one way, twenty the other, free parking at the end of both."),
                 ("h3", "What Does Trackman Official Performance Centre Mean?"),
                 ("p", "Trackman is the dual-radar launch monitor used on the PGA Tour and by most of the world's leading coaches, and Official Performance Centre status means the technology here is the full specification rather than a cut-down version, and that the coaches using it are trained on it. In practice it means seven range bays reporting live data, a teaching bay set up for video and Trackman together, and custom fitting decided by numbers instead of a chart on the wall. Those fittings are brand neutral, so you can buy from us or anywhere you like."),
                 ("h3", "What Does TPI Certified Mean for an Ordinary Golfer?"),
                 ("p", "The Titleist Performance Institute framework connects the golf swing to the body producing it, and coaching here works to <strong>TPI certified principles</strong>. A TPI certified coach can tell whether you cannot turn your hips because nobody has taught you to, or because your hips physically will not do it. That distinction saves people years. It runs through our <a href=\"tpi-screening.html\">TPI screening</a> at £75 and through the work in the <a href=\"golf-fitness.html\">golf fitness suite</a>, and it quietly shapes every lesson taught here."),
                 ("h3", "How Big Is the Academy?"),
                 ("p", "Larger than most people expect from the road, and all of it is <strong>open to the public</strong>, member or not. Seven covered floodlit bays on the <a href=\"trackman-range.html\">Trackman driving range</a>, two or more indoor simulators, a private teaching bay, a <a href=\"grass-range.html\">grass driving range</a> for the drier months, a full <a href=\"short-game.html\">short game area</a> and a fitness suite. All of it on one site, all of it open from seven in the morning until eight at night, every day of the week."),
             ]},

            {"type": "split", "img": "bay_screen",
             "img_alt": "Trackman screen inside an indoor teaching bay at Evolution Golf Academy",
             "kick": "What we believe",
             "h2": "What Does Evolution Golf Academy Do <em>Differently?</em>",
             "paras": [
                 "Golf coaching has a habit of being sold as a one-off transaction. You buy an hour, you get told something true, and six weeks later it has faded. We would rather build the relationship, which is why so much of what we run is continuous rather than single-session, and why the same coach stays with you rather than whoever happened to be free.",
                 "The other difference is measurement. Because the academy is a <strong>Trackman Official Performance Centre</strong>, every number from your first session is still there in your tenth. Progress stops being a feeling and becomes a line on a chart, and that turns out to be far more motivating than anybody expects.",
             ],
             "ticks": [
                 "<b>One coach, not a rota</b> - see who you would be working with on <a href=\"meet-team.html\">the team page</a>",
                 "<b>Continuous coaching</b> - the <a href=\"monthly-programme.html\">monthly programme</a> is £60 a month",
                 "<b>Everything measured</b> - Trackman data from your first <a href=\"1-1-lessons.html\">golf lesson</a> onward",
                 "<b>Year-round facilities</b> - covered bays and <a href=\"trackman-simulator.html\">indoor simulators</a> for winter",
                 "<b>Easy to reach</b> - free parking and <a href=\"location.html\">directions from Derby and Nottingham</a>",
             ],
             "btn2": ("Meet the coaching team", "meet-team.html"), "alt": True},

            {"type": "team", "kick": "The coaching team",
             "h2": "Who Is the <em>Advanced PGA Professional</em> at the Academy?",
             "p": "Coaching here is led by Will Painter, an Advanced PGA Professional, working alongside TPI certified principles, Trackman expertise and fitness professionals. His full biography lives on our <a href=\"meet-team.html\">meet the team page</a>.",
             "people": [
                 {"img": "lesson_grip", "name": "Will Painter", "role": "Advanced PGA Professional, Head Coach and Academy Director",
                  "bio": "Will leads on technique, swing mechanics and long term player development, working with everyone from complete beginners to advanced players chasing their last two shots. The Advanced qualification is a stage beyond the standard PGA Professional route, and in practice it shows up as a coach who can explain a complicated idea in one sentence. He runs the junior academy and the ladies academy alongside individual coaching, oversees the custom fitting work carried out on Trackman, and keeps every golfer's data from one session to the next so progress is measured rather than remembered."},
             ]},

            {"type": "stats", "items": [("1:1", "PGA Coaching"), ("7", "Trackman Range Bays"),
                                        ("7am", "Open From, Daily")]},

            {"type": "prose", "kick": "The facilities",
             "h2": "What Facilities Does the Golf Academy Have <em>On Site?</em>",
             "blocks": [
                 ("p", "Everything below is on one site in Codnor, which means a session can move from a lesson to a practice bay to the short game area without anybody getting in a car. That sounds like a small thing and it is not. It is the reason a swing change here tends to survive contact with an actual golf course."),
                 ("h3", "Practice and Play"),
                 ("ul", [
                     "<a href=\"trackman-range.html\">Trackman driving range</a> - seven covered floodlit bays, walk-in, baskets from £4",
                     "<a href=\"trackman-simulator.html\">Trackman simulator</a> - indoor course play and practice at £25 an hour",
                     "<a href=\"grass-range.html\">Grass driving range</a> - real turf and honest strike feedback through the drier months",
                     "<a href=\"short-game.html\">Short game area</a> - chipping, pitching, bunker play and putting",
                     "Private bay hire at £15 an hour when you want to work undisturbed",
                 ]),
                 ("h3", "Coaching and Assessment"),
                 ("p", "Lessons run in the private <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a>, which pairs the launch monitor with video analysis and training aids in a space where nobody is watching you. A standard <a href=\"1-1-lessons.html\">1:1 golf lesson</a> is £55, and the <a href=\"monthly-programme.html\">monthly programme</a> at £60 a month is the option most regular golfers settle on once they have had a few."),
                 ("p", "For golfers who want to know what their body is contributing, <a href=\"tpi-screening.html\">TPI screening</a> costs £75 and produces a physical picture that the coaching plan is then built around. Follow-up work happens in the <a href=\"golf-fitness.html\">golf fitness suite</a>, which is set up specifically for the demands of the golf swing rather than general gym work."),
                 ("h3", "Group Coaching and Beginners"),
                 ("p", "Group sessions carry a lot of the week. <a href=\"get-into-golf.html\">Get Into Golf</a> is for people who have never played, <a href=\"beginner-coaching.html\">beginner coaching</a> picks things up from there, the <a href=\"junior-academy.html\">junior academy</a> handles ages six to sixteen and the <a href=\"ladies-academy.html\">ladies academy</a> runs women-only groups. We can lend you a set for any of them, so a first session costs you nothing in equipment."),
                 ("h3", "Custom Club Fitting"),
                 ("p", "Fitting is done on Trackman by our fitters, working alongside the coaching, so the specification accounts for where your swing is going rather than only where it sits today. Fittings are brand neutral, so you can buy from us or anywhere you like. Shaft, flex, lie angle, loft and swing weight are tested rather than assumed, and you leave with the numbers behind the recommendation."),
             ], "alt": True},

            {"type": "rel", "kick": "Find out more",
             "h2": "Where Should You Go <em>Next?</em>",
             "p": "The practical detail most people want after reading about the academy.",
             "links": [
                 ("location.html", "Location and Directions",
                  "Where we are on Nottingham Road in Codnor, and how to drive here from Derby, Nottingham and the M1.", "Find us"),
                 ("meet-team.html", "Meet the Team",
                  "The full biography for Will Painter, Advanced PGA Professional, and how sessions are matched to your goals.", "The coaching"),
                 ("faqs.html", "Frequently Asked Questions",
                  "Booking, prices, equipment, weather, cancellations and everything else people ask before a first visit.", "Read FAQs"),
                 ("trackman-range.html", "Trackman Driving Range",
                  "Seven covered floodlit bays with live ball data on every shot. No booking required.", "The range"),
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes with an Advanced PGA Professional in the private Trackman teaching bay, £55.", "Golf lessons"),
                 ("contact.html", "Contact the Academy",
                  "Send an enquiry to the coaching team, or ring 07710 582036 between 7am and 8pm any day.", "Get in touch"),
             ]},

            {"type": "tgrid", "kick": "Reviews",
             "h2": "What Do Golfers Say About the <em>Academy?</em>",
             "items": [
                 ("Great first lesson with Will. Felt very comfortable and definitely happy with the results.", "Kelsey"),
                 ("Another great lesson with Will today. Very knowledgeable talking through all the different strategies of chipping.", "Harry"),
                 ("After a comprehensive test of a variety of shafts and swing weights I now have complete confidence in my clubs.", "Lee"),
             ], "alt": True},

            {"type": "faq", "kick": "Common questions",
             "h2": "About Evolution Golf Academy - <em>FAQs.</em>",
             "qs": [
                 ("Where exactly is Evolution Golf Academy based?",
                  "At Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL, in Derbyshire. It is about fifteen minutes from Derby and twenty from Nottingham, with free parking on site. Directions from the M1, Belper, Alfreton and the surrounding towns, plus what to expect when you arrive, are on our <a href=\"location.html\">location page</a>."),
                 ("Do I have to be a member to use the academy?",
                  "No. Anyone can book golf lessons, the range or the simulators, and you do not need to be a member of Ormonde Fields Golf Club either. Membership does exist, and it gives you priority booking and better rates, but everything here is open to the public. You book what you want and pay for that, which is the arrangement most golfers prefer."),
                 ("Is Evolution Golf Academy suitable for complete beginners?",
                  "It is designed for them as much as for good players. <a href=\"get-into-golf.html\">Get Into Golf</a> assumes no experience at all, and <a href=\"beginner-coaching.html\">beginner coaching</a> takes you from there to a swing that repeats. We can lend you a set for lessons, club hire is included at no extra cost on the range and simulators, the bays are private enough that nobody is watching, and a good part of every week here is spent teaching people who have never played."),
                 ("What is a Trackman Official Performance Centre?",
                  "It means the academy runs full-specification Trackman dual-radar launch monitors and the coaching is built around them. Seven bays on the <a href=\"trackman-range.html\">driving range</a> report live ball and club data, the teaching bay combines Trackman with video, and custom fitting decisions come from measured numbers rather than assumptions about your swing speed."),
                 ("Who will coach me at the academy?",
                  "Will Painter, Advanced PGA Professional and Academy Director. He leads individual coaching, the junior academy and the ladies academy, and the same person sees your swing from the first session to the hundredth. Around that sit TPI certified principles, Trackman expertise and fitness professionals in the golf fitness suite, so sessions are matched to your goals rather than passed between people. His full biography is on the <a href=\"meet-team.html\">meet the team page</a>."),
                 ("What does it cost to use the academy?",
                  "A 1:1 lesson is £55 and the <a href=\"monthly-programme.html\">monthly programme</a> is £60 a month. TPI screening is £75. Range baskets start from £4, a private bay is £15 an hour and the <a href=\"trackman-simulator.html\">Trackman simulator</a> is £25 an hour. Group coaching is priced per block, so ring 07710 582036 for current dates and rates."),
                 ("Do you run junior and ladies coaching?",
                  "Yes. The <a href=\"junior-academy.html\">junior academy</a> takes ages six to sixteen in structured groups led by Will Painter, Advanced PGA Professional, and the <a href=\"ladies-academy.html\">ladies academy</a> runs women-only sessions for beginners and improvers. Both are popular with families across Ripley, Heanor, Belper and Alfreton, and both lead into individual coaching for anyone who wants to take it further."),
                 ("Can I visit and look round before booking anything?",
                  "Of course. The <a href=\"trackman-range.html\">driving range</a> is walk-in, so the simplest thing is to turn up, buy a basket and see the place while you hit balls. Club hire is included at no extra cost, so you can do that with nothing in the boot. If you would rather speak to someone first, ring 07710 582036 or send an enquiry through the <a href=\"contact.html\">contact page</a> and we answer within a working day."),
             ]},
        ],
    },

    # ============================================================= LOCATION
    {
        "file": "location.html",
        "cur": "location.html",
        "title": "Golf Academy Location Ripley, Codnor, Derbyshire | Directions &amp; Parking",
        "desc": "Golf academy location in Ripley, Codnor, Derbyshire. Ormonde Fields Golf Club, Nottingham Road, DE5 9RL. 15 minutes from Derby, 20 from Nottingham on the A610. Free parking, open 7am to 8pm.",
        "visit_kick": "Golf academy location in Ripley &amp; Codnor",
        "cta": ("Fifteen minutes from <em>Derby.</em>",
                "Nottingham Road, Codnor, Ripley DE5 9RL. Free parking on site, open 7am to 8pm every day, and you do not need to be a member to walk in and hit balls."),
        "hero": {
            "kick": "Golf Academy Location, Ripley and Codnor, Derbyshire",
            "l1": "Visit", "l2": "Ripley.",
            "p": "Our <strong>golf academy location in Ripley, Codnor, Derbyshire</strong> sits on Nottingham Road at Ormonde Fields Golf Club, fifteen minutes from Derby and twenty from Nottingham on the A610. Free parking on site, open from 7am to 8pm, seven days a week, all year round.",
            "img": "range_night",
            "alt": "Floodlit driving range bays at the Evolution Golf Academy location in Codnor, Ripley",
        },
        "marq": ["Nottingham Rd, Codnor", "Ripley DE5 9RL", "15 Minutes From Derby",
                 "20 Minutes From Nottingham", "Free On-Site Parking", "Open 7am to 8pm"],
        "sections": [

            {"type": "prose", "kick": "Where we are",
             "h2": "Where Is Evolution Golf Academy <em>Located?</em>",
             "blocks": [
                 ("p", "The academy is at <strong>Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL</strong>, in the middle of Derbyshire and a couple of minutes off the A610. Codnor sits between Ripley and Langley Mill, so if you know the road that runs from the Ripley bypass down towards Eastwood, you already know how to find us. The entrance is signed from Nottingham Road and the car park is immediately inside."),
                 ("p", "Being here rather than inside either city was a deliberate choice. A <strong>golf academy near Derby and Nottingham</strong> only works if both sets of golfers can get to it after work without resenting the journey, and the A610 does that job better than anything running through a city centre. Fifteen minutes from Derby, twenty from Nottingham, and neither trip involves a park and ride or a parking charge."),
                 ("h3", "Why Does Sitting Between Derby and Nottingham Work So Well?"),
                 ("p", "Because the traffic runs the other way. Most evening congestion around the East Midlands is people heading into or out of the two city centres, and coming here you are travelling across that flow rather than with it. It also means one academy serves both counties in full, which is why we keep separate pages explaining the journey and coaching options for <a href=\"golf-lessons-derby.html\">golf lessons from Derby</a> and <a href=\"golf-lessons-nottingham.html\">golf lessons from Nottingham</a>."),
                 ("h3", "What Postcode Should I Put in the Satnav?"),
                 ("p", "DE5 9RL. Some older satnavs place that postcode slightly short of the entrance, so if the arrival announcement fires before you see the sign, keep going for a few hundred metres along Nottingham Road. Searching for Ormonde Fields Golf Club or Evolution Golf Academy in Google Maps will take you to the correct entrance every time, and the map on this page is set to the same spot."),
                 ("h3", "Is There Parking at the Golf Academy?"),
                 ("p", "Yes, <strong>parking is free and on site</strong>, and there is normally space even at the busiest times on a weekend morning. You park once and everything is a short walk away, including the <a href=\"trackman-range.html\">Trackman driving range</a>, the teaching bays and the <a href=\"short-game.html\">short game area</a>. There is no barrier, no ticket machine and nothing to display in the windscreen."),
             ]},

            {"type": "steps", "kick": "Getting here",
             "h2": "How Do I Get to the Golf Academy From <em>Derby and Nottingham?</em>",
             "p": "Five routes covering where most golfers travel in from. All of them finish in the same free car park on Nottingham Road.",
             "steps": [
                 ("Driving from Derby, about 15 minutes",
                  "Head north east out of Derby on the A61 towards Ripley, then join the A610 towards Codnor and Langley Mill. Come off at Codnor and follow Nottingham Road. The entrance to Ormonde Fields is on your right. Full detail for golfers travelling this way is on our <a href=\"golf-lessons-derby.html\">golf lessons Derby</a> page."),
                 ("Driving from Nottingham, about 20 minutes",
                  "Take the A610 north west out of Nottingham through Nuthall, Kimberley and Eastwood, continue past Langley Mill and turn off for Codnor. Nottingham Road runs straight to us. It is dual carriageway for most of the way, which is why the trip is quicker than the map suggests. See the <a href=\"golf-lessons-nottingham.html\">golf lessons Nottingham</a> page for more."),
                 ("Coming off the M1 at Junction 26",
                  "Leave the M1 at Junction 26 and take the A610 north west towards Ripley. Stay on it past Eastwood and Langley Mill, then come off for Codnor and pick up Nottingham Road. It is about twelve minutes from the motorway roundabout, which makes the academy easy to reach from Sheffield, Chesterfield and Leicester as well."),
                 ("Coming from Belper, Alfreton and Heanor",
                  "From Belper take the A610 east through Ambergate and Ripley. From Alfreton drop south on the A38 and A61 into Ripley, then follow signs for Codnor. From Heanor it is a straight run north on the A6007 and Codnor Denby Lane. All three journeys are inside fifteen minutes outside rush hour."),
                 ("Parking and finding your way round the site",
                  "Turn in at Ormonde Fields Golf Club and park in the free car park directly ahead. The academy building and the covered range bays are signed from there. If it is your first visit, walk into reception and someone will point you at the right bay, whether you are here for a lesson or just picking up a basket for the <a href=\"trackman-range.html\">driving range</a>."),
             ]},

            {"type": "split", "img": "putting",
             "img_alt": "Putting and short game practice area at the golf academy in Codnor, Derbyshire",
             "kick": "What is on site",
             "h2": "What Will You Find When You <em>Get Here?</em>",
             "paras": [
                 "The academy is bigger than it looks from Nottingham Road. Everything sits on one site, so a session can move from a lesson bay to a practice bay to the chipping green without anyone moving a car, and that continuity is a large part of why swing changes made here actually hold up on the course.",
                 "It is also built for a Derbyshire winter. The range bays are <strong>covered and floodlit until 8pm</strong>, and the indoor simulator bays carry on regardless of what is falling out of the sky, so the practice season does not stop in October like it does almost everywhere else.",
             ],
             "ticks": [
                 "<b>Seven Trackman bays</b> on the covered <a href=\"trackman-range.html\">driving range</a>, walk-in from £4",
                 "<b>Indoor simulators</b> - the <a href=\"trackman-simulator.html\">Trackman simulator</a> is £25 an hour",
                 "<b>Private teaching bay</b> for <a href=\"trackman-teaching-bay.html\">coaching with video and Trackman</a>",
                 "<b>Short game and grass range</b> - <a href=\"short-game.html\">chipping and bunkers</a> plus a <a href=\"grass-range.html\">grass range</a>",
                 "<b>Golf fitness suite</b> for <a href=\"golf-fitness.html\">mobility, strength and speed work</a>",
             ],
             "btn2": ("See the Trackman range", "trackman-range.html"), "alt": True},

            {"type": "areas", "kick": "Areas we cover",
             "h2": "Which Towns Do Golfers Travel From to <em>Reach Us?</em>",
             "p": "Codnor sits in the middle of a lot of Derbyshire and Nottinghamshire. These are the places our golfers most often drive in from, and every one of them is inside half an hour.",
             "tags": [
                 ("Derby", "golf-lessons-derby.html"),
                 ("Nottingham", "golf-lessons-nottingham.html"),
                 ("Ripley", None), ("Codnor", None), ("Heanor", None), ("Belper", None),
                 ("Alfreton", None), ("Ilkeston", None), ("Eastwood", None), ("Hucknall", None),
                 ("Kimberley", None), ("Long Eaton", None), ("Swanwick", None), ("Langley Mill", None),
             ]},

            {"type": "rel", "kick": "Plan your visit",
             "h2": "What Should You Book Before You <em>Travel?</em>",
             "p": "The range needs no booking at all. Everything else is worth arranging before you set off, particularly at weekends.",
             "links": [
                 ("trackman-range.html", "Trackman Driving Range",
                  "Walk-in, seven covered floodlit bays, baskets from £4 and club hire included at no extra cost.", "The range"),
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes with an Advanced PGA Professional at £55. Weekend and after-work slots go first, so book ahead.", "Book a lesson"),
                 ("trackman-simulator.html", "Trackman Simulator",
                  "£25 an hour indoors with club hire included, and the thing to reserve if the forecast looks unpleasant.", "Simulator"),
                 ("meet-team.html", "Meet the Team",
                  "Will Painter, Advanced PGA Professional. Worth a read before booking your first session.", "The coaching"),
                 ("faqs.html", "Frequently Asked Questions",
                  "Prices, equipment, weather, cancellations and the practical detail of a first visit.", "Read FAQs"),
                 ("contact.html", "Contact the Academy",
                  "Send an enquiry or ring 07710 582036 if you want to check something before you drive over.", "Get in touch"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Golf Academy Location, Ripley and Codnor - <em>FAQs.</em>",
             "qs": [
                 ("Is there free parking at the golf academy?",
                  "Yes. Parking is free, on site and unrestricted, with no barrier, ticket machine or time limit. The car park sits directly inside the entrance to Ormonde Fields Golf Club on Nottingham Road, and there is usually space even on a Saturday morning. Everything at the academy is a short walk from where you leave the car."),
                 ("Can I get to the academy by public transport?",
                  "It is possible but not ideal. Buses run along the A610 corridor between Ripley, Codnor and Langley Mill, and the nearest railway stations are Alfreton and Langley Mill, both a short taxi ride away. Most golfers drive, largely because carrying a bag on a bus is nobody's idea of a good start to a session."),
                 ("Is the academy accessible for wheelchair users and people with limited mobility?",
                  "The car park, range bays and main academy areas are on level ground with no steps between them, and the covered bays are wide enough to work in comfortably. If you have specific access needs, ring 07710 582036 before you visit and we will make sure the right bay is free and someone meets you at the car park."),
                 ("What are the opening hours at the Ripley golf academy?",
                  "Seven in the morning until eight at night, seven days a week, including weekends and bank holidays. The range bays are covered and floodlit, so the last hour in December works the same as the last hour in June. Coaching slots run across the whole of that window, including early mornings before work."),
                 ("Do I need to book before I come?",
                  "Not for the <a href=\"trackman-range.html\">Trackman driving range</a>, which is walk-in and first come, first served. You do need to book <a href=\"1-1-lessons.html\">golf lessons</a>, private bays, the <a href=\"trackman-simulator.html\">simulator</a>, custom fitting and <a href=\"tpi-screening.html\">TPI screening</a>. Booking online is quickest, or ring 07710 582036 during opening hours."),
                 ("What is the full address and postcode?",
                  "Evolution Golf Academy, Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL. Put DE5 9RL into the satnav, or search for the academy by name in Google Maps, which lands on the correct entrance. The embedded map further down this page points at the same place if you want to send directions to your phone."),
                 ("How far is the academy from Derby and Nottingham?",
                  "Around fifteen minutes from Derby city centre and twenty from Nottingham, both largely on the A610. From the M1 at Junction 26 it is roughly twelve minutes. Golfers regularly travel in from Belper, Alfreton, Heanor, Ilkeston, Eastwood and Hucknall too, all of which are inside half an hour on a normal evening."),
                 ("Is there anywhere to get food or a drink on site?",
                  "Ormonde Fields Golf Club has a clubhouse on the same site, so there is somewhere to sit down with a coffee before or after a session. It is a genuinely useful thing on a winter morning, and it makes the academy workable for a group who want to combine a <a href=\"trackman-simulator.html\">simulator booking</a> with a couple of hours that are not spent standing outdoors."),
             ]},
        ],
    },

    # ============================================================ MEET TEAM
    {
        "file": "meet-team.html",
        "cur": "meet-team.html",
        "title": "PGA Golf Coach Derby &amp; Nottingham | Meet the Team | Evolution Golf Academy",
        "desc": "Meet Will Painter, the Advanced PGA Professional coaching golfers from Derby and Nottingham at Evolution Golf Academy, Ripley. Trackman coaching, TPI certified principles and brand neutral fitting.",
        "visit_kick": "PGA golf coaching near Derby &amp; Nottingham",
        "cta": ("Book your first <em>session.</em>",
                "Advanced PGA Professional coaching, TPI certified principles, Trackman expertise and fitness professionals on one site. Tell us your goal and the session gets built around it."),
        "hero": {
            "kick": "PGA Golf Coaching Derby &amp; Nottingham",
            "l1": "Meet the", "l2": "Team.",
            "p": "Coaching at Evolution Golf Academy in Codnor, Ripley is led by <strong>Will Painter, Advanced PGA Professional</strong>, working with golfers from Derby, Nottingham and across Derbyshire. Alongside him sit TPI certified principles, Trackman expertise and fitness professionals, covering everything from a first lesson to a scratch handicap.",
            "img": "coach_feedback",
            "alt": "PGA golf coach giving Trackman feedback to a golfer near Derby and Nottingham",
        },
        "marq": ["Advanced PGA Professional", "Will Painter", "Trackman Coaching",
                 "TPI Certified Principles", "Brand Neutral Fitting", "Ripley, Derbyshire"],
        "sections": [

            {"type": "prose", "kick": "Coaching philosophy",
             "h2": "How Does Our <em>PGA Golf Coach</em> Actually Teach?",
             "blocks": [
                 ("p", "There is a long-running and slightly tedious argument in golf coaching between the data people and the feel people. The data camp will not look up from the screen. The feel camp will not look at it at all. Both are working with half the evidence, and a golfer paying £55 for an hour deserves all of it. Coaching here uses <strong>Trackman data and coaching feel together</strong>, because the numbers say what happened and only the golfer can say what it felt like."),
                 ("h3", "What Does Data Plus Feel Mean in a Lesson?"),
                 ("p", "It means the launch monitor settles the factual questions - did the face open, did the path change, did the strike move towards the middle - and the coach handles the human question, which is what you need to feel in order to repeat it on the first tee with people watching. A number nobody can reproduce is trivia. A feel nobody can measure is a hope. Together they are a lesson. That is the whole of it, and it runs through every <a href=\"1-1-lessons.html\">1:1 golf lesson</a> we teach."),
                 ("h3", "Will I Understand What the Coach Is Telling Me?"),
                 ("p", "Yes, because jargon is treated here as a failure of explanation rather than a sign of expertise. Your <strong>golf instructor</strong> teaches in plain English. Attack angle, dynamic loft and low point are all real, all useful to a coach, and all completely useless to a golfer who has come after work and wants to stop losing balls right. Will will go as technical as you ask him to and no further. If you cannot explain your lesson to your playing partner afterwards, the lesson did not land."),
                 ("h3", "How Many Changes Will I Be Given at Once?"),
                 ("p", "One, in almost every case. The fastest way to make a golfer worse is to hand them a list. A single change, understood, drilled and given a way to practise it on the <a href=\"trackman-range.html\">Trackman driving range</a> between sessions, beats four changes half-remembered in the car park. For golfers who want that sequenced across a whole season, the <a href=\"monthly-programme.html\">monthly coaching programme</a> is built exactly for it."),
                 ("h3", "Do You Look at the Golfer as Well as the Swing?"),
                 ("p", "Always. Coaching here runs on <strong>TPI certified principles</strong>, which means the first question when a movement will not happen is whether you have never been taught it or whether your body will not currently do it. Those need completely different answers, and giving the technical one to a physical problem wastes months. <a href=\"tpi-screening.html\">TPI screening</a> at £75 answers it in an hour, and the <a href=\"golf-fitness.html\">golf fitness suite</a> handles the work that follows."),
             ]},

            {"type": "team", "kick": "The coaching team",
             "h2": "Who Is the <em>Advanced PGA Professional</em> at Evolution Golf Academy?",
             "p": "One Advanced PGA Professional leading the coaching, supported by TPI certified principles, Trackman expertise and fitness professionals, all on the same site in Codnor, Ripley.",
             "people": [
                 {"img": "over_shoulder", "name": "Will Painter",
                  "role": "Advanced PGA Professional, Head Coach and Academy Director",
                  "bio": "Will is an Advanced PGA Professional, Head Coach and Academy Director. The Advanced qualification sits a stage beyond the standard PGA Professional route and takes years of assessed coaching to earn, which matters mainly because of what it produces: a coach who can take a complicated idea and hand it over in one sentence. He leads on technique, swing mechanics and long term player development, working across the full range from someone who has never held a club to a single figure player chasing the last two shots. "
                         "Will is the first coach most new golfers here meet and the one they keep going back to, and because he is the only coach you will see, nobody is ever re-reading your swing from scratch. He uses Trackman in nearly every session, but the numbers are there to settle questions rather than to run the lesson, and he keeps your data from one session to the next so progress is measured rather than remembered. "
                         "Alongside <a href=\"1-1-lessons.html\">1:1 golf lessons</a> and the <a href=\"monthly-programme.html\">monthly programme</a>, Will leads the <a href=\"junior-academy.html\">junior academy</a> for ages six to sixteen and the <a href=\"ladies-academy.html\">ladies academy</a>, runs <a href=\"get-into-golf.html\">Get Into Golf</a> and <a href=\"beginner-coaching.html\">beginner coaching</a> for people starting from nothing, and works with golfers coming out of <a href=\"tpi-screening.html\">TPI screening</a> whose plan needs to fit what their body will actually allow. He also oversees the brand neutral custom fitting carried out on Trackman, so equipment decisions and coaching decisions are made by people looking at the same numbers."},
             ]},

            {"type": "prose", "kick": "Who else is behind the coaching",
             "h2": "What Does the Academy Put <em>Behind Your Coach?</em>",
             "blocks": [
                 ("p", "One coach with a full diary is only as good as what stands behind him, and a great deal of improvement happens outside the hour you spend in the teaching bay. The academy combines <strong>Advanced PGA Professional coaching, TPI certified principles, Trackman expertise and fitness professionals</strong> on one site, which is the reason a golfer can arrive with a slice and leave with an answer that covers technique, equipment and physical capability rather than only the first of those."),
                 ("h3", "What Does Trackman Expertise Add to a Golf Lesson?"),
                 ("p", "We are a Trackman Official Performance Centre, so the launch monitors are full specification rather than a cut-down version, and the data collected in a lesson is the same data used in the fitting bay and on the <a href=\"trackman-range.html\">Trackman driving range</a>. That continuity matters more than the technology itself. A change made in the <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a> can be checked on your own during the week and reviewed against your own baseline at the next session, so nobody is arguing about whether something improved."),
                 ("h3", "How Do the Fitness Professionals Fit In?"),
                 ("p", "Golfers are handed technical answers to physical problems constantly, and it wastes months. If your lead hip will not rotate, no amount of drilling a hip turn will produce one. <a href=\"tpi-screening.html\">TPI screening</a> at £75 establishes what your body will currently allow, and the <a href=\"golf-fitness.html\">golf fitness suite</a> is where the mobility, strength and speed work then happens, built around the demands of a golf swing rather than general gym training. The coaching plan is written to match, and rewritten as the physical picture changes."),
                 ("h3", "Who Carries Out the Custom Fitting?"),
                 ("p", "Our fitters, working on Trackman data rather than a chart on the wall, with the coaching sat alongside so that the specification accounts for where your swing is heading. <strong>Fittings are brand neutral</strong>, so you can buy from us or anywhere you like, and nobody has a reason to steer you towards a particular badge. Shaft, flex, lie angle, loft and swing weight are all tested against what your swing actually does, and you leave with the numbers that produced the recommendation."),
                 ("h3", "Does One Coach Mean a Longer Wait for a Lesson?"),
                 ("p", "Not usually, because the academy is open from 7am to 8pm every day of the week, which is a far wider coaching window than most places offer. Early mornings before work, evenings under floodlights and weekends are all live slots. Weekend and after-work times do go first, so booking a week ahead is sensible, and the <a href=\"monthly-programme.html\">monthly programme</a> at £60 a month books your sessions in as a standing arrangement rather than a scramble each time."),
             ]},

            {"type": "split", "img": "lesson_grip",
             "img_alt": "PGA golf instructor adjusting a golfer's grip during a lesson in Derbyshire",
             "kick": "Finding the right session",
             "h2": "Which Golf Session Is <em>Right for Me?</em>",
             "paras": [
                 "You do not have to work this out yourself. When an enquiry comes in we ask three things: what you play off, what you want to change, and what you have already tried. That is normally enough to point you at the right starting point, and if it is not, we will say so rather than guess.",
                 "The session gets matched to your goal rather than to a different name on a rota. A first ever swing, a stubborn slice, a child of eight, a body that will not turn: all of those are the same coach and the same site, and what changes is what the hour is aimed at. <strong>Staying with one coach is the point</strong>, because a coach who has watched your swing for six months spots a change in about ten seconds.",
             ],
             "ticks": [
                 "<b>New to golf</b> - start with <a href=\"get-into-golf.html\">Get Into Golf</a> or <a href=\"beginner-coaching.html\">beginner coaching</a>",
                 "<b>Stuck at the same handicap</b> - a <a href=\"1-1-lessons.html\">1:1 golf lesson</a> at £55 to diagnose it",
                 "<b>Blaming your clubs</b> - brand neutral custom fitting on Trackman, <a href=\"contact.html\">ask us</a>",
                 "<b>Child aged 6 to 16</b> - the <a href=\"junior-academy.html\">junior academy</a>, led by Will",
                 "<b>Body will not do what you ask it</b> - <a href=\"tpi-screening.html\">TPI screening</a> first, technique second",
             ],
             "btn2": ("Ask us what to book", "contact.html"), "alt": True},

            {"type": "steps", "kick": "How coaching works here",
             "h2": "What Happens From Enquiry to <em>First Lesson?</em>",
             "p": "Five steps, and none of them involve being sold a package you did not ask about.",
             "steps": [
                 ("You send an enquiry or ring us",
                  "Use the form on the <a href=\"contact.html\">contact page</a> or ring 07710 582036 between 7am and 8pm. Tell us roughly what you play off, what is bothering you and when you can get here. Nobody needs a handicap or a history to make that first contact."),
                 ("We match the session to your goal",
                  "Based on what you want to change rather than what is easiest to sell. That might be a single diagnostic hour, a block of beginner coaching, a TPI screen before anything technical, or a fitting if your clubs are the problem. We answer within a working day with a recommendation and a couple of times."),
                 ("Your first session",
                  "An hour in the private <a href=\"trackman-teaching-bay.html\">Trackman teaching bay</a>. The first twenty minutes are mostly the coach watching and asking questions while Trackman gathers a baseline. There is no lecture and nothing gets rebuilt on day one."),
                 ("You leave with a plan",
                  "One change, a way to feel it, and a specific practice task with numbers attached so you know whether it is working when you next get to the <a href=\"trackman-range.html\">driving range</a>. It is written down, because nobody remembers a plan given verbally in the last four minutes."),
                 ("We follow it up",
                  "Your baseline data is kept, so the next session starts by comparing rather than guessing. Most golfers move onto the <a href=\"monthly-programme.html\">monthly programme</a> at this point because continuous coaching is where the handicap actually shifts, but there is no obligation to."),
             ]},

            {"type": "rel", "kick": "Coaching options",
             "h2": "What Can You <em>Book With Our Coach?</em>",
             "p": "Every option below is taught by Will Painter, Advanced PGA Professional, on the same site in Codnor, Ripley.",
             "links": [
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes in the private Trackman teaching bay with video analysis. £55 per lesson.", "Golf lessons"),
                 ("beginner-coaching.html", "Beginner Coaching",
                  "Structured tuition for new golfers and returners. We can lend you a set, no experience assumed.", "Beginners"),
                 ("monthly-programme.html", "Monthly Programme",
                  "£60 a month for continuous coaching, a rolling practice plan and tracked Trackman progress.", "Monthly coaching"),
                 ("junior-academy.html", "Junior Academy",
                  "Group coaching for ages six to sixteen led by Will Painter, Advanced PGA Professional.", "Junior golf"),
                 ("ladies-academy.html", "Ladies Academy",
                  "Women-only group sessions for beginners and improvers in a relaxed, unhurried setting.", "Ladies golf"),
                 ("tpi-screening.html", "TPI Screening",
                  "A £75 physical assessment showing which swing limitations are technical and which are physical.", "TPI screening"),
             ]},

            {"type": "tgrid", "kick": "Reviews",
             "h2": "What Do Golfers Say About Our <em>Coaches?</em>",
             "items": [
                 ("Great first lesson with Will. Felt very comfortable and definitely happy with the results.", "Kelsey"),
                 ("Another great lesson with Will today. Very knowledgeable talking through all the different strategies of chipping.", "Harry"),
                 ("After a comprehensive test of a variety of shafts and swing weights I now have complete confidence in my clubs.", "Lee"),
             ], "alt": True},

            {"type": "faq", "kick": "Common questions",
             "h2": "PGA Golf Coaching Derby &amp; Nottingham - <em>FAQs.</em>",
             "qs": [
                 ("Who will coach me?",
                  "Will Painter, Advanced PGA Professional. He leads the coaching at the academy, so whatever you book, he is the person in the bay. We still ask what you play off and what you want to change before you arrive, because that shapes what the hour is aimed at, and we will tell you what we think you should book rather than simply taking the order."),
                 ("Do I stay with the same coach between sessions?",
                  "Yes, and that is deliberate rather than a limitation. Coaching is a working relationship, and a coach who has watched your swing for six months spots a change in about ten seconds where a stranger needs half a lesson. Your Trackman history sits alongside that, so every session starts by comparing against your own baseline rather than guessing."),
                 ("Is your golf coach PGA qualified?",
                  "Will Painter is an Advanced PGA Professional, which is a stage beyond the standard qualification through the Professional Golfers' Association and a long way beyond a weekend certificate. Coaching here also works to TPI certified principles, so the physical side of your swing is assessed as well as the technical side. That is why <a href=\"tpi-screening.html\">TPI screening</a> feeds directly into the coaching plan."),
                 ("Do you teach complete beginners?",
                  "Every week, and beginners are not handed to a junior member of staff here, because teaching someone their first swing well is harder than tidying up a five handicapper. Start with <a href=\"get-into-golf.html\">Get Into Golf</a> if you have never played, or <a href=\"beginner-coaching.html\">beginner coaching</a> if you have had a few goes and want structure. We can lend you a set, so you need nothing to begin."),
                 ("Who else works at the academy?",
                  "The academy combines Advanced PGA Professional coaching with TPI certified principles, Trackman expertise and fitness professionals in the <a href=\"golf-fitness.html\">golf fitness suite</a>, plus our fitters on the custom fitting side. What you get is one coach who knows your swing, backed by people whose job is the parts of improvement that sit outside the teaching bay."),
                 ("Can you help if I think my clubs are wrong?",
                  "Yes. Custom fitting runs on Trackman numbers rather than a chart, testing shaft, flex, lie angle, loft and swing weight against what your swing actually does. Fittings are brand neutral, so you can buy from us or anywhere you like, and because the fitting sits alongside the coaching the specification accounts for where your swing is heading rather than freezing it where it is today. <a href=\"contact.html\">Ask us</a> to arrange one."),
                 ("Do you coach juniors, and from what age?",
                  "From six years old, through the <a href=\"junior-academy.html\">junior academy</a> up to age sixteen, led by Will Painter, Advanced PGA Professional. Sessions are group based, structured and built so that children are enjoying themselves while they learn, which is the only way any of it sticks. Juniors who want to go further move into individual coaching alongside the group sessions."),
                 ("How much is a lesson and how do I book one?",
                  "A 1:1 golf lesson is £55 for sixty minutes, and the <a href=\"monthly-programme.html\">monthly programme</a> is £60 a month for continuous coaching. Booking online is the fastest route, or ring 07710 582036 any day between 7am and 8pm. You can also send an enquiry from the <a href=\"contact.html\">contact page</a> and we will come back to you."),
             ]},
        ],
    },

    # ============================================================== CONTACT
    {
        "file": "contact.html",
        "cur": None,
        "title": "Book Golf Lessons Derby &amp; Nottingham | Contact Evolution Golf Academy",
        "desc": "Book golf lessons near Derby and Nottingham at Evolution Golf Academy, Codnor, Ripley DE5 9RL. Call 07710 582036 or send an enquiry. Open 7am to 8pm, seven days a week.",
        "visit_kick": "Book golf lessons near Derby &amp; Nottingham",
        "cta": ("Book your first <em>lesson.</em>",
                "A 1:1 golf lesson with an Advanced PGA Professional is £55, and the monthly programme is £60 a month. Booking online takes about a minute, or ring 07710 582036."),
        "hero": {
            "kick": "Book Golf Lessons Derby &amp; Nottingham",
            "l1": "Get in", "l2": "Touch.",
            "p": "<strong>Book golf lessons in Derby and Nottingham</strong> with an Advanced PGA Professional at Evolution Golf Academy in Codnor, Ripley. Send an enquiry below, ring 07710 582036, or book online. We are open from 7am to 8pm, seven days a week, with free parking on site.",
            "img": "lesson_grip",
            "alt": "PGA golf instructor coaching grip during a booked golf lesson near Derby",
        },
        "marq": ["Book Golf Lessons Derby", "Golf Lessons Nottingham", "07710 582036",
                 "Open 7am to 8pm", "Ripley DE5 9RL", "Advanced PGA Professional"],
        "sections": [

            {"type": "form",
             "kick": "Book golf lessons near Derby and Nottingham",
             "h2": "How Do You Book a Golf Lesson at <em>Evolution Golf Academy?</em>",
             "intro_p": "Fill in the form and it lands with the coaching team directly. Tell us what you play off, what you would like to change and roughly when you can get here, and we will come back with a recommendation and a time. We answer within a working day. If you would rather talk it through, ring 07710 582036 any day between 7am and 8pm.",
             "right_html": "<div class=\"prose\"><h3>Where to find the golf academy</h3>"
                           "<p>Evolution Golf Academy, Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL. Fifteen minutes from Derby and twenty from Nottingham on the A610, with free parking on site. Full driving directions are on our <a href=\"location.html\">location page</a>.</p>"
                           "<h3>Phone and opening hours</h3>"
                           "<p>Call <a href=\"tel:07710582036\">07710 582036</a>. The academy is open from 7am to 8pm, seven days a week, including weekends and bank holidays. The covered range bays are floodlit, so late sessions run the same in December as they do in June.</p>"
                           "<ul><li>Monday to Sunday, 7:00am to 8:00pm</li>"
                           "<li>Range is walk-in, no booking needed</li>"
                           "<li>Lessons, simulator and fitting are booked in advance</li>"
                           "<li>Free parking, and no membership needed to book</li>"
                           "<li>Club hire included at no extra cost on range and simulators</li></ul>"
                           "<h3>What happens after you enquire</h3>"
                           "<p>A coach reads your enquiry rather than an inbox robot. We reply with a suggested session, a couple of times that fit what you told us, and an honest view on whether the thing you asked for is the thing you need. We answer within a working day.</p>"
                           "<ul><li>Coaching is led by Will Painter, Advanced PGA Professional</li>"
                           "<li>You get suggested times, not a sales call</li>"
                           "<li>Nothing is charged until you confirm a booking</li></ul>"
                           "<h3>Booking online is fastest</h3>"
                           "<p>If you already know what you want, the online booking system shows live availability and confirms instantly, which is quicker than waiting on a reply. Use the enquiry form instead when you are not sure what to book, and read the <a href=\"meet-team.html\">coaching team page</a> if you want to know who you will be working with first.</p></div>"},

            {"type": "prose", "kick": "Choosing what to book",
             "h2": "Which Golf Lesson or Service Should You <em>Book First?</em>",
             "blocks": [
                 ("p", "Most people ringing to <strong>book golf lessons near Derby and Nottingham</strong> for the first time are not sure what to ask for, which is entirely reasonable given that the price list runs from a £4 basket of balls to a full custom fitting. Below is the short version of what each thing is for. If none of it quite matches your situation, send the enquiry anyway and describe the problem in your own words. Working out what you need is part of the job."),
                 ("h3", "You Have Never Played Golf Before"),
                 ("p", "Start with <a href=\"get-into-golf.html\">Get Into Golf</a>. It assumes nothing, we can lend you a set for the lesson, and it is deliberately built for people who feel self-conscious about being a beginner in front of golfers. From there, <a href=\"beginner-coaching.html\">beginner coaching</a> takes you to a swing that repeats and a set of shots you can take onto a course without dreading the first tee."),
                 ("h3", "You Play Already and Want to Fix Something Specific"),
                 ("p", "Book a <a href=\"1-1-lessons.html\">1:1 golf lesson</a> at <strong>£55 for sixty minutes</strong>. An hour in the private teaching bay with Trackman and video is normally enough to identify what is going on, and you will leave with one change and a practice task rather than a list. If it turns out to need more than one session, the coach will say so plainly."),
                 ("h3", "You Want to Improve Steadily Over a Season"),
                 ("p", "The <a href=\"monthly-programme.html\">monthly coaching programme</a> at £60 a month is the option most regular golfers end up on. It is continuous coaching with a rolling practice plan, and progress is tracked on Trackman so you can see the direction of travel rather than relying on how last Sunday happened to go."),
                 ("h3", "You Just Want to Hit Balls"),
                 ("p", "Turn up. The <a href=\"trackman-range.html\">Trackman driving range</a> is <strong>walk-in with no booking</strong>, open from 7am to 8pm with baskets from £4 and club hire included at no extra cost. A private bay is £15 an hour if you would rather work undisturbed, and the <a href=\"grass-range.html\">grass driving range</a> runs through the drier months for anyone who wants real turf under the ball."),
                 ("h3", "The Weather Is Awful or You Are Booking for a Group"),
                 ("p", "The <a href=\"trackman-simulator.html\">Trackman simulator</a> is £25 an hour indoors, and it is the busiest thing on site between November and February. Groups use it for course play, and golfers use it for measured practice when standing outside has stopped being appealing. It needs booking, particularly at weekends and across the Christmas period."),
                 ("h3", "Your Body Is Not Doing What You Ask It To"),
                 ("p", "Book <a href=\"tpi-screening.html\">TPI screening</a> at <strong>£75</strong>. It is a physical assessment that separates the swing faults you can coach away from the ones your body is currently preventing, and it changes the coaching plan that follows. Follow-up work runs in the <a href=\"golf-fitness.html\">golf fitness suite</a>, which is built around the golf swing rather than general fitness."),
                 ("h3", "You Are Booking for a Child or Joining a Group"),
                 ("p", "The <a href=\"junior-academy.html\">junior academy</a> covers ages six to sixteen, and the <a href=\"ladies-academy.html\">ladies academy</a> runs women-only groups for beginners and improvers. Both work on blocks of sessions, so ring 07710 582036 or send an enquiry to find out when the next block starts and whether there is space in it."),
             ], "alt": True},

            {"type": "rel", "kick": "Before you get in touch",
             "h2": "What Else Might You Want to <em>Check First?</em>",
             "p": "A few pages that answer most of what people ask us on the phone.",
             "links": [
                 ("faqs.html", "Frequently Asked Questions",
                  "Prices, equipment, weather, cancellations, gift vouchers and what a first visit actually involves.", "Read FAQs"),
                 ("location.html", "Location and Directions",
                  "Nottingham Road, Codnor, Ripley DE5 9RL. Routes from Derby, Nottingham, the M1 and nearby towns.", "Find us"),
                 ("meet-team.html", "Meet the Team",
                  "Will Painter, Advanced PGA Professional. Read this if you want to know who you will be working with.", "The coaching"),
                 ("about.html", "About the Academy",
                  "Why the academy exists, what Trackman Official Performance Centre means and what is on the site.", "About us"),
                 ("1-1-lessons.html", "1:1 Golf Lessons",
                  "Sixty minutes with an Advanced PGA Professional in the private Trackman teaching bay, £55.", "Golf lessons"),
                 ("trackman-range.html", "Trackman Driving Range",
                  "Walk-in practice with live ball data, seven covered floodlit bays, baskets from £4.", "The range"),
             ]},

            {"type": "faq", "kick": "Common questions",
             "h2": "Booking Golf Lessons Near Derby &amp; Nottingham - <em>FAQs.</em>",
             "qs": [
                 ("How quickly will you reply to my enquiry?",
                  "We answer within a working day. A coach reads the message rather than an automated system, so the reply comes back with a suggested session and times rather than a generic acknowledgement. If your enquiry is urgent, ringing 07710 582036 between 7am and 8pm is faster than writing."),
                 ("Can I call instead of using the form?",
                  "Yes. Ring 07710 582036 any day between 7am and 8pm. If a coach is mid-lesson the call may go unanswered for a few minutes, so leave a message and it will be returned. The form is useful when you want to explain something in detail, because it gets read carefully rather than scribbled on a notepad."),
                 ("Do I need to book the driving range?",
                  "No. The <a href=\"trackman-range.html\">Trackman driving range</a> is walk-in and first come, first served, every day from 7am to 8pm. Baskets start from £4. Only <a href=\"1-1-lessons.html\">golf lessons</a>, private bays at £15 an hour, the simulator, custom fitting and <a href=\"tpi-screening.html\">TPI screening</a> need booking in advance."),
                 ("How do I book the Trackman simulator?",
                  "Book online or ring 07710 582036. The <a href=\"trackman-simulator.html\">Trackman simulator</a> is £25 an hour and is the busiest thing on site from November through February, so weekend slots and anything over the Christmas period go early. Groups are welcome, and it is worth saying how many of you there are when you book."),
                 ("Do you sell gift vouchers for golf lessons?",
                  "Yes, and a lesson makes a considerably better present than another pair of novelty socks. Vouchers can be bought for a 1:1 lesson, a block of coaching or a value amount to spend on the range or simulator. Ring 07710 582036 or send an enquiry through this page and we will arrange it, including at short notice."),
                 ("What is your cancellation policy?",
                  "Give us as much notice as you can and we will move the booking with no bother. Late cancellations are harder because the slot usually cannot be refilled, so we ask for at least 24 hours where possible. If you are ill or stuck in traffic on the A610, ring 07710 582036 and tell us rather than not turning up."),
                 ("Do I need my own clubs to book a lesson?",
                  "No. We can lend you a set for lessons, and the range and simulators include club hire at no extra cost, which is why <a href=\"get-into-golf.html\">Get Into Golf</a> and <a href=\"beginner-coaching.html\">beginner coaching</a> work for people who own nothing at all. If you do have clubs, bring them, because a coach seeing your actual equipment sometimes explains a fault faster than anything on the screen does."),
                 ("Where are you and how far is it from Derby or Nottingham?",
                  "Ormonde Fields Golf Club, Nottingham Road, Codnor, Ripley DE5 9RL. About fifteen minutes from Derby and twenty from Nottingham, both on the A610, with free parking on site. Detailed routes, including from the M1 at Junction 26 and from Belper, Alfreton and Heanor, are on our <a href=\"location.html\">location page</a>."),
             ]},
        ],
    },
]
